### ISSUE TITLE
文章主题功能

### ISSUE THREAD

**Issue by blackfader** [firekylin/firekylin#217]
加个主题功能如何？比如某一类文章都是这个主题相关的，然后再左侧栏能有一个展示，这个主题添加新文章了会自动纳入这个主题中。
标签和分类，展示性比较弱，太多的标签和分类也不想都展示出来，主题相当于文章更好的“收集”和“提炼”

**Comment by lizheming** [comment]
这个需求应该用分类就可以满足了，做一个分类显示就可以了，之前我在做另一款主题的时候已经考虑过这个了，等我发布出来吧。
