### ISSUE TITLE
markdown错误的标签会把整个页面搞挂

### ISSUE THREAD

**Issue by snadn** [firekylin/firekylin#255]
![image](https://cloud.githubusercontent.com/assets/1269858/24143928/6495f076-0e66-11e7-9dd4-4e0400084ab4.png)

如图，错误的 div 标签，让整个页面混乱。如果是个错误的 style 标签，就让整个页面都无法编辑了。

**Comment by lizheming** [comment]
这个是已知问题，暂时没有特别好的解决办法。
