### ISSUE TITLE
Sitemap 优化

### ISSUE THREAD

**Issue by ddhhz** [firekylin/firekylin#262]
『[Sitemap](https://github.com/75team/firekylin/blob/0.15.5/src/home/controller/index.js#L39)』 只包括了 posts，应当包括所有搜索引擎需要 index 的页面。例如：
 * `/` 主页
 * `/post/*` 所有文章
 * `/page/*` 所有页面
 * `/tag/*` 所有标签
 * `/tags` 标签
 * `/cate/*` 所有分类
 * `/categories` ？类似 `/tags` 的页面，貌似不存在。目前是通过 post 下方的链接可以进入指定的分类。
 * `/archives` 归档
 * `/links` 友链
 * `/about` 关于

可以考虑增加 `robots.txt` 功能
```
User-agent: *
Disallow: /admin
Disallow: /page/about
```

**Comment by lizheming** [comment]
是的，这块一直有问题，说是要加结果忙了一直忘记了。如果你有时间欢迎 pr 加一下。

**Comment by ddhhz** [comment]
回复神速呀！请问分类是怎么个情况？目前我只看到从 post 底下有入口？以后有没有像 /tags 类似的打算？

**Comment by lizheming** [comment]
没有，这个需求和 #217 是一样的，之前是打算给主题加一个分类列表获取的方法的，这样就能在主题里渲染使用了，不过比较忙一直没来得及做…

**Comment by ddhhz** [comment]
In progress. Blocked by #265.

**Comment by ddhhz** [comment]
已经完成添加以下进 `sitemap.xml`
 * `/` 主页
 * `/archives` 归档
 * `/post/*` 所有文章 (existing)
 * `/page/*` 所有页面

以下两个如果用户加了页面的话都已经包含在了 `/page/*` 里了，感觉应该够了不需要额外添加。
 * `/links` 友链
 * `/about` 关于

Blocked by bugfix from #265
 * `/tag/*` 所有标签
 * `/tags` 标签
 * `/cate/*` 所有分类
 * `/categories` ？类似 `/tags` 的页面，貌似不存在。目前是通过 post 下方的链接可以进入指定的分类。


>**有两个问题请教一下：**
>
> 1. `post` 和 `pages` 默认带 `.html`。我看你的 Project 里有关于 Permalink 的未来计划，是不是以后希望丢掉这个后缀？是的话我可以现在就在 sitemap 里先丢掉这个后缀？不带 `.html` 的链接打开也完全没问题可以被用来做 sitemap。如果有意保留的话我就不丢咯。
>
> 2. 请问你希望我把已完成的
> * `/` 主页
> * `/archives` 归档
> * `/post/*` 所有文章 (existing)
> * `/page/*` 所有页面
>
> 先 pull request 进来 还是等 #265 解决了再一起 pull？不知道你 release schedule 是啥样。: P

**Comment by lizheming** [comment]
感谢~

1. 按照之前的理解如果是同页面索引太多的话 Google 反而会降权重，所以 `/links` 和 `/about` 这两个页面你看着来吧。
2. 那个未来是计划可以自定义 url 格式的，目前还没打算做，先按照现有的格式保留 `.html` 吧。
3. 等我把 #265 的问题 fix 了你把 `/tags/{{slugname}}` 等相关的添加一下再 pr 吧，或者你先把相关的先补全了 pr 了之后我再 fix 那个 bug 也没关系。下个版本的 release 应该还有段时间，不是很急。

**Comment by ddhhz** [comment]
1. 嗯嗯查了一下 Google 说 [canonicalization](https://support.google.com/webmasters/answer/66359?hl=en) 就够咯，只要不是滥用重复页面提升 SEO 的行为。

> If your site contains multiple pages with largely identical content, there are a number of ways you can indicate your preferred URL to Google. (This is called "canonicalization".) [More information about canonicalization](https://support.google.com/webmasters/answer/139066).

> However, in some cases, content is deliberately duplicated across domains in an attempt to manipulate search engine rankings or win more traffic. Deceptive practices like this can result in a poor user experience, when a visitor sees substantially the same content repeated within a set of search results.

 [`rel="canonical"`](https://yoast.com/rel-canonical/) 应该就是最好的方法咯。本来就没几页是重的，我可以在 theme 里 layout.html 加上这个 header.

2. Ok!

3. Category 有修补的打算吗？感觉他好可怜：
  * `{{slugname}}` aka `{{pathname}}` - 和 tag 一样的问题 #265 
  * pathname 需要自动设置 - 和 tag 一样的问题 #203 
  * 缺类似 `/tags` 的一页

还是准备暂时忽略他？

我到时候一起 pr 哈。

**Comment by lizheming** [comment]
#265 已经标记为 bug 了 ，`/categories` 这个页面不会有，已经说过同 #217 了。

**Comment by ddhhz** [comment]
👌 谢咯！

**Comment by lizheming** [comment]
还有一个需要增加列表分页索引。

**Comment by lizheming** [comment]
#265 has fixed
