### ISSUE TITLE
搜索页分页问题

### ISSUE THREAD

**Issue by xuexb** [firekylin/firekylin#267]
搜索结果页没有分页? 我看显示很多条, 底部没有分页, 但试图直接修改`url`是可以的, 如:

- 第一页: [https://xuexb.com/search.html?keyword=我](https://xuexb.com/search.html?keyword=%E6%88%91)
- 第二页: [https://xuexb.com/search.html?keyword=我&page=2](https://xuexb.com/search.html?keyword=%E6%88%91&page=2)

**Comment by xuexb** [comment]
ThinkJS版本：2.2.17
FireKylin版本：0.15.5

**Comment by lizheming** [comment]
搜索的样式一直都没有调过，如果有时间欢迎 pr 修改下 👍
