### ISSUE TITLE
请问是否可以增加某个配置以支持https啊？

### ISSUE THREAD

**Issue by mojie126** [firekylin/firekylin#268]
请问是否可以增加某个配置以支持https啊？

**Comment by lizheming** [comment]
#31

**Comment by mojie126** [comment]
这个我看到了，但是看起来是用node https.js启用服务了？不能用pm2 start pm2xxx.js启用了...？

**Comment by lizheming** [comment]
https 支持和 nginx 相关，和 Firekylin 本身服务没有关系，`node https.js` 只是用来生产证书并更新 nginx 配置文件而已。

**Comment by mojie126** [comment]
我已经让nginx支持https了，也代理8360端口了，就无法访问，直接访问IP:PORT的形式就可以

**Comment by lizheming** [comment]
nginx 配置贴一下，网站也贴一下

**Comment by mojie126** [comment]
不好意思，我的锅，我把CmsWing的配置直接拿来用了，看起来差不多，没想到root位置不一样...╮(￣▽￣")╭

**Comment by lizheming** [comment]
OK ~
