### ISSUE TITLE
pm2启动报错， Nginx root应该指向哪里？

### ISSUE THREAD

**Issue by toringo** [firekylin/firekylin#271]
pm2文件配置：
![image](https://cloud.githubusercontent.com/assets/17404085/24574797/c5d59cf8-16ca-11e7-9dd8-413b86ba094e.png)

nginx配置文件：
![image](https://cloud.githubusercontent.com/assets/17404085/24574815/22d3f684-16cb-11e7-863e-a0da795c3711.png)

不用pm2, 用node直接起8360端口， 浏览器找不到index.html：
![image](https://cloud.githubusercontent.com/assets/17404085/24574828/54b14b98-16cb-11e7-896e-a1a74f9ec8c0.png)

**Comment by lizheming** [comment]
是不是端口被占用了... 这个错误提示看起来不太像是 ThinkJS 的 404 提示，你直接使用 `node www/production.js` 启动试一下。

**Comment by lizheming** [comment]
close with long time inactivity.
