### ISSUE TITLE
前台如何显示分类列表？

### ISSUE THREAD

**Issue by ghostrin** [firekylin/firekylin#274]
用这个系统的，99%的都是固定的这个几个菜单： 首页  归档  标签  关于 友链；为什么就不支持“前端技术、后端技术”类似这样维度的菜单列表呢？

我在后台添加了几个分类，并且每个分类里对应有若干文章，请问：前台怎么将该分类里的文章都列表显示出来？如果首页还要显示多个分类的多个列表呢？

归档文件显示的是按照时间维度的列表，不是我想要的；通过tag，显示的列表太杂，也不是我想要的。

**Comment by lizheming** [comment]
same with #217
