### ISSUE TITLE
主题目录内的 js css 直接编辑无效

### ISSUE THREAD

**Issue by ddhhz** [firekylin/firekylin#279]
安装版编辑主题目录下的 css / js 无效。因为 layout.html hard code 进去了。

“以后拆出来” per @lizheming on gitter。

![image](https://cloud.githubusercontent.com/assets/5880908/24611808/4caaaa02-1851-11e7-9877-9eadb4bbe5f4.png)

**Comment by xuexb** [comment]
我理解这是正常的吧? 安装版本提供的是 dist 打包版本, 按理说不应该让开发者修改源码的, 如果你要修改(定制化), 你应该使用 [仓库版本](https://github.com/firekylin/firekylin/wiki/%E4%BB%93%E5%BA%93%E7%89%88%E5%AE%89%E8%A3%85) 吧.

如果说"以后拆出来", 我感觉是不是可以把主题单独的领出来独立成 npm 包呢? 比如: `firekylin-theme-xxoo`, firekylin 核心只提供一些数据变量, 模板你说了算...
