### ISSUE TITLE
安装后无static文件夹

### ISSUE THREAD

**Issue by golmic** [firekylin/firekylin#283]
如题，后台页面空白，前台无http://blog.lujq.me/static/img/firekylin.jpg

<img width="1426" alt="qq20170406-154243 2x" src="https://cloud.githubusercontent.com/assets/7007115/24743163/d248f1a6-1adf-11e7-9646-c845d69ea6ac.png">

项目根目录中无 static 文件夹 ，只有下面这些文件/文件夹

<img width="488" alt="qq20170406-153943 2x" src="https://cloud.githubusercontent.com/assets/7007115/24743153/c8c290ba-1adf-11e7-85cb-7eec7714c8e5.png">

**Comment by lizheming** [comment]
root 要指定到 `www` 目录下，静态资源都在那里。
