### ISSUE TITLE
我把自己的账户删了,就没法登陆了。可以限制不能删除自己么

### ISSUE THREAD

**Issue by zxysilent** [firekylin/firekylin#286]

**Comment by zxysilent** [comment]
感谢 感谢

**Comment by zxysilent** [comment]
送你一杯水

**Comment by lizheming** [comment]
@zxysilent 收到了！非常感谢你的打赏~ https://github.com/firekylin/firekylin/wiki/%E6%8D%90%E8%B5%A0%E5%88%97%E8%A1%A8 已添加到捐赠列表中~

**Comment by zxysilent** [comment]
等我大学毕业了，找到工作就请你喝咖啡 ^_^

**Comment by lizheming** [comment]
哈哈哈，好的 😸
