### ISSUE TITLE
用户数据以及post数据可以支持软删除不

### ISSUE THREAD

**Issue by zxysilent** [firekylin/firekylin#288]

**Comment by lizheming** [comment]
为什么会有这个需求呢？

**Comment by zxysilent** [comment]
我其实不是真的想删除 post

**Comment by zxysilent** [comment]
好像可以，那用户那个呢，我今天尝试了删除自己，结果真的删除了

**Comment by lizheming** [comment]
#286 @xuexb 已经在 fix 了，争取今天发一版带上 😄

**Comment by zxysilent** [comment]
我现在只有重新部署一遍了，可以问个其他问题不。就是我直接修改了
login.jsx里面的东西 结果页面上面没变化

**Comment by lizheming** [comment]
`npm run webpack.build.production` 编译之后才会生效哈 ~

**Comment by zxysilent** [comment]
就是我想把后台界面 diy一下，然后修改了没变化。

**Comment by zxysilent** [comment]
webpack-dev-server --open  --config webpack.production.config.babel.js
我用这个 
按照你的方式我成功了
感谢你的热心回答，我才开始学校 webpack 问的问题有些幼稚 你多多包含

**Comment by lizheming** [comment]
嗯，可以直接用 `npm run webpack` 。

**Comment by zxysilent** [comment]
老是说，我没有在 api/user.js下面找到删除用户的方法

**Comment by zxysilent** [comment]
怪不得我没办法直接修改了，看来这个问题只有等你们 fix

**Comment by lizheming** [comment]
不用啊，你自己加上 `deleteAction` 就好了呀，ThinkJS 只是默认提供了 `GET`, `POST`, `DELETE` 等 Action 的简单操作，方便绝大多数的情况，但是你也可以自己写嘛。

**Comment by zxysilent** [comment]
我怕我自己写了 以后不好在线更新了

**Comment by lizheming** [comment]
嗯，这是自然，不过你直接修改后台模板照样也不好更新的说

**Comment by zxysilent** [comment]
等你们把这个bug修复了我再diy,因为已经这样了 我必须重新部署一遍

**Comment by lizheming** [comment]
欢迎把好的修改 pr 回主仓库里~ 😄

**Comment by zxysilent** [comment]
惭愧，还在学习git的使用

**Comment by lizheming** [comment]
没事~ 互相学习~

**Comment by zxysilent** [comment]
ok  会努力的
