### ISSUE TITLE
关于模板新增一个test.html

### ISSUE THREAD

**Issue by mojie126** [firekylin/firekylin#293]
模板里新增了一个test.html，但是提示是404
请问怎么不通过page新增页面啊？

**Comment by lizheming** [comment]
没办法，需要新增一个页面选择这个模板

**Comment by mojie126** [comment]
在哪里新增这个页面？

**Comment by lizheming** [comment]
https://imnerd.org/firekylin-custom-index.html 参考自定义模板小节
