### ISSUE TITLE
模板增加 taglist 和 postlist 数据

### ISSUE THREAD

**Issue by lizheming** [firekylin/firekylin#295]
增加标签列表和最近十篇文章列表数据，用于在某些主题侧边栏显示。代码参考这里即可：https://github.com/firekylin/firekylin/blob/master/src/home/controller/base.js#L57

**Comment by ddhhz** [comment]
标签列表添加后

https://github.com/firekylin/firekylin/blob/40bee12349c8ba07e937a01048b5be3666d6ba4f/src/home/controller/index.js#L58-L60

就可以删掉了

**Comment by ddhhz** [comment]
加上这些东西 每个请求都要数据库好多次 不会影响性能么

**Comment by lizheming** [comment]
@ddhhz 先这么着吧，现在模板不支持异步获取数据，不管有的没的数据只能先拿到再渲染了。http://dustjs.com 这个模板引擎是支持异步获取数据的，后期再看看能不能改成这个。

**Comment by ddhhz** [comment]
Should've closed with #306 merge.
