### ISSUE TITLE
tags 路径错误

### ISSUE THREAD

**Issue by p2yang** [firekylin/firekylin#299]
今天在线更新后，标签页 `/tags/git` 出现 404，而实际路径是 `/tag/git`，应该是没有 build 到生产环境，求教！
地址：

404: [http://p2yang.com/tags/git](http://p2yang.com/tags/git)

实际：[http://p2yang.com/tag/git](http://p2yang.com/tag/git)

**Comment by xuexb** [comment]
@p2yang 这版本更新了 `/tags/{q}` 的路径, 我理解是因为 `/tags` 显式的为复数, 而具体到某个标签时 `tag` 要更语义些, 如果你是 Nginx, 可以添加一条301转发的规则, 如:

```
rewrite ^/tags/(.+?)/?$ /tag/$1 permanent;
```

添加后记得reload下~

**Comment by p2yang** [comment]
@xuexb 好的，多谢~
