### ISSUE TITLE
微信分享无图标

### ISSUE THREAD

**Issue by ringcrl** [firekylin/firekylin#302]
谢谢你们分享了一款那么棒的博客系统，一切的体验都太棒了，可是有一点是写的文章，分享到微信的时候没有图标，这样分享就会显得比较丑，之前做项目遇到这个问题，有个答案是在页面前面放一个

<div style="margin:0 auto;width:0px;height:0px;overflow:hidden;">
    <img src="">
 </div>

标签，微信就会读取出来了，这样分享就会带有图标。

我尝试把这段代码放到firekylin的统计部分，这样每个页面都会有这段代码，不知道为什么一直没有生效。

**Comment by lizheming** [comment]
微信分享加图标这个比较诡异，如果不用 jssdk 的话，貌似是需要一张一定大小的图片默认加载完成才 OK。感谢提醒！你能帮忙看看如果有一张大图的情况下分享的时候会有图片么？

**Comment by ringcrl** [comment]
<img width="1013" alt="qq20170412-225519 2x" src="https://cloud.githubusercontent.com/assets/16740021/24964185/27e2d13e-1fd3-11e7-867b-c811c5a14b36.png">


以前在body的第一个元素添加一个图，是可以的，但是现在在js中动态创建一个图，发现就不行了，怀疑是微信读图比创建这个图的时间要早导致了

**Comment by lizheming** [comment]
嗯，微信分享这个确实头疼，我们后续再研究下~

**Comment by ringcrl** [comment]
按照上面的思路，写个静态页面，在body里面第一个元素插个大于300的隐藏图片，是可以显示的。。不知道在现有基础上能不能把那个标签写死在某个地方实现。。

**Comment by ringcrl** [comment]
看不太懂模板修改部分怎么插代码，在js里面插的话估计插进去微信已经读完了

**Comment by lizheming** [comment]
你在layout.html里写试试

**Comment by ringcrl** [comment]
<img width="314" alt="qq20170413-075140 2x" src="https://cloud.githubusercontent.com/assets/16740021/24984106/0afb2792-201e-11e7-9995-3a6a17816a8a.png">

 编辑后保存报错了

**Comment by lizheming** [comment]
你看一下控制台报什么错了？

**Comment by ringcrl** [comment]
原来不是必现啊。会不会我服务器没有配对呢

<img width="912" alt="qq20170413-093950 2x" src="https://cloud.githubusercontent.com/assets/16740021/24986503/392d3dc6-202d-11e7-9226-ab968423628b.png">

**Comment by ringcrl** [comment]
修改资料这里，估计和上传图片一个问题，可以修改layout.html了。最后我试了很多种以前可行的方案，增加到body头部，发现都不显示图像了，看了看以前显示设置图的项目，现在分享页不显示了，估计新版微信干掉了这个分享图的hack方案。。有时间我再研究研究，分享到朋友圈没有图确实好难看= =

**Comment by lizheming** [comment]
@ringcrl OK，据我最近了解到的信息是分享图的逻辑没有改变，应该还是我们的页面结构和图片的问题。

**Comment by yiling-e0** [comment]
https://mp.weixin.qq.com/s/hAdtKl2i4ilyo9HxT1kXyw  好像是已经限制了，能否在后台增加配置微信公众号的功能吗

**Comment by lizheming** [comment]
@yiling-e0 目前 JSSDK 的话可以在外观设置-主题管理-自定义JS中添加，默认主题的确可以考虑加一个这个设置的入口，期待后续版本吧~

**Comment by lizheming** [comment]
据了解微信已经禁止了所有除了 jssdk 以外的自定义封面图的行为了，目前有两种方法解决这个问题：
- 域名进行认证公众号后台绑定安全域名后使用 jssdk 进行定义分享的封面图等内容
- 使用国内支持分享到微信功能的浏览器打开网页（例如：UC浏览器，360浏览器等）利用浏览器的分享接口进行分享

第一种方法的成本比较高，但是自由度很高，第二种方法非常简单，成本小但缺点是分享的内容会带上浏览器的小尾巴。有结论了就暂时先关闭这个问题了，大家可以按需选择对应的方法。
