### ISSUE TITLE
希望可以增加HOST环境变量

### ISSUE THREAD

**Issue by mojie126** [firekylin/firekylin#308]
现在只看到有PORT环境变量，但是貌似没看到HOST环境变量
如果想绑定指定IP的话如何操作？
比如我只想绑定127.0.0.1，因为不想外部也能访问IP:PORT的形式访问到项目

**Comment by mojie126** [comment]
这样岂不是更新时会被自动覆盖掉么...？是否可以在pm2.json的env里设置...？

**Comment by ddhhz** [comment]
你防火墙打开不就行了 🤓
