### ISSUE TITLE
上传图片报错

### ISSUE THREAD

**Issue by ringcrl** [firekylin/firekylin#311]
<img width="1150" alt="qq20170414-210045 2x" src="https://cloud.githubusercontent.com/assets/16740021/25043842/8ae045b8-2155-11e7-8602-ffacd9e69e81.png">

从本地上传一张图片，遇到报错问题

**Comment by ddhhz** [comment]
请把网络里请求和 response 贴过来

**Comment by ringcrl** [comment]
<img width="1323" alt="qq20170414-212342 2x" src="https://cloud.githubusercontent.com/assets/16740021/25044326/aeb3177e-2158-11e7-98c7-bc4cc759d4c0.png">

**Comment by ringcrl** [comment]
<img width="517" alt="qq20170414-212732 2x" src="https://cloud.githubusercontent.com/assets/16740021/25044413/2ef0e72c-2159-11e7-8253-9c5835300c72.png">

**Comment by ringcrl** [comment]
不知道是不是权限问题，我把api文件夹里面所有文件都加了可执行权限chmod +x，就不报500错误了，但是报413错误，这就奇怪了= =

<img width="1181" alt="qq20170414-220408 2x" src="https://cloud.githubusercontent.com/assets/16740021/25045339/6d3eed44-215e-11e7-8269-eadac9d9c311.png">

**Comment by ringcrl** [comment]
重装了一次还是不行，报500错误，不知道是不是nginx的问题了

**Comment by ddhhz** [comment]
额 请把 response preview 贴过来。看看是500错误有没有包含错误信息。

**Comment by ringcrl** [comment]
<img width="1149" alt="qq20170414-225459 2x" src="https://cloud.githubusercontent.com/assets/16740021/25046698/7984db66-2165-11e7-9571-a32ce74ca735.png">


好诡异，有时500，有时413，已经重装2次了

**Comment by ddhhz** [comment]
额 你传一个很小很小的图试试，再看上传的文件是不是超了 nginx 设置里的 client_max_body_size

**Comment by ringcrl** [comment]
我传的图都不超过100k

user common;
worker_processes 2;

events {
    use epoll;
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
	listen 80;
        server_name ringcrl.com;
        root /home/common/firekylin/www;
        set $node_port 8360;

        index index.js index.html index.htm;

        location ^~ /.well-known/acme-challenge/ {
            alias /home/common/firekylin/ssl/challenges/;
            try_files $uri = 404;
        }

        location / {
            proxy_http_version 1.1;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:$node_port$request_uri;
            proxy_redirect off;
        }

        location = /development.js {
            deny all;
        }
        location = /testing.js {
            deny all;
        }

        location = /production.js {
            deny all;
        }

        location ~ /static/ {
            etag         on;
            expires      max;
        }
	
	location ~ /web/ {
            etag         on;
	    expires      max;
        }
    }
}


贴一下我的nginx配置

**Comment by mojie126** [comment]
今天下午我也遇到了
最后我结束了pm2，用npm start启用一次结束掉后换回pm2启动就又好了，赶脚跟那个token < xxx的信息有关系...不知道是不是检测升级的问题...

**Comment by ringcrl** [comment]
好吧，试了试楼上方法，还是500错误，不知道是不是nginx导致的= =

**Comment by ddhhz** [comment]
500 错误的 response 贴个图看看有木有错误信息

**Comment by lizheming** [comment]
@ringcrl 你是上传到本地是么？看看是不是 `www/static/upload` 上传文件夹的权限问题。另外就是上传的时候看一下终端 node 这块的报错。

@mojie126 前段 `Unexcepted token` 这个错误是因为后台报错返回的是 500 HTML 页面，接口 JSON 解析自然失败了，和这个关系不大，主要还是得解决后端报错。

**Comment by ringcrl** [comment]
client_max_body_size 5m;
    client_body_buffer_size 16k;
    client_body_temp_path /home/common/temp;

查了很多资料，最后在nginx的http{}配置块里面加入了这三行，就可以了，common用户登录，nginx头配置为user common，估计还是权限的问题吧。

**Comment by lizheming** [comment]
@ringcrl 好的，问题解决就好，给你点个赞！
