### ISSUE TITLE
保存草稿后回不来了= =

### ISSUE THREAD

**Issue by ringcrl** [firekylin/firekylin#312]
额，写了一下午的东西，不知道什么原因，保存草稿后就进不回来了= =

<img width="1212" alt="qq20170415-195454 2x" src="https://cloud.githubusercontent.com/assets/16740021/25063386/71bda290-2215-11e7-9827-e802c6bf505e.png">

**Comment by lizheming** [comment]
重启服务试试，server 返回的内容和 header 的 content-length 对不上了，或者 Chrome 关闭高级设置里的 “预提取资源，以便更快速的加载网页” 试试。

**Comment by lizheming** [comment]
closed with long time inactivity.
