### ISSUE TITLE
建议加入user.email信息

### ISSUE THREAD

**Issue by NangeGao** [firekylin/firekylin#314]
希望在index.html和post.html页面都可以打入user.email的信息，这样制作博客主题的时候，就可以通过邮箱获取到gravatar头像，丰富主题内容。

**Comment by xuexb** [comment]
@NangeGao 这个`user.email`是指当前文章作者的邮箱还是指当前博主的邮箱呢?

1. 如果是当前文章作者的, 可以透传到文章`post`数据对象中
2. 如果是博主的, 可能需要加个`options`字段了? @lizheming 或者说加个博主专用的`user.type`?

**Comment by lizheming** [comment]
@xuexb 当前文章的，放到 post.user 里就好了
