### ISSUE TITLE
后台的左侧sidebar，只显示概述和文章管理，其他菜单不见了

### ISSUE THREAD

**Issue by NangeGao** [firekylin/firekylin#316]
我是用admin登录的，并非一个单纯的博客编辑角色，感觉是权限控制出bug了

**Comment by lizheming** [comment]
查看下源码看看你的 `window.SysConfig.userInfo.type` 是多少？

**Comment by NangeGao** [comment]
2

**Comment by lizheming** [comment]
`type=1` 才是管理员

**Comment by NangeGao** [comment]
查了一下数据库，admin的type确实是1。是不是昨天的某个commit带出来的bug，今天早晨pull完代码，就这样了。

**Comment by lizheming** [comment]
和昨天的修改没关系，昨天就一个 commit，还是删除了一个文件而已。你的 `type` 是否有在 mysql 中直接修改过，重启下 firekylin 服务看看是不是缓存的问题。

**Comment by lizheming** [comment]
close with long time inactivity.
