### ISSUE TITLE
数据库系统有误

### ISSUE THREAD

**Issue by guider** [firekylin/firekylin#317]
如图 配置失败![](http://ww2.sinaimg.cn/large/006tNbRwly1fersq8qrf0j30t20hs0u3.jpg)

**Comment by guider** [comment]
我的QQ277892183 求破

**Comment by xuexb** [comment]
@guider 你`blog`数据库是不是不存在? 如果不存在就创建个编码是`utf8`, 默认排序是`utf8_general_ci`,
 数据库名是`blog`的数据库再试下

**Comment by guider** [comment]
@xuexb   blog 已经创建了  能不能私聊  请教一下 谢谢 ![](http://ww2.sinaimg.cn/large/006tKfTcly1fes2b0po2wj30iq08amxs.jpg)

**Comment by xuexb** [comment]
你的mysql端口自定义过? 默认是3306

**Comment by xuexb** [comment]
@guider 重新给你装了下数据库就好了... 应该是数据库配置问题, 但我试了很多方法都行只能重装了...
