### ISSUE TITLE
后台管理：修改用户组和状态有bug

### ISSUE THREAD

**Issue by NangeGao** [firekylin/firekylin#319]
https://github.com/firekylin/firekylin/blob/master/www/static/src/admin/component/user_create.jsx#L164
这里用了 `===`
然而在这里（https://github.com/firekylin/firekylin/blob/master/www/static/src/admin/component/user_create.jsx#L264 ）就应该是`<option value="2" {...this.getOptionProp('type', 2)}>编辑</option>` 了，数据类型不对。

**Comment by NangeGao** [comment]
还有，用户邮箱好像修改不了

**Comment by lizheming** [comment]
那你 pr 改一下吧 =w=
