### ISSUE TITLE
安装后首页显示不全，admin后台显示空白

### ISSUE THREAD

**Issue by jiespring** [firekylin/firekylin#325]
```
server {
    listen 80;
    server_name blog.duoyici.com;
    root /root/wwj/firekylin/www;
    set $node_port 8360;

    index index.js index.html index.htm;

    location ^~ /.well-known/acme-challenge/ {
      alias /root/wwj/firekylin/ssl/challenges/;
      try_files $uri = 404;
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

    location = /development.js {
        deny all;
    }
    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
    }


    location ~ /static/ {
        etag         on;
        expires      max;
    }
}
```

**Comment by jerrybendy** [comment]
发出来的内容也格式化一下呀…… 另外你是用的什么安装方式？

**Comment by jiespring** [comment]
正常模式，出来这样，后来换仓库模式，不想，后来又换回正常模式、

**Comment by ddhhz** [comment]
首页、admin 页，console 有报错吗？

**Comment by jiespring** [comment]
不知道怎么检查 console? 网站blog.duoyici.com 安装后首页显示不全，admin也全是空白的。

**Comment by ddhhz** [comment]
看了下是你 `/static` 的请求都是 403 错误的原因。

**Comment by jiespring** [comment]
后台进不去

**Comment by jiespring** [comment]
服务器登录账户已通过email发给Austin Lee。你们可以登录服务器看看。

**Comment by ddhhz** [comment]
Austin Lee 是谁：X

**Comment by ddhhz** [comment]
你可以看下 #117 看看是不是文件夹权限问题。

**Comment by lizheming** [comment]
@ddhhz Austin Lee 是我~
@jiespring 确认是权限问题，修改权限后正常了。

**Comment by jiespring** [comment]
firekylin默认没有编译 admin(后台)的js 所有www/static下面没有js 所以会出现 403， 需要检查js文件存在 且有可访问权限即可！https://github.com/firekylin/firekylin/issues/117
希望改进哦。

**Comment by lizheming** [comment]
@jiespring 这个是 feature 啦~仓库版就是不编译的，自己运行命令即可，要不然自己装安装版~

**Comment by ddhhz** [comment]
@jiespring `www/static` 下面没有 js 应该会出现 404 吧。403 是文件夹权限的问题。

**Comment by jiespring** [comment]
最好是在安装说明里写一下，仓库吧不编译，或许是我没看到。

**Comment by ddhhz** [comment]
[仓库版安装](https://github.com/firekylin/firekylin/wiki/仓库版安装) 里写了 

> 3. 启动环境
>
> 首先在一个窗口下执行 npm run webpack 进行 React 代码的实时编译
> 然后在另一个窗口下执行 npm start 来启动服务。

不过那主要是针对本地开发的。可以考虑添加：
仓库版如果用在生产环境：

 a. `npm run compile`
 b. `npm run webpack.build.production`

然后根据[安装版](https://github.com/firekylin/firekylin/wiki/%E5%AE%89%E8%A3%85)的 4. 配置 PM2 继续配置。

**Comment by lizheming** [comment]
@ddhhz 这个是发布版本专用的脚本，运行这个脚本也处理不了这个问题😄

**Comment by jiespring** [comment]
现在开https后是404错误了，(⊙﹏⊙)

**Comment by jiespring** [comment]
文件权限和所有者都改好了，还是不显示静态文件。

**Comment by jiespring** [comment]
`#https nginx conf

server{
    listen 443;
    server_name blog.duoyici.com;
    root /root/wwj/firekylin/www;
    set $node_port 8360;
#    set $patht /root/wwj/firekylin;

    ssl on;
    ssl_certificate  /root/wwj/certs/blog.duoyici.com/fullchain.pem;
    ssl_certificate_key /root/wwj/certs/blog.duoyici.com/privkey.pem;

    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA......省略
    ssl_session_cache shared:SSL:50m;
    ssl_session_cache shared:SSL:50m;
    ssl_dhparam /root/wwj/certs/blog.duoyici.com/dhparams.pem;
    ssl_prefer_server_ciphers on;


    index index.js index.html index.htm;

    location ^~ /.well-known/acme-challenge/ {
      alias /root/wwj/firekylin/ssl/challenges/;
      try_files $uri = 404;
    }

   location / {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

    location = /development.js {
        deny all;
    }

    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
   }


   location ~ /static/ {
      etag on;
      expires max;
   }
}`

**Comment by ddhhz** [comment]
看到了现在又是一堆 403 权限 错误。需要的话我可以帮你看一下。邮箱在 github profile 里。

![image](https://cloud.githubusercontent.com/assets/5880908/25563547/0f6145c2-2d6c-11e7-9014-b44197c79b30.png)

**Comment by jiespring** [comment]
@lizheming 在不？
