### ISSUE TITLE
管理员自己的文章审批权限、文章时间错误

### ISSUE THREAD

**Issue by jiespring** [firekylin/firekylin#326]
管理员自己的文章发布会，再修改后，好像需要审核，谁来批准发布呢！自己只能点【拒绝】，点不了【通过】按钮额！

**Comment by lizheming** [comment]
如果是的话那应该是 BUG，你确认下复现流程，我这边并没有复现。

**Comment by jiespring** [comment]
文章发布时间我写错了！^_^

**Comment by jiespring** [comment]
发布时间，空着的话，最后显示有问题，我现在9点钟发布，文章显示最后编辑时间29日01:00:21，没弄明白。

**Comment by lizheming** [comment]
你服务器的时区不对，设置成东8时区即可。

**Comment by jiespring** [comment]
哦

**Comment by jiespring** [comment]
系统时间修改后，博客时间还是异常，怎样更新博客里的时间？

**Comment by jiespring** [comment]
暂时弄好了。修改了服务器系统时间，用pm2重启了进程。但发现nginx重启错误，网站竟然还能用！

**Comment by lizheming** [comment]
好的，那我先关闭这个 issue 了。重启失败一般是之前检测配置不过，这时候没有关闭服务，所以即使失败了也还能用。如果是修改系统时间的话不需要重启 nginx 重启下 firekylin 服务就好了
