### ISSUE TITLE
添加一篇 Hello World 文章

### ISSUE THREAD

**Issue by lizheming** [firekylin/firekylin#330]

**Comment by ddhhz** [comment]
`firekylin.sql` 添加如下：

```sql
INSERT INTO `fk_post` 
            (`user_id`, 
             `type`, 
             `status`, 
             `title`, 
             `pathname`, 
             `summary`, 
             `markdown_content`, 
             `content`, 
             `allow_comment`, 
             `create_time`, 
             `update_time`, 
             `is_public`, 
             `comment_num`, 
             `options`) 
VALUES      ('1', 
             '0', 
             '3', 
             'Hello World!', 
             'hello-world', 
             '<p>Hello world!</p>', 
             '<p>Hello world!</p>', 
             'Hello world!', 
             '1', 
             Now(), 
             Now(), 
             '1', 
             '0', 
             '{\"template\":\"\",\"push_sites\":[]}') 
```

内容模仿 WordPress 的话可以写这个 `Welcome to Firekylin. This is your first post. Delete it, then start blogging!`

需要加 `tag`、`cate` 的话还需要加几行到别的桌子上。

**Comment by lizheming** [comment]
@ddhhz 嗯，主要是内容，想要写点简单的帮助内容，也可以有一些 Markdown 语法指导内容。

**Comment by choicky** [comment]
@lizheming 写了一篇给你参考，源码：[来自 Firekylin 的第一篇文章.txt](https://github.com/firekylin/firekylin/files/998730/Firekylin.txt)。

如有什么修改建议，可告知，我有空再调整。

另外，发现 firekylin 还没有支持待办事项列表的Markdown解析。
- [x] 成为万元户
- [ ] 解决温饱

------
# Hello World

这是程序自动发布的文章。

您可以删除这文章，但建议保留，以便后期查阅。

# 程序简介

您目前使用博客程序的是 [Firekylin](https://firekylin.org/) 。

[Firekylin](https://firekylin.org/) 是使用 [nodejs](https://nodejs.org/) 语言的博客系统，后端使用 [thinkjs 框架](https://thinkjs.org/) 开发，前端使用 [React 框架](https://facebook.github.io/react/) 开发。thinkjs 框架是兼容 ES2015+ （含 ES2016）标准的 nodejs 框架，React 框架是 [Facebook](https://facebook.github.io/react/) 主导开发的 nodejs 前端框架。

欢迎您关注 Firekylin 的 [Github Repo](https://github.com/firekylin/firekylin) ，更欢迎贡献代码、制作主题。

欢迎您关注 thinkjs 的 [Github Repo](https://github.com/thinkjs/thinkjs) ，更欢迎贡献代码、撰写教程。

# 常用操作

### 登录后台

Firekylin 的后台登录入口在 [~/admin](/admin)

### 网站基本设置

后台的 [系统设置](/admin/options/) 提供了与网站相关的选项，例如可在其中的 [基本设置](admin/options/general) 中设置网站名称、Logo地址、Favicon icon 的地址等。

更多的设置，请参考 [官方wiki](https://github.com/firekylin/firekylin/wiki/) 的 [系统设置](https://github.com/firekylin/firekylin/wiki/系统设置)

### 评论系统设置

Firekylin 没有内置评论模块。但是，Firekylin 可方便地使用第三方评论系统。在后台的 [系统设置](/admin/options/) 的 [评论设置](/admin/options/comment) 的 `自定义` 模式下粘贴第三方评论系统的代码即可。

Firekylin 还对 [Disqus](https://disqus.com/) 、[畅言](https://changyan.kuaizhan.com/) 、网易云跟帖](https://gentie.163.com/)  提供了特别的支持，只需要填写对应的网站id即可，不需要粘贴具体的代码。

### 分类设置

后台的 [分类管理](/admin/cate/) 可进行分类管理，包括 [新增分类](/admin/cate/create)、 [列出现有分类](/admin/cate/list)、删除分类等。

### 菜单管理

后台的 [外观设置](admin/appearance/) 可进行 [菜单管理](/admin/appearance/navigation)，包括新增菜单、删除菜单、菜单排序等。

新增菜单时，如填写了菜单属性（例如属性为 `home`），firekylin 自带的主题会从字体图标库（ [Font Awesome](http://www.bootcss.com/p/font-awesome/)）尝试寻找 `icon-home` 作为该菜单的图标，如未查到匹配的则不会显示图标。

### 主题外观

Firekylin 目前只带了一套主题，所以基于 Firekylin 架构的网站长得都差不多^_^

主题外观的使用、修改、创建可参考官网 wiki 的 [主题外观](https://github.com/firekylin/firekylin/wiki/主题外观)。

欢迎越来越多的热心用户为 Firekylin 开发主题外观，开发手册详见 [主题开发]( https://github.com/firekylin/firekylin/wiki/主题开发)。

# 编辑器简介

Firelylin 带有可视化编辑器，您在撰写博文、页面的时候，能实时预览内容渲染后的效果。撰写博文、页面的具体操作可参考 官方Wiki 的 [文章](https://github.com/firekylin/firekylin/wiki/文章)、[页面](https://github.com/firekylin/firekylin/wiki/页面)。

编辑器划分为左右两个区域，左侧区域包括编辑菜单和内容输入区，编辑菜单包括标题级别设置、**粗体**、_斜体_、[超链接]()、引用、`代码块`、插入图片、插入列表等，内容输入区显示当前输入的内容。右侧区域为预览区域，实时地把左侧的内容渲染出来。

2017年5月3日之后发布的 Firekylin 已经支持左侧区域、右侧区域同步滚动。

# Markdown 简介

Firekylin 的编辑器为支持 Markdown 语法的编辑器。Markdown 是一种简化的标记语言，普通的纯文本内容（例如 Windows 的记事本撰写的内容）经过 Markdown 标记之后，可被渲染成赏心悦目的富格式文本。

如果您不需要上传图片，您完全可以用第三方文本编辑器撰写出带有 Markdown 标记的纯文本内容，然后将撰写好的内容粘贴到编辑器的内容输入区，就可以直接发布了，不再需要进行格式的调整。

Markdown 的格式说明可参考：[英文版](https://guides.github.com/features/mastering-markdown/)、[中文版](https://coding.net/help/doc/project/markdown.html)

# 常见的 Markdown 语法

### **标题** 的语法

```
# 一级标题（对应Html的<H1>标签）
## 二级标题（对应Html的<H2>标签）
### 三级标题（对应Html的<H3>标签）
#### 四级标题（对应Html的<H4>标签）
##### 五级标题（对应Html的<H5>标签）
###### 六级标题（对应Html的<H6>标签）
```

### **有序列表** 的语法、渲染效果

```
1. 用带小数点的数字表示有序序列
5. 数字不需要按顺序写
   5. 缩进两格以上就可作为二级列表
      5. 再次缩进就可以作为三级列表
      3. 三级序列同样不要求数字按顺序写
   1. 这一行是第一次缩进，所以是二级列表
4. 这一行没有缩进，所以是一级序列
```

1. 用带小数点的数字表示有序序列
5. 数字不需要按顺序写
   5. 缩进两格以上就可作为二级列表
      5. 再次缩进就可以作为三级列表
      3. 三级序列同样不要求数字按顺序写
   1. 这一行是第一次缩进，所以是二级列表
4. 这一行没有缩进，所以是一级序列

### **无序列表** 的语法、渲染效果

```
* 星号表示是无序列表
- 减号也表示是无序列表
  * 第一次缩进表示二级列表
    * 第二次缩进表示三级列表
  - 这一行是第一次缩进，所以属于二级列表
+ 加号也表示无序列表
```

* 星号表示是无序列表
- 减号也表示是无序列表
  * 第一次缩进表示二级列表
    * 第二次缩进表示三级列表
  - 这一行是第一次缩进，所以属于二级列表
+ 加号也表示无序列表

### **引用** 的语法、渲染效果

```
> 这是第一级引用。
> > 这是第二级引用。
>
> 现在回到第一级引用。
```

> 这是第一级引用。
> > 这是第二级引用。
>
> 现在回到第一级引用。

### **代码段** 的语法、渲染效果

    ```
    var name = firekylin;
    var version = 0.15.8;
    ```

```
    var name = firekylin;
    var version = 0.15.8;
```

\` 不是单引号，而是英文输入的情况下按键盘左上角的 `ESC` 键输出来的符号。

### **行内代码** 的语法、渲染效果

行内代码只需要用 \` 引起来即可。

```
通过 `sudo apt update` 可更新 Ubuntu Linux 的软件列表。
```

通过 `sudo apt update` 可更新 Ubuntu Linux 的软件列表。

### **待办事项** 的语法、渲染效果

```
- [x] 晋级万元户
- [] 解决温饱 
```

- [x] 晋级万元户
- [] 解决温饱 

### **字体格式** 的语法、渲染效果

```
**加粗字体**
__加粗字体__
*倾斜字体*
_倾斜字体_
~~删除~~
```

**加粗字体**
__加粗字体__
*倾斜字体*
_倾斜字体_
~~删除~~


### **超链接** 的语法、渲染效果

```
其他疑问，可参考官方 wiki 的 [问题解答]( https://github.com/firekylin/firekylin/wiki/问题解答)。

本文档初稿由 [choicky](https://https://zhoucaiqi.com/) 提供。
```
其他疑问，可参考官方 wiki 的 [问题解答]( https://github.com/firekylin/firekylin/wiki/问题解答)。

本文档初稿由 [choicky](https://https://zhoucaiqi.com/) 提供。

**Comment by xuexb** [comment]
@choicky todo说法得有空格吧?

```markdown
错误
- [x] 晋级万元户
- [] 解决温饱

正确
- [x] 晋级万元户
- [ ] 解决温饱
```

**Comment by lizheming** [comment]
@choicky 感谢，这篇文章不错，可以按照这个稍微改改就成了，感谢！另外 todo 是 Github 特有的，不是 Markdown 的标准语法哈。
