### ISSUE TITLE
升级到 firekylin 0.15.8 后，标签页为空

### ISSUE THREAD

**Issue by xiaojichao** [firekylin/firekylin#331]
之前版本设置了标签后，标签页是自动出现和更新的。

**Comment by xuexb** [comment]
@xiaojichao hi, 提供下链接地址呗, 你是从哪个版本升级到 v0.15.8 呢?

**Comment by lizheming** [comment]
@xuexb 应该是从 0.15.6 在线升级过来的。

**Comment by ddhhz** [comment]
@xuexb 会是 #306 `think.cache` 的原因吗？

**Comment by ddhhz** [comment]
@xiaojichao 应该是自定义主题的原因  #306 把 tag.html 里的 list 改成了 tags。 请见 https://github.com/firekylin/firekylin/pull/306/files

**Comment by ddhhz** [comment]
@xiaojichao 请将你自定义主题内 `tag.html` 里的 `for tag in list` 改为 `for tag in tags`。

**Comment by lizheming** [comment]
@xiaojichao 你在主题管理里切换成 `firekylin` 主题吧。
