### ISSUE TITLE
今天刚搭建的blog。标签也不显示内容

### ISSUE THREAD

**Issue by aalj** [firekylin/firekylin#332]
通过[](https://firekylin.org/release/latest.tar.gz)下载的，没有进行过主题自定义，但是标签也设置没有显示相应的内容。不知道这个属不属于bug   。

**Comment by ringcrl** [comment]
同样遇到了标签不显示内容的问题

**Comment by xuexb** [comment]
@ringcrl @aalj 你们谁方便加下我的QQ, 单聊下 我查一下问题所在~  463004799, 谢谢~

**Comment by ddhhz** [comment]
请尝试删除 /runtime/cache 文件夹内容。

**Comment by xuexb** [comment]
刚跟 @ringcrl  Q上沟通, 他是在线升级后的, 由于之前编辑过主题, 根据 [更新日志-v0.15.7](https://github.com/firekylin/firekylin/blob/master/CHANGELOG.md#0157) 操作即可

> 【重要】使用自定义主题者请将主题内 `tag.html` 中的 `for tag in list` 改为 `for tag in tags`

后续的版本升级也会多关注字段的无diff, 减少升级操作, 感谢 @ringcrl ~

**Comment by xuexb** [comment]
@aalj 你是直接新安装的吗?

**Comment by golmic** [comment]
遇到了同样的问题，今天下载的最新的安装包，没进行任何自定义操作，标签页为空。

**Comment by xuexb** [comment]
说明下哈, 不显示的情况有2种:

1. 之前有自定义过主题 - 请参考 [更新日志-v0.15.7](https://github.com/firekylin/firekylin/blob/master/CHANGELOG.md#0157) 操作即可

> 【重要】使用自定义主题者请将主题内 `tag.html` 中的 `for tag in list` 改为 `for tag in tags`

2. 后台编辑标签后前台没生效 - 这是由于标签做了6小时的缓存, 删除 `runtime/cache` 下的缓存文件即可, 或者等待下次缓存更新. 缓存的问题下版会 **考虑** 优化下:
    1. 编辑文章时删除标签缓存
    1. 标签相关操作时删除标签缓存
