### ISSUE TITLE
后台导入markdown文件失败

### ISSUE THREAD

**Issue by Bocity** [firekylin/firekylin#338]
centos7 + mariadb 下导入markdown失败，mariadb中也不存在记录，但是可以手动添加。

**Comment by lizheming** [comment]
是什么格式的压缩包？压缩包内文章顶层放不要放到文件夹内。

**Comment by Bocity** [comment]
确认是在顶层，而且是tar.gz格式，不过是在win环境下打包的，不知是否与环境有关？一会忙完我去测试一下

**Comment by lizheming** [comment]
唔，如果还不行就发份包给我邮箱吧，i#imnerd.org，谢啦~

**Comment by Bocity** [comment]
..linux tar 打包也失败了。。。给你个测试地址：47.93.227.136:8360   admin 123456789   这是我用的的测试文件。。http://pan.baidu.com/s/1qYLODKK。。

**Comment by lizheming** [comment]
嗯之前修改了一些其它的东西导致出问题了，已经修改，下个版本就能正常了，感谢反馈！

**Comment by shang1101** [comment]
能给个时间点吗？下版本什么时候上？

**Comment by lizheming** [comment]
还得等等，再攒一波更新，大概月中左右吧

**Comment by shang1101** [comment]
恩恩，辛苦了，期待
