### ISSUE TITLE
为什么添加的标签在标签页都不显示呀

### ISSUE THREAD

**Issue by wxfkwx** [firekylin/firekylin#343]
我添加了标签，但是标签页都没有。我看大家的都有呀

**Comment by ddhhz** [comment]
猜测缓存原因 标签做了缓存 添加标签后需要清缓存。如果有网址请贴过来以便确认是这个原因。

**Comment by wxfkwx** [comment]
昨天一直没有，我还专门写了个页面添了几个链接当标签，结果刚才看到有您回复我，我就改回默认标签页了，看了一下又有了~~~~。嘿嘿嘿

**Comment by ddhhz** [comment]
好 请详细写一下你的解决方法方便后来人借鉴 之后就关闭 issue 吧😄

**Comment by wxfkwx** [comment]
然而我也不知道咋解决的，我把便签页改回来就有了😂😂
