### ISSUE TITLE
TypeError: Invalid Version: 5.6.33-0ubuntu0.14.04.1

### ISSUE THREAD

**Issue by wuyanxin** [firekylin/firekylin#348]
![image](https://user-images.githubusercontent.com/2012249/27064165-98e08496-5028-11e7-88db-32d2222bc885.png)

请问一下这个是什么原因？
firekylin不支持mysql5.6吗？
还是我的姿势不对

**Comment by lizheming** [comment]
你装的是仓库版吧？昨天我在改这块的东西，master 分支还不一定能用，你直接按照这个教程装吧 https://github.com/firekylin/firekylin/wiki/%E5%AE%89%E8%A3%85

**Comment by wuyanxin** [comment]
好的。谢谢
