### ISSUE TITLE
markdown文件打包为tar.gz导入不了

### ISSUE THREAD

**Issue by istek** [firekylin/firekylin#350]
页面显示导入成功700篇文章，首页刷新页面没有数据，查了一下数据库，fk_post，没文章。这是怎么回事？

**Comment by istek** [comment]
服务器系统：linux
Node.js版本：4.8.3
V8引擎版本：4.5.103.47
MySQL版本：10.0.31-MariaDB-1~jessie
ThinkJS版本：2.2.19
FireKylin版本：0.15.9

刚才升级到0.15.9试了一下，还是无法导入。

**Comment by lizheming** [comment]
文章要在压缩包根目录下，如确认 0.15.9 无法导入的话可以邮件发下压缩包给我我来测试下看是不是有其他问题。

**Comment by istek** [comment]
好的，我发给你啊。

**Comment by lizheming** [comment]
我本地试了下导入是成功的，可以显示。不过我看你这个内容应该是 hexo 的吧？建议还是用 hexo 的插件导入比较方便一点。

**Comment by istek** [comment]
OK。谢谢了！
