### ISSUE TITLE
markdown导入成功，但是创建时间有问题

### ISSUE THREAD

**Issue by istek** [firekylin/firekylin#352]
version  0.15.9

markdown打包导入成功，刷新缓存后，文章管理也可以打开。

但是，

导入的时间不对啊，全部都是今天，应该是原文的创建时间啊。而且标题，貌似都是slug，这770多篇文章啊，得一篇一篇改不现实啊。

我试试wordpress导出文件，导入FireKylin的效果吧。

**Comment by lizheming** [comment]
Markdown 的文件不做文件的解析啊，标题就是文件名，时间没办法获取就只能是今天额。另外我和你说过了啊… 你的是 hexo 的文章直接用 hexo 的导入方法导入就好了…这样文章的信息是能补全进来的。

**Comment by istek** [comment]
哦。好吧。close吧。

**Comment by lizheming** [comment]
嗯，你试试 hexo 导入先，有什么问题再开 issue ~
