### ISSUE TITLE
markdown表格中的公式无法渲染

### ISSUE THREAD

**Issue by Bocity** [firekylin/firekylin#353]
会变成下面这个样子

算法         | 系数表示法的时间复杂度 | 点值表示法的时间复杂度
------------| ------------------ | ------------------
 `$A(x)+B(x)$` | `$O(n)$`             | `$O(n)$` 
 `$A(x)* B(x)$` | `$O(n^2)$`           |  `$O(n)$`(因为对于`$x_i$`只需计算 `$A(x_i)*B(x_i)$` 但是要求 `$x_i$` 的取值相同（i：0...2n-2）)

目测可能是渲染顺序的原因？

**Comment by jerrybendy** [comment]
OK, I'll handle it.

**Comment by jerrybendy** [comment]
已解决
