### ISSUE TITLE
摘要空格被删

### ISSUE THREAD

**Issue by lizheming** [firekylin/firekylin#365]
![image](https://user-images.githubusercontent.com/424491/27617244-c1af9ba8-5be7-11e7-8693-9bedb96bfa21.png)

[原文](http://www.esesr.net/post/2010-03-04-Virtual%20Hosting%20With%20Proftpd%20And%20MySQL%20(Incl%20Quota)%20On%20Ubuntu%20910.html)

**Comment by jerrybendy** [comment]
#355  中已经修复了这个问题

**Comment by lizheming** [comment]
好，那等发版的时候关掉这个 issue

**Comment by jerrybendy** [comment]
嗯，好的

**Comment by istek** [comment]
这是从我博客发现的问题啊。哈哈。

**Comment by lizheming** [comment]
@istek 你的博客数据是从 hexo 里导入过来的？

**Comment by istek** [comment]
恩。是的。hexo markdown文件。

**Comment by istek** [comment]
因为我尝试用ghost的json导入，但是一直不成功，虽然界面提示成功，但是数据库的表里面是空的。

**Comment by lizheming** [comment]
把你的 json 发我一份吧，我来看看。

**Comment by istek** [comment]
行，我这就发给你。

**Comment by lizheming** [comment]
收到，我待会看看。

**Comment by lizheming** [comment]
我试了是可以的诶…都导入成功了…

**Comment by istek** [comment]
那为什么我这边死活就不行，pages可以导入，posts显示导入成功，然后去数据库的数据表去看，fk_posts就是空的。很奇怪。

**Comment by lizheming** [comment]
pm2 logs 看下控制台是否有报什么错？

**Comment by lizheming** [comment]
@istek 麻烦

-
