### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by istek** [firekylin/firekylin#366]
不知道为什么我首页的那些图标都不显示了，然后按了F12，打开工具，重新刷新一下页面，发现了这个错误。

Failed to decode downloaded font: https://www.esesr.net/theme/firekylin/res/font/iconfont.ttf

我看了一下这个字体的属主，和nginx，pm2都是同一个用户，web。权限644.

**Comment by lizheming** [comment]
我看已经好了，应该还是权限问题吧。
