### ISSUE TITLE
系统安装时数据库导入失败

### ISSUE THREAD

**Issue by Trilliean** [firekylin/firekylin#373]
`Error: ER_BAD_DB_ERROR: Unknown database 'firekylin'`
mysql创建了firekylin数据库之后还是报错。
是要自己添加表吗？如果是，应该添加哪些字段呢？

**Comment by lizheming** [comment]
还是报这个错么？

**Comment by Trilliean** [comment]
是啊

**Comment by lizheming** [comment]
重启下服务试一下？

**Comment by Trilliean** [comment]
试过了

**Comment by lizheming** [comment]
配置截图看一下，MySQL 截图看看？

**Comment by Trilliean** [comment]
已经解决了！谢谢

**Comment by lizheming** [comment]
是什么问题？

**Comment by Trilliean** [comment]
showdatabases检查的时候发现数据库没创建成功orz。粗心大意没发现。

**Comment by lizheming** [comment]
嗯，好的，我们下个版本加一个自动创建数据库。之前有这个功能来着，但是不知道为啥给删掉了。
