### ISSUE TITLE
安装增加自动创建数据库

### ISSUE THREAD

**Issue by lizheming** [firekylin/firekylin#374]
现在安装如果数据库不存在会报错，可以增加数据库不存在时自动创建数据库。

**Comment by lizheming** [comment]
@catchou

**Comment by ddhhz** [comment]
@lizheming Check #19ce8b

**Comment by lizheming** [comment]
哈哈，谢谢 @ddhhz 我说我明明记得有这个功能来着，原来是被我删除了，辛苦你翻 log 了，我回加一下。
