### ISSUE TITLE
怎么定义自定义页面的URL

### ISSUE THREAD

**Issue by epubreader** [firekylin/firekylin#375]
我填了了一个“联系我们”的页面，  我想通过 http://localhost:8360/contact 这样的页面访问， 怎么才能做到？ 为什么其他页面是可以的， 比如http://localhost:8360/about
还有怎么把页面的评论屏蔽掉？
谢谢了

**Comment by lizheming** [comment]
你修改 nginx 的 rewrite 规则去做吧。评论的话在文章编辑里是可以设置是否允许评论的，具体可参考 WiKi https://github.com/firekylin/firekylin/wiki/%E6%96%87%E7%AB%A0#%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6

**Comment by epubreader** [comment]
为什么我的页面上“允许评论“，没有radio这个按钮啊？

**Comment by lizheming** [comment]
是一个复选框
![image](https://user-images.githubusercontent.com/424491/28115952-865d473c-6739-11e7-9a06-69bb8b8f5215.png)

**Comment by epubreader** [comment]
我的页面显示没有“容许评论”那些字， 是不是跟设置有关， 
不知道怎么截图给你看

**Comment by epubreader** [comment]
检查了， 是CSS问题， CSS使它隐藏了， 但我好像没有动CSS

**Comment by lizheming** [comment]
在后台编辑页面那块肯定是有的…

**Comment by lizheming** [comment]
那你看看是哪个样式影响的，如果是我们程序的样式提交一个 PR 修复一下吧，谢谢。

**Comment by epubreader** [comment]
.fk-content-wrap input[type=radio], .fk-content-wrap input[type=checkbox] {
    margin-right: 5px;
    margin-left: -18px;
}

把margin-left: -18px; 改成margin-left: 0; 就行了

**Comment by ddhhz** [comment]
@STayinloves #354 

https://github.com/firekylin/firekylin/pull/354/files#diff-ad38717f0f548998d7bf98958c345868L161

**Comment by lizheming** [comment]
感谢 @ddhhz 找到了原因，我还在纳闷怎么突然多了这个呢😂
