### ISSUE TITLE
建议增加文章缩略图功能

### ISSUE THREAD

**Issue by epubreader** [firekylin/firekylin#388]
能不能帮忙添加一下这个功能？
1. 创建文章时，可以选一张图片，当主图片。
2. 在文章列表页面， 显示缩略图， 
点击缩略图能看到文章。

类似于今日头条这个页面的文章图片：
http://www.toutiao.com/

谢谢。

**Comment by wahmaths** [comment]
请问有没有文章的多媒体附件管理啊？图片多了，简单的rar文件基本的管理也希望加入。THX

**Comment by lizheming** [comment]
@wahmaths 这个在后期的规划里了，可以看 <https://github.com/firekylin/firekylin/projects/2> 不过可能会比较靠后再支持。目前的话建议你先用其它的存储服务解决，毕竟我们是支持七牛又拍的。

**Comment by ddhhz** [comment]
1. is done in #390. 
2. will be done in other themes.
