### ISSUE TITLE
搞不清楚我的static/js/

### ISSUE THREAD

**Issue by baitongda** [firekylin/firekylin#391]
我装完了。但少了这个目录下地文件！

**Comment by baitongda** [comment]
home.js common.js page.js post.js admin.js

**Comment by lizheming** [comment]
从仓库克隆的请使用仓库版安装方法，具体见
 WIKI: https://github.com/firekylin/firekylin/wiki/%E4%BB%93%E5%BA%93%E7%89%88%E5%AE%89%E8%A3%85

**Comment by gitshan** [comment]
同样的问题，npm run webpack后就有了，谢谢@lizheming
