### ISSUE TITLE
内容编辑区域适配

### ISSUE THREAD

**Issue by HJDev** [firekylin/firekylin#395]
- [x] **#396.** 希望可以将`文章编辑`、`页面编辑`和`主题编辑`的编辑窗口，根据页面的大小，显示到底部，现在在我的显示器上，默认都只显示到一半，下面部分都被留白了，编辑内容的时候显示有点局限，只有文章编辑可以拖动窗口大小，其他都不能拖动窗口大小。
PS : 可以参考 ghost 的后台设计
<img width="2318" alt="wx20170727-115125 2x" src="https://user-images.githubusercontent.com/18192386/28653769-04faa0ce-72c2-11e7-8b78-001f4ea92646.png">

- [x] 文章没有编辑摘要区域，在主题里只输出了`...`作为摘要。
- [x] **Added in #390.** 文章没有缩略图，如果可以单独添加缩略图就更好了。

**Comment by ddhhz** [comment]
![image](https://user-images.githubusercontent.com/5880908/28670861-934008de-72a8-11e7-9768-85ee7d6a77c3.png)

按这个按钮或手动添加 `<!--more-->`，这一行上方的内容为摘要。
