### ISSUE TITLE
更新FireKylin 0.15.12后，标签页空白？

### ISSUE THREAD

**Issue by BeAce** [firekylin/firekylin#398]
更新*FireKylin 0.15.12*后，标签页空白，浏览器没有任何error

![image](https://user-images.githubusercontent.com/13284978/28755433-699f91ba-758d-11e7-9316-2eb89c8c1e23.png)

**Comment by ddhhz** [comment]
请问你在使用 firekylin_new 主题吗还是默认主题？需要把 [https://www.beacelee.com/theme/firekylin_new/tag.html](view-source:https://www.beacelee.com/theme/firekylin_new/tag.html) 里的 `for tag in list` 改成 `for tag in tags` 

See #331

**Comment by BeAce** [comment]
@ddhhz 感谢回复！我使用的是 * firekylin_new* 主题，已经好了。
