### ISSUE TITLE
建议开启自定义伪静态

### ISSUE THREAD

**Issue by bayunjiang** [firekylin/firekylin#399]
原先的博客链接都没有.html后缀，希望能够支持自定义删除html，那样就可以平滑迁移过来了。

**Comment by lizheming** [comment]
https://75team.com/post/svg-animation-in-action 去除`.html`后缀目前这种路由也是支持的~

**Comment by bayunjiang** [comment]
奇舞是直接修改的路由代码么？
自己改路由的确可以实现，不过最好还是能够直接在后台通过设置修改，不然每次更新版本都得改一次。

**Comment by lizheming** [comment]
不是修改代码的。我的意思是你的老代码里如果是无 `.html` 的路由格式的话目前也是能正常使用的，钱以后的话就全部使用 `.html` 的路由格式就好啦~

**Comment by bayunjiang** [comment]
原来 `.html` 是摆设啊~~~

**Comment by lizheming** [comment]
😄 也差不多吧~ 其实给动态页面增加 `.html` 后缀算是早期伪静态优化的一种方式了。

**Comment by bayunjiang** [comment]
那头回头可以移植现在的主题了

**Comment by lizheming** [comment]
欢迎~ 主题开发可以参考 https://github.com/firekylin/firekylin/wiki/%E4%B8%BB%E9%A2%98%E5%BC%80%E5%8F%91 这篇 WIKI，当然还比较简陋了~ 如果有什么不满足的需求可以再在 issue 中提出来~谢谢~

**Comment by lizheming** [comment]
@bayunjiang 啊！看了下你的 Github！之前我还考虑过要移植你的那个 Typecho 主题呢！没想到作者来了！荣幸之至！

**Comment by bayunjiang** [comment]
其实我是移植修改的别人的，最早的版本是ghost的，然后我移植到typecho加了一些功能。

**Comment by lizheming** [comment]
啊，没事没事，移植也有移植的功劳呀，何况你还二次开发了~

**Comment by lizheming** [comment]
我先把这个 issue 关闭了，如果你主题开发还有什么问题的话可以新开 issue 再讨论，谢谢！
