### ISSUE TITLE
$code.forEach is undefined in firekylin.js

### ISSUE THREAD

**Issue by lnxbh** [firekylin/firekylin#401]
在文章查看页面，js脚本会有问题，提示$code.forEach is undefined,
我是在js的头部加入
` if(!NodeList.prototype.forEach){
    console.log('新增forEach方法')
     NodeList.prototype.forEach=function(callback){
                [].slice.call(this).forEach(callback);
        };
     }`
解决的
具体查看原文 [原文链接](http://blog.betweenfriends.cn/post/codeForEachUndefinedFirekylin.html)

**Comment by xuexb** [comment]
好的, 多谢, 我处理下~
