### ISSUE TITLE
tags标签页面不显示数据

### ISSUE THREAD

**Issue by lnxbh** [firekylin/firekylin#403]
已经有添加标签数据，系统其他部分部署也都正常，
但是标签页面就是空白的，也没有报错，后台没有
改动过，比较奇怪
https://blog.betweenfriends.cn/tags

**Comment by ddhhz** [comment]
已经好了？

**Comment by lnxbh** [comment]
好了，也不知道是哪里问题，好像什么都没改就出来了？

**Comment by cuitianze** [comment]
@lnxbh 缓存问题。
@ddhhz 那么问题来了，这样的缓存机制合理吗？

**Comment by lizheming** [comment]
@cuitianze 不合理，欢迎提 pr 去了 :smile:
