### ISSUE TITLE
文章不可以上传封面图么？

### ISSUE THREAD

**Issue by AspenLuoQiang** [firekylin/firekylin#404]
![image](https://user-images.githubusercontent.com/12598256/28819609-60e81e02-76e1-11e7-9c67-c1c2d6f47427.png)

**Comment by lizheming** [comment]
目前先简单的加了一下，直接输入图片地址吧，如果要上传可以在左侧文章区域上传了再粘过来。后期会加上上传等逻辑的，现在先简单的支持下。
