### ISSUE TITLE
index.html 页面遍历文章时标签问题

### ISSUE THREAD

**Issue by bayunjiang** [firekylin/firekylin#407]
`index.html` 页面遍历文章时是否支持遍历每篇文章的标签和分类。

**Comment by lizheming** [comment]
好像不支持 @ddhhz 抽空加一下吧，辛苦。

**Comment by bayunjiang** [comment]
好的，谢谢。

**Comment by lizheming** [comment]
已支持，post 数据里会有 `cate` 和 `tag` 字段，可以自行遍历。

**Comment by alvendarthy** [comment]
貌似并没有支持，在index.html中

**Comment by lizheming** [comment]
@alvendarthy 有的，在 `{{post.cate}}` 和 `{{post.tag}}` 中。

**Comment by alvendarthy** [comment]
2.1.4 releas 试了下，应该是不支持。

**Comment by lizheming** [comment]
@alvendarthy 用错项目了？我们最新的是 1.2.5 额....还没发过 2 的版本...

**Comment by alvendarthy** [comment]
手误写错了，1.2.4 release。

**Comment by lizheming** [comment]
你把你的文章 URL 后缀从 `.html` 改成 `.json` 可以看到所有注入到当前页面的数据，比如 https://75team.com/post/75cdn-es-module.json 这个，可以看到 `post.cate` 和 `post.tag` 都是有的。

**Comment by alvendarthy** [comment]
嗯，我一直在找 Home page 的注入情况，大概如此 https://75team.com/post/list/index.json，需要遍历 {{categories}} 获的 post 的 cate 情况。
 post.cate 和 post.tag 应该只在 post template 注入了，index page 没有直接支持。
