### ISSUE TITLE
文章管理能否添加管理员“选择作者”发布文章的功能？

### ISSUE THREAD

**Issue by HenryKamg** [firekylin/firekylin#408]
如题，希望可以添加feature，管理员审核修改文章后可以选择“作者”并发布文章。

**Comment by epubreader** [comment]
最好就变成多用户的博客系统， 让用户自己发帖然后管理员审核

**Comment by lizheming** [comment]
@epubreader 现在就是这样的逻辑的，普通用户有发文权限，管理员审核通过后会出现在首页。只是 issue 主他们的文章都是由他带为发的，所以会有这个需求。
