### ISSUE TITLE
封面图调用字段

### ISSUE THREAD

**Issue by bayunjiang** [firekylin/firekylin#412]
在 `post` 和 `page` 调用封面图的字段叫做什么，默认主题里面没有找到。

**Comment by ddhhz** [comment]
https://github.com/firekylin/firekylin/pull/390/files#diff-ddbcd6053fdc956767317c4f64cc04b7R95

**Comment by bayunjiang** [comment]
抱歉忘记看 commits 了

**Comment by ddhhz** [comment]
np! 默认主题里暂时还没添加这个。
