### ISSUE TITLE
文章链接500

### ISSUE THREAD

**Issue by cnTomato** [firekylin/firekylin#416]
博客正常，文章链接打开是500 <https://blog.steps.info>

**Comment by lizheming** [comment]
麻烦上机器执行下  `pm2 logs` 看下有什么报错

**Comment by cnTomato** [comment]
![image](https://user-images.githubusercontent.com/12791216/29492255-7ade7196-85a8-11e7-93e9-0d732b057390.png)

**Comment by lizheming** [comment]
你重新保存下文章看下正常否？

**Comment by cnTomato** [comment]
@lizheming 可以了，这是？

**Comment by lizheming** [comment]
新加了一个字段的问题，这个问题已经修复了，会在下个版本发布。目前你可以先手动重新保存手工修复一下。

**Comment by cnTomato** [comment]
@lizheming 好的  thx
