### ISSUE TITLE
博客更新后tags页面不显示bug解决

### ISSUE THREAD

**Issue by haodalong** [firekylin/firekylin#417]
博客更新到v0.15.12后，点击标签页，标签无法显示，如下图所示
![image](https://user-images.githubusercontent.com/13931187/29992939-7c06cab4-8fda-11e7-8191-fb80f9e1e9dd.png)
经过排查，发现，tag.html页面的代码
```
      {% for tag in list %}
      <a href="/tag/{{tag.name}}" data-tag="{{tag.name}}">{{tag.name}}({{tag.count}})</a>
      {% endfor %}
```
应为
```
      {% for tag in tags %}
      <a href="/tag/{{tag.pathname}}" data-tag="{{tag.name}}">{{tag.name}}({{tag.count}})</a>
      {% endfor %}
```
如下图
![image](https://user-images.githubusercontent.com/13931187/29992926-1e80e2bc-8fda-11e7-8e5a-8208f2937146.png)
![image](https://user-images.githubusercontent.com/13931187/29992984-c05018be-8fdb-11e7-9fd5-2cde2a8f9cc0.png)
 更改完后，页面标签即可正常显示，如下图：
![image](https://user-images.githubusercontent.com/13931187/29992936-4c4bc5b8-8fda-11e7-80f1-6faf4667720d.png)
![image](https://user-images.githubusercontent.com/13931187/29992987-cc534898-8fdb-11e7-8452-a926143acda0.png)

**Comment by lizheming** [comment]
嗯，应该是 0.15.7 版本把 list 变量修改成 tags 了，自定义主题模板的需要更新下，新下载的或者使用默认主题的没有这个问题。
