### ISSUE TITLE
有关仓库版部署和主题优化的说明

### ISSUE THREAD

**Issue by yugasun** [firekylin/firekylin#420]
### 仓库版部署

    安装以上步骤完成后，项目前端界面还是实时编译运行的，如果想要部署到服务器，需要进行一下步骤：
    
    - 编译输出静态文件： `npm run webpack.build.production`，解决很多朋友拉取git代码到本地后，部署会发现后台没法进入问题，就是缺少这一步，相关issue: https://github.com/firekylin/firekylin/issues/39，https://github.com/firekylin/firekylin/issues/325,
    - 添加mysql配置：在 `src/common/config/` 目录下添加 `db.js`:

      ```js
        export default {
            type: 'mysql', //数据库类型
            log_sql: true, //是否记录 sql 语句
            log_connect: true, // 是否记录连接数据库的信息
            adapter: {
                mysql: {
                    host: '127.0.0.1', //数据库 host
                    port: '3306', //端口
                    database: 'firekylin', //数据库名称
                    user: 'root', //账号
                    password: '', //密码
                    prefix: 'fk_', //数据表前缀
                    encoding: 'utf8', //数据库编码
                    nums_per_page: 10, //一页默认条数
                }
            }
        }
      ```

    - 修改 `pm2.json` 文件中的 `cwd` 字段值为你的项目目录。
    - pm2后台启动node服务：`pm2 startOrReload pm2.json`
    - nginx配置，请参考[安装包安装](https://github.com/75team/firekylin/wiki/安装)

### 主题优化
   
   无论你是[安装包安装](https://github.com/75team/firekylin/wiki/安装)还是[仓库版安装](https://github.com/75team/firekylin/wiki/仓库版安装)，主题代码都是没有优化的，所以会发现访问博客地址的时候，会加载很多css文件，这里分享下个人优化主题的步骤，方便前端小白的朋友：

   1. 仓库版安装方式：
        
        对于仓库版安装，项目根目录下直接有个 `stc.view.config.js` 的文件就是用来编译主题文件的，直接运行：
        ```bash
        node stc.view.config.js
        ```
        之后根目录下会生成 `output.theme` 文件夹，将 `output.theme/www/theme/firekylin/` 目录下的 `res` 文件夹替换项目根目录下的 `www/theme/firekylin/` 目录下 `res` 文件夹即可。有关讨论issue, 参考 https://github.com/firekylin/firekylin/issues/392

    2. 安装包安装方式：

       对于安装包安装，需要在根目录创建 `stc.view.config.js`，[源码](https://github.com/firekylin/firekylin/blob/master/stc.view.config.js)，然后步骤同上。

PS: 由于本人没有修改wiki权限，所以在这里提了issue，希望能帮助到大家。

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin-docs 之前考虑到了这个问题，所以我把文档放到了另外一个仓库地址了，能帮忙在这修改一下提下 PR 么，谢谢了~

**Comment by yugasun** [comment]
@lizheming 已经提交PR到 [firekylin-docs](https://github.com/firekylin/firekylin-docs)仓库

**Comment by lizheming** [comment]
已经 merge 并更新，感谢~

**Comment by yugasun** [comment]
@lizheming 举手之劳~
