### ISSUE TITLE
在后台更新到最新版本后懒加载的图片出不来？

### ISSUE THREAD

**Issue by henryzp** [firekylin/firekylin#425]
看一下html最终代码，占位图并没有替换掉啊

是不是有js未更新提交？

还是什么原因？

**Comment by xuexb** [comment]
偶遇小翼啊, 你看下有没有报错~ 有链接吗?

**Comment by henryzp** [comment]
@xuexb ，没有报错，我发你链接：http://www.my-fe.pub/post/module-note.html

**Comment by ddhhz** [comment]
目测可以加载 @FL

**Comment by xuexb** [comment]
我看这里的图片可以正常加载啊, 我是 chrome 61.0.3163.79, 你的是什么浏览器? @henryzp

**Comment by lizheming** [comment]
@ddhhz @xuexb 部分图没加载出来，“运行效果：”后有一张截图。

**Comment by ddhhz** [comment]
hmm 运行效果后一张截图也有成功加载。我再测测看。

**Comment by xuexb** [comment]
![image](https://user-images.githubusercontent.com/3872051/30464270-38d52018-9996-11e7-8f77-84bd0f87ce8d.png)

如果真有加载不出的情况, 应该属于兼容问题了.

**Comment by henryzp** [comment]
@xuexb 61.0.3163.91,

效果是这样的：

![image](https://user-images.githubusercontent.com/3849702/30464338-a1c06ace-9996-11e7-8af6-e80837104a28.png)

**Comment by ddhhz** [comment]
Update: Firefox on OSX small height ~400px 可以复现。

**Comment by ddhhz** [comment]
document.body.scrollTop is always 0 in Chrome 61. Working on a fix...

**Comment by lizheming** [comment]
要用 `document.scrollingElement || document.body` 兼容一下。

**Comment by henryzp** [comment]
@lizheming ，啥时候后台能提示更新？

**Comment by lizheming** [comment]
先按照 #426 后台模板管理手动修改下吧，短时间内还不会发版。
