### ISSUE TITLE
请问安装好博客之后，如何再次进入安装的网页呢

### ISSUE THREAD

**Issue by zhenfeng-zhu** [firekylin/firekylin#430]
![default](https://user-images.githubusercontent.com/6822558/30914761-4ab2f52c-a3c7-11e7-8dc2-5f89bfec1300.png)
想重新进入这个页面，安装一下，求指教。

我输入了127.0.0.1:8360/index/install  进入不了

**Comment by ddhhz** [comment]
删除 firekylin 目录下的 `.installed` 试试。

**Comment by ddhhz** [comment]
Closed due to inactivity.
