### ISSUE TITLE
仓库版部署管理页不显示，console报错如图

### ISSUE THREAD

**Issue by codefinger23** [firekylin/firekylin#432]
![image](https://user-images.githubusercontent.com/12182066/31434722-c871edd0-ae42-11e7-8909-fbc775405113.png)
猜测的原因:

- 与正在使用的博客共用数据库，导致账号系统混乱（至少应该让我能登录）

尝试解决办法：

- npm run webpack.build.production ： 没有任何效果

- npm run webpack：没有效果

- npm start：服务正常启动，没有报错

目前状态：
博客页面正常使用，后台无法进入。能够正常共享数据库数据，因为界面显示不出来，所以没试过账号数据，文章数据是正常的。

**Comment by ddhhz** [comment]
开发部署用 `npm run webpack` 截图看一下 terminal

**Comment by shadofight** [comment]
![image](https://user-images.githubusercontent.com/12182066/31710716-74f5d38c-b3bb-11e7-915f-c67ad0a4ddd6.png)

有两个警告。博客界面正常进入，就是后台界面不显示
这次的报错
![image](https://user-images.githubusercontent.com/12182066/31710846-d48b3a76-b3bb-11e7-8417-58b7cf5e4dc1.png)

**Comment by sleagon** [comment]
同样的bug

**Comment by lizheming** [comment]
看下 #436 这个 issue 看一下是不是同一个问题？

**Comment by summerwang0915** [comment]
@lizheming 看上去不是同一个问题，后台界面不显示这个问题依然存在

**Comment by lizheming** [comment]
应该和 #497 是一个问题，还有问题的清一下浏览器缓存试一下

**Comment by lizheming** [comment]
无回复先关闭此问题
