### ISSUE TITLE
求解决 XSS 攻击

### ISSUE THREAD

**Issue by shadofight** [firekylin/firekylin#433]
在写博文的时候写了<script>标签，网站内容无法展示，明显是被XSS，这个问题希望尽快解决。
![image](https://user-images.githubusercontent.com/12182066/31559468-5b3564c4-b016-11e7-94dd-3421796d411b.png)
![image](https://user-images.githubusercontent.com/12182066/31559476-61f81bb2-b016-11e7-9642-dbc2877a8ad0.png)

**Comment by ddhhz** [comment]
我觉得是个 wontfix，因为这是个 Self-inflicted xss attack 额。我在关于页面上就有需求需要添加 script tag。

![image](https://user-images.githubusercontent.com/5880908/31560667-34260df4-b023-11e7-8714-32156466c6e4.png)

**Comment by lizheming** [comment]
有很多用户是有在内容中输入 HTML 的需求的，用户自己输入的内容用户自己去保证自己的安全性即可，如果要不解析标签请使用代码块包括代码。
