### ISSUE TITLE
后台一片空白

### ISSUE THREAD

**Issue by SenLief** [firekylin/firekylin#434]
/admin后不显示后台，一个空白页是什么原因？

**Comment by lizheming** [comment]
怎么安装的？

**Comment by SenLief** [comment]
VPS上安装的，首页可以打开。但是后台打不开。

**Comment by lizheming** [comment]
怎么安装的？是 clone 的仓库还是下载的包？

**Comment by SenLief** [comment]
下载的包，在官网下载的那个

**Comment by lizheming** [comment]
博客地址给一下

**Comment by SenLief** [comment]
www.senlief.com

**Comment by lizheming** [comment]
http://www.senlief.com/static/module/bootstrap/css/bootstrap.min.css?v=9696a 静态资源全部 403 了，看下文件夹权限对不对。

**Comment by SenLief** [comment]
基本上都是644啊

**Comment by SenLief** [comment]
可以了，nginx配置出错了，多谢！

**Comment by lichunshan** [comment]
我要遇到了静态资源403的问题，请问您是怎么解决的？

**Comment by lizheming** [comment]
@lichunshan 手机上码字搜索不太方便，你直接在 issue 里搜 403 应该挺多回答的，这个是 nginx 配置的问题。
