### ISSUE TITLE
后台页面打不开， 执行npm run webpack.build.production 报错

### ISSUE THREAD

**Issue by summerwang0915** [firekylin/firekylin#436]
![image](https://user-images.githubusercontent.com/13192952/32097674-ee2c99d2-bacf-11e7-88db-61e4412a4747.png)
![image](https://user-images.githubusercontent.com/13192952/32097737-1d1ff36a-bad0-11e7-83af-245b818395ac.png)

**Comment by summerwang0915** [comment]
这个问题没人解决吗？

**Comment by sorkindeng** [comment]
遇到同样的问题。

**Comment by lizheming** [comment]
是 `qrcode-react` 这个依赖小版本升级了个不兼容内容，已修复，各位更新后删除 node_modules 重新安装依赖即可。

**Comment by ChaoHui123** [comment]
![image](https://user-images.githubusercontent.com/17821872/41927065-abb51dca-79a3-11e8-9040-37a7e422465a.png)
![image](https://user-images.githubusercontent.com/17821872/41927123-dc25dd00-79a3-11e8-9601-f58c7ab576c9.png)

cnpm@6.0.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.1.0 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@10.5.0 (/usr/lib/nodejs/bin/node)
npminstall@3.6.2 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/lib/nodejs
linux x64 4.4.0-43-Microsoft
registry=https://registry.npm.taobao.org

安装包地址:https://github.com/firekylin/firekylin/archive/1.1.0.zip
启动方式:  sudo node production.js
我也出现了和他类似的问题
