### ISSUE TITLE
从文章阅读里点击文章分类标签时跳404

### ISSUE THREAD

**Issue by healthymap** [firekylin/firekylin#437]
在阅读文章
https://blog.betweenfriends.cn/post/howtoimportmultilintextintoeclipse.html
时，点击 添加在分类 备忘录 下 ，，
调到 
https://blog.betweenfriends.cn/cate/%E5%A4%87%E5%BF%98
404

**Comment by xuexb** [comment]
hi @lnxbh ，刚看了下，访问不了。你的 firekylin 是哪个版本呢？

**Comment by lizheming** [comment]
@xuexb 是中文 cate 的问题

中文分类的话尽量给一下纯英文的缩略名吧，现在中文分类应该是有点问题的。

**Comment by lizheming** [comment]
已增加中文分类的兼容，请等下个版本的更新
