### ISSUE TITLE
tags 不显示啊

### ISSUE THREAD

**Issue by wchb2015** [firekylin/firekylin#439]
新建了 标签 但 /tags 下面没

**Comment by wchb2015** [comment]
老哥 tag 改了简写 就404了, 然后 新建的tag即时绑了文章也不显示,这块有问题呀

**Comment by ddhhz** [comment]
看一下 #332. 这个还有待优化  欢迎 PR

**Comment by haodalong** [comment]
博客更新后tags标签页面不显示bug解决 #417 ，除了tags和list要改，还需要改下面一句的pathname

**Comment by qfdk** [comment]
@haodalong 还是没有解决,用的最新的版本,主题的没有问题,tag.html 里面也没有问题.就是不显示...

**Comment by ddhhz** [comment]
@qfdk 啥不显示？http://blog.qfdk.me/tags http://blog.qfdk.me/tag/nodejs 都可以吖

**Comment by qfdk** [comment]
@ddhhz 知道怎么回事儿了. 要删除 `rm -rf runtime/cache/` 这里的缓存的问题.

**Comment by ddhhz** [comment]
好 谢谢  我之后有空优化修复一下这个问题。

**Comment by lizheming** [comment]
0.15.16 暂时先把 tag 缓存去掉了，应该没问题了。
