### ISSUE TITLE
新手普通安装时出了点问题

### ISSUE THREAD

**Issue by wenlittleoil** [firekylin/firekylin#441]
将该文件软链到 nginx 的配置目录下能写具体点吗

**Comment by ddhhz** [comment]
根据你 nginx 安装配置目录的不同，后部分要对应：

在 firekylin 目录下运行
```
sudo ln -s nginx.conf <nginx配置目录>/域名.conf
```

请问是哪个部分卡住了？还有问题话请详细说明。或者前往 [gitter](https://gitter.im/firekylin/firekylin) 交流。

**Comment by Vove7** [comment]
sudo ln -s /firekylin/firekylin/nginx.conf /etc/nginx/sites-enabled/firekylin
前面是完整目录

**Comment by ddhhz** [comment]
Close due to inactivity.
