### ISSUE TITLE
懒加载图片有时候出不来

### ISSUE THREAD

**Issue by zxysilent** [firekylin/firekylin#442]
![image](https://user-images.githubusercontent.com/19162822/32696260-9897aa5c-c7ae-11e7-8208-2276e7f10cc2.png)

[地址](https://blog.zxysilent.com/about)

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/commit/09226ac7524848c869e1aa3cbefa8fcc4c8bf4b8 按照这个 commit 修改一下主题的 `firekylin.js` 文件试试。

**Comment by zxysilent** [comment]
ok了  感谢
