### ISSUE TITLE
启用toc会导致lazy-load失效

### ISSUE THREAD

**Issue by huzunjie** [firekylin/firekylin#445]
FireKylin版本：0.15.13  [Releases包](https://github.com/firekylin/firekylin/releases/download/0.15.13/firekylin_0.15.13.tar.gz) 代码有问题。

同一篇文章内容，分别发了两篇：

_启用toc的: http://blog.pyzy.net/post/test-toc.html_ （已删除）
未启用toc的：http://blog.pyzy.net/post/chimee-preface.html （已改为启用toc）

**Comment by ddhhz** [comment]
你的代码和主分支分离了。请把你文件夹下这个文件覆盖一下看看能不能修复这个问题：https://github.com/firekylin/firekylin/blob/master/www/theme/firekylin/res/js/firekylin.js

**Comment by huzunjie** [comment]
我是直接wget https://github.com/firekylin/firekylin/releases/download/0.15.13/firekylin_0.15.13.tar.gz 安装的，这个包里的代码是坏掉的？

**Comment by ddhhz** [comment]
@lizheming  看了一下 `www/theme/firekylin/res/js/firekylin.js` 确实不是最新版

**Comment by lizheming** [comment]
@ddhhz 上一次发版挺久之前了，当时太着急了依稀记得那一次的 tag 打的时机好像有问题…好像发版比打 tag 要早一两个 commit。如果是 scrolltop 这个问题的话我再发一版吧，忧桑。

**Comment by lizheming** [comment]
@ddhhz 我重新更新了下 0.15.13 的代码，二位看下还有没有问题，我这边看是正常的了。

**Comment by ddhhz** [comment]
@lizheming 看了一下 0.15.13 Github Release 和 latest 的 tarball 里都没有改过来诶。你在哪改了？

**Comment by lizheming** [comment]
@ddhhz release 忘记上传了，我重新补一下。https://firekylin.org/release/latest.tar.gz 我是重新上传了的，我也验证了和 tag 是一样的。https://firekylin.org/release 这里可以看到更新时间。

**Comment by ddhhz** [comment]
喔喔 看了下 latest.tar.gz 对的。我之前应该是看错了。Downloads 里太多 firekylin 文件夹了😄。

**Comment by lizheming** [comment]
嗯，好的，辛苦了。这个 issue 由于问题已解决，我先关闭。
另外我开了一个新的 issue #446 来解决可能由于我本地有修改没发布导致的发版问题。
