### ISSUE TITLE
谷歌浏览器不显示文章图片,别的浏览器可以

### ISSUE THREAD

**Issue by lxjcxj** [firekylin/firekylin#448]
![98777](https://user-images.githubusercontent.com/5517710/33355181-5d338418-d4f1-11e7-9f67-5f58a3113038.png)

**Comment by xuexb** [comment]
看下 https://github.com/firekylin/firekylin/issues/442 这个可以解决不。

**Comment by lizheming** [comment]
@xuexb 本周我发一版吧，解决下这个问题。

**Comment by lxjcxj** [comment]
按照 #442 没有解决，主题一个是原始的一个是拷贝的都改了。
谷歌浏览器版本是 版本 63.0.3236.0（正式版本） （32 位）
可能是图片多？一共有8张配图，图片少的就可以正常显示。
8张图不显示 https://blog.hijs.cc/post/CodeSniffer.html
3张图显示     https://blog.hijs.cc/post/docker-slim.html

**Comment by ddhhz** [comment]
@lxjcxj 你好 看了一下你的还没有改：
![image](https://user-images.githubusercontent.com/5880908/33563743-bc4dc550-d8e6-11e7-8cfd-6d0c531d5da1.png)

请按照如下修改：
09226ac

**Comment by lxjcxj** [comment]
@ddhhz 改好了，是我用nginx做的反向代理，估计缓存有点严重。
我在layout.html 113行加了个版本号
<script src="/theme/firekylin/res/js/firekylin.js?v=1" data-ls="js_firekylin"></script>
现在没有问题了,THANKS.

**Comment by lizheming** [comment]
0.15.14 已经释出：https://github.com/firekylin/firekylin/releases/tag/0.15.14
