### ISSUE TITLE
如何将firekylin放在二级域名下

### ISSUE THREAD

**Issue by huangssssx** [firekylin/firekylin#451]
我有个主域名xxxx.com这个放了我的主网站，我希望能在xxxx.com/doc/下放置我的blog，请问如何做可以实现？

**Comment by ddhhz** [comment]
这个是个 nginx 配置问题  Something like 

location /docs {

}

Will do

**Comment by huangssssx** [comment]
nginx只能配置blog的访问地址，但是对于blog内部的链接地址就没有办法，比如登陆后台的超链接就是：xxxx/post/hello-world-via-firekylin.html#toc-1ab 而非 xxxx/doc/post/hello-world-via-firekylin.html#toc-1ab

**Comment by ddhhz** [comment]
nginx 中使用 location 和 proxy_pass 和 rewrite module 可以实现你要的效果。

p.s. 你最新的回复和你之前的 issue 里的问题不一样。如果还有其他疑问，请写清楚具体需要实现的效果并贴出你尝试的 nginx 配置。这样我们比较好帮助你。：）

**Comment by ddhhz** [comment]
明白了，您的意思是子目录下，二级域名是 doc.xxxx.com 这样的。
