### ISSUE TITLE
子目录下网站内链问题

### ISSUE THREAD

**Issue by huangssssx** [firekylin/firekylin#452]
如果通过nginx将firekylin配置在xxx.com/doc子域名下,blog内部的链接地址却没有办法修改，比如登陆后台的超链接就是：xxx.com/post/hello-world-via-firekylin.html#toc-1ab 而非 xxx.com/doc/post/hello-world-via-firekylin.html#toc-1ab

**Comment by ddhhz** [comment]
请尝试使用 nginx 的 sub_filter / subs_filter 

将 `href="/` 替换为 `href="/doc/` 即可。

**Comment by ddhhz** [comment]
有进展吗

**Comment by ddhhz** [comment]
先关了，有问题请回复。

**Comment by huangssssx** [comment]
不好意思，这几天没看见，仍然有问题，我们的运维表示这种配置对子目录不友好，不予配合。
说实在的，当一个功能涉及到多人配合时成功的几率就会几何级数下降，产品的实用性就会降低，所以我只能放弃firekylin选择其他方式。

**Comment by ddhhz** [comment]
感谢您给 firekylin 一试。：）新快！

**Comment by FrancisKong** [comment]
我也是同样的需求，但是遇到了个问题，就是 `/admin` 页面能够加载，但是页面中的静态资源返回了 404。

这是我的 Nginx 配置：

```
location /blog/ {
                root /www/Blog/output;
                proxy_http_version 1.1;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Accept-Encoding "";
                proxy_pass http://127.0.0.1:8360/;
                proxy_redirect off;
                sub_filter 'href="/' 'href="/blog/';
                sub_filter 'url(/' 'url(/blog/';
                sub_filter_once off;
}
```

**Comment by ddhhz** [comment]
@FrancisKong `url('/` 替换为 `url('/blog/` 这条您没有加。可能要 escape 一下 `sub_filter 'url(\'/' 'url(\'/blog/';`

还有就是可否贴出网址或错误截图和404文件的路径？

**Comment by FrancisKong** [comment]
感谢您的回复，经过调试后发现是因为 Nginx 中有下面的配置，导致 `location /blog/` 规则没有被采用，所以里面的 `root` 字段没生效，导致的404 错误

```
location ~ .*\.(js|css)?$
{
           expires 15d;
}
```

在修复这个问题后，静态资源能够正常加载了，但页面还是没有渲染出来，控制台也没看到任何报错，网址是：https://www.n2boost.com/blog/admin/dashboard

**Comment by ddhhz** [comment]
@FrancisKong 我晚点看一下哈

**Comment by ddhhz** [comment]
@FrancisKong 因为后台用了 React，react-router 配置文件里默认路径是 `/admin` 所以需要更新为 `/blog/admin`。正好也有很多api请求是 `/admin` 下面的。

所以只要再加一条 sub_filter 即可：
```
sub_filter '"/admin' '"/blog/admin'
```

如果还有其他问题请回复。

p.s. 目前这个项目设计时没有考虑子目录的方式。之后可以考虑添加这个需求。还有就是为啥不用 https://blog.n2boost.com ? 证书原因？

**Comment by FrancisKong** [comment]
@ddhhz 问题解决了，非常感谢！

没有使用子域名确实是因为证书原因，本以为使用子目录的方式会方便一点，没想到还是有些麻烦。

**Comment by zhoushuozh** [comment]
@ddhhz 遇到了同样的问题，已添加`sub_filter`，仍存在问题。

下面是我的`nginx`配置
```
location /blog/ {
        root /home/ubuntu/www/firekylin/www;

        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Accept-Encoding "";
        proxy_pass http://127.0.0.1:8360/;
        proxy_redirect off;

        subs_filter 'href="/' 'href="/blog/';
        subs_filter 'url(/' 'url(/blog/';
        subs_filter 'url(\'/' 'url(\'/blog/';
        subs_filter '"/admin' '"/blog/admin';
        subs_filter '"/static' '"/blog/static';

        location ~ /static/ {
            etag         on;
            expires      max;
        }
    }
```
链接：https://zhoushuo.me/blog/
