### ISSUE TITLE
0.15.14的标签标签页面不显示

### ISSUE THREAD

**Issue by lxjcxj** [firekylin/firekylin#453]
看了一些closed issue，照着上面的做了，修改了自定义模板，标签页面还是不显示。
重新装了0.15.14包，还是不显示。
这又是什么问题？

**Comment by lxjcxj** [comment]
今天怎么又好了

**Comment by lizheming** [comment]
@lxjcxj 这个是因为 tag 缓存更新机制有问题，我下个版本会把缓存去掉，实时取吧。
