### ISSUE TITLE
为什么我设置摘要字符数后，首页摘要没有样式呢？

### ISSUE THREAD

**Issue by opsarno** [firekylin/firekylin#456]
https://fandenggui.com/

**Comment by opsarno** [comment]
阅读设置中：
自动生成摘要截取的字符数

**Comment by lizheming** [comment]
你设置了200个字？我看好像是已经生效的，样式是指什么问题？

**Comment by opsarno** [comment]
@lizheming 我尝试设置了不同字符的限制，但都不是附图的效果。 
![image](https://user-images.githubusercontent.com/8611744/34282226-c5dc700a-e6fe-11e7-96c1-1148c616b323.png)

**Comment by lizheming** [comment]
哦，自动截取会把文章全部格式化然后取一定的字数，所以没办法保留样式。如果你需要样式的话可以选择手动设置摘要，在需要在首页显示的内容后面增加 `<!--more-->` 标签即可，程序会自动分割文章。

**Comment by opsarno** [comment]
@lizheming Get~  非常感谢，很实用！
