### ISSUE TITLE
后台-系统设置-下 评论管理提交报错

### ISSUE THREAD

**Issue by longain** [firekylin/firekylin#460]
后台-系统设置-下 评论管理提交报错 REFERRER_ERROR

**Comment by lizheming** [comment]
这个是因为当前访问的域名和系统设置的域名导致的，你先进数据库修改下 fk_options 里面的 site_url 吧。

**Comment by longain** [comment]
域名对着

**Comment by lizheming** [comment]
协议没对？两者需要完全一样…

**Comment by longain** [comment]
要加https://吗？

**Comment by lizheming** [comment]
嗯

**Comment by longain** [comment]
不行，好像后台所有提交按钮 都报错 REFERRER_ERROR，昨天都可以，今天看有个更新我就更新了，更新了就这样了

**Comment by lizheming** [comment]
对，你得先去数据库里修改一下，因为安全问题，所有的后台写的接口都做了域名的判断。

**Comment by longain** [comment]
改了，还报错

**Comment by lizheming** [comment]
改成什么了，访问的地址是什么

**Comment by longain** [comment]
https//www.longain.top

**Comment by lizheming** [comment]
`https://www.longain.top` 少了一个冒号吧

**Comment by longain** [comment]
不是

**Comment by longain** [comment]
咋整啊

**Comment by lizheming** [comment]
截图看看你配的是什么？

**Comment by qfdk** [comment]
@longain 其实你可以先跑起来,用ip地址加端口访问 然后套个NGINX就好了. 之前我也有这样的问题,就是 设置的博客地址和 访问的不一样造成的.

**Comment by longain** [comment]
谢谢大家，我重新搭建了一下好了

**Comment by lizheming** [comment]
这块我之后改一下吧，只判断 host，忽略 http 和 https 之类的。

**Comment by longain** [comment]
0.15.16  主题是不能编辑了吗

**Comment by lizheming** [comment]
提示什么

**Comment by longain** [comment]
没提示什么，就是右边那快是灰色的不能选择点击

**Comment by lizheming** [comment]
可以的，如果不能在线编辑的话也可以选择手动编辑文件。

**Comment by longain** [comment]
嗯

**Comment by longain** [comment]
谢谢了，应给是主题文件我备份后变成只读了吧

**Comment by lizheming** [comment]
那也不应该...可以 F12 看看控制台有没有报错....

**Comment by longain** [comment]
没有报错，有一个警告 : 此页上的代码禁用了反向和正向缓存。有关详细信息，请参阅: http://go.microsoft.com/fwlink/?LinkID=291337

**Comment by lizheming** [comment]
额... IE 啊.... 那你再倒腾倒腾在线编辑吧，如果不行就手动改服务器上的文件吧。另外注意不要改默认的主题，在线升级的时候会覆盖它的。

**Comment by longain** [comment]
嗯嗯，谢谢了
