### ISSUE TITLE
REFERRER_ERROR 错误，不读取最新数据

### ISSUE THREAD

**Issue by choicky** [firekylin/firekylin#470]
### REFERRER_ERROR
我最近在两台 vps 新安装了 firekylin ，两台 vps 的配置完全一样。

但第二台 vps 安装的 firekylin 在登陆后编辑后台选项时，点击提交就会提示 `REFERRER_ERROR` ，且 mysql 的数据并没有被更新，所以我怀疑数据没有上传到服务器。

我搜索了一下，有人在 [后台-系统设置-下 评论管理提交报错](https://github.com/firekylin/firekylin/issues/460 ) 提到了类似的问题。那里建议修改数据库的 `site_url ` 。

我发现第二台 vps 里面的 `site_url ` 是 `http://` 开头，而第一台 vps 是 `https://` 开头，估计是我第二台 vps 安装 firekylin 时，我忘了修改 site_url ，所以写入数据库的 http 。而我这两台 vps 实际上都使用 https 。

### firekylin 不读取 mysql 更新后的数据
我把 `site_url ` 里面的值改为  `https://` 开头 ，然后，奇怪的事情发生了，firekylin 后台依然显示为 `http://` 开头，没有显示 `https://` 开头。

我已经用 pm2 stop 并重新 start firefkylin ，问题依旧。我重启了 web 服务，问题依旧。

### caddy server
我这两台 vps 都用了 caddy server 。对于个人用户而言， caddy 的方便之处是自己会搞定 https

目前配置如下。不知道这配置够准确了没有。如够准确了，希望项目组也集成一个 `Caddyfile_default` 进去。
```
itlaws.cn {
    gzip
    log /var/log/caddy/itlaws.cn.log
    tls zhoucaiqi@gmail.com
    proxy / localhost:8360 {
        header_upstream Host {host}
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-Proto {scheme}
    }
}
````

**Comment by choicky** [comment]
我把 `~/runtime/cache` 里面的内容删掉，终于读取 mysql 里面的新数据了。 读取了 `https://` 开头 `site_url` 之后，就正常了，不再出现 `REFERRER_ERROR` 了。

**Comment by ddhhz** [comment]
太好了！

https://github.com/firekylin/firekylin/commit/5ea1a0cdbc98c3855aa3e6018588d07fafed03a8 里增加了referrer 验证。

如果还有问题请回复。谢谢支持！

**Comment by lizheming** [comment]
https://github.com/lizheming/examples/blob/master/thinkjs/Caddyfile 
Caddy 的配置可参考我写的 ThinkJS 的 Caddy_default 配置，`header_upstream` 可以直接使用 `transparent` 替换，然后还需要指定下静态目录不走反代。

**Comment by choicky** [comment]
@ddhhz 最近还在纠结是用 iplaws.cn 还是 itlaws.cn ，哈哈。我写点知识产权法律和互联网的内容，用哪个域名好呢？给个建议~  
 ip 的本意是知识产权

**Comment by ddhhz** [comment]
哈哈 我知道 Intellectual Property。看你受众咯，我喜欢 iplaws 😁。

**Comment by choicky** [comment]
@ddhhz 好，启用 https://iplaws.cn 了。
