### ISSUE TITLE
nodejs 服务器重启自启动脚本谁有共享一下

### ISSUE THREAD

**Issue by longain** [firekylin/firekylin#471]
nodejs 服务器重启自启动脚本谁有共享一下

**Comment by ddhhz** [comment]
`pm2 startOrReload` 不喜欢？你也可以用 `nodemon`、`forever`之类的。

**Comment by qfdk** [comment]
如果不满意可以用cluster 这个库 自己写个简单的

**Comment by longain** [comment]
谢谢您！！
