### ISSUE TITLE
最新版本的firekylin提交报错

### ISSUE THREAD

**Issue by alawnchen** [firekylin/firekylin#473]
最新版本的firekylin写文章时候不管发布还是保存草稿都会报错**REFERRER_ERROR**。后面还发现只要是提交数据都会报这个错误！！
![_20180113030255](https://user-images.githubusercontent.com/1811463/34890809-5aad445a-f80e-11e7-835d-babc72b1db32.png)

**Comment by ddhhz** [comment]
你管理页面的域名和博客域名不一样吧。安全起见添加了 Referrer 验证。https://github.com/firekylin/firekylin/commit/5ea1a0cdbc98c3855aa3e6018588d07fafed03a8

您可以使用和博客一样的域名访问管理界面，或删除这几行即可：
https://github.com/firekylin/firekylin/blob/5ea1a0cdbc98c3855aa3e6018588d07fafed03a8/src/admin/controller/api/base.js#L34-L36

**Comment by alawnchen** [comment]
@ddhhz 谢谢提点，已经解决！最新版本的代码修改略有不同
![_20180113145427](https://user-images.githubusercontent.com/1811463/34903690-fb789610-f871-11e7-82a4-65f1957344f9.png)
