### ISSUE TITLE
如何定义baseUrl?

### ISSUE THREAD

**Issue by zhangxinshuai** [firekylin/firekylin#476]
因为我的项目以目录分割了，博客的url会有个目录前缀https://xxx.com/yyy/?博客安装后首页的链接都少一个/yyy/

**Comment by ddhhz** [comment]
解决这个问题 请使用 nginx 的 sub_filter / subs_filter

举个例子如果子目录是 blog，将

`href="/` 替换为 `href="/blog/`
`url(/` 替换为 `url(/blog/`
`url('/` 替换为 `url('/blog/`
`"/admin` 替换为 `"/blog/admin`

即可。

Dupe of #452

**Comment by zhangxinshuai** [comment]
万分感谢，解决了~
