### ISSUE TITLE
忘记密码怎么办 死链

### ISSUE THREAD

**Issue by ddhhz** [firekylin/firekylin#478]
Wiki 中忘记密码怎么办的文章链接死了

**Comment by lizheming** [comment]
不是已经有忘记密码的功能了？

**Comment by ddhhz** [comment]
我以为这个是没有邮箱数据库或者后台改的。😄

**Comment by lizheming** [comment]
没有邮箱就后台加一下邮箱吧，走系统自带的这个会方便一点，数据库改的还有点麻烦。

**Comment by ddhhz** [comment]
哈哈 好的 那链接可以删除一下。

**Comment by lizheming** [comment]
好的

**Comment by Stephenzho** [comment]
找回密码时，收不到邮箱，admin/user/forgot接口返回{"errno":0,"errmsg":"","data":""}

**Comment by lizheming** [comment]
发邮件主要看你自己的机器支不支持，而且发出去的有可能会进垃圾邮箱，所以原因比较复杂，建议不行的话就上数据库自己改吧。
