### ISSUE TITLE
网站后台出现REFERRER_ERROR

### ISSUE THREAD

**Issue by Ycloub** [firekylin/firekylin#481]
在后台改了一下网站地址，结果无论怎么提交都提示
![image](https://user-images.githubusercontent.com/25115371/35208962-d65393ec-ff85-11e7-9f67-201f5cca1e38.png)
而且，提交不成功，一直显示提交中

**Comment by shaoyun** [comment]
我也是，更新后，发布修改都是这个错误

**Comment by lizheming** [comment]
各位看一下当前 firekylin 版本是多少，后台基础设置中的网站地址配置的是什么地址，以及当前你访问博客的地址是什么地址，看一下这两个地址是否一致。

**Comment by yujintao529** [comment]
我的版本是0.15.17,也出现了这个问题，就刚才自动更新后出现的

**Comment by ddhhz** [comment]
0.15.17 更新了 REFERRER_ERROR 的判断方式 “referrer 校验仅校验主域部分，避免端口和协议不同导致的 REFERRER_ERROR 报错”。

请发一下：系统设置 > 基本设置 > 网站设置 里的域名和你地址栏中显示的域名。

**Comment by yujintao529** [comment]
我看了下，网站设置里变成ip了，不是域名了。我手动的改变数据库里的设置，但是没有起作用～？程序里怎么修改？

**Comment by ddhhz** [comment]
你是怎么改的？请发一下语句，截图。

**Comment by shaoyun** [comment]
我更新到0.15.17后就好了

**Comment by yujintao529** [comment]
![image](http://ww4.sinaimg.cn/large/0060lm7Tly1fnsnjfq5axj30z8058my5.jpg
)
```
UPDATE `fk_options` SET `key`="site_url",`value`="http://www.demon-yu.com",`desc`="address" WHERE `key`="site_url"
```
图片传不上去，弄了个外链可以看到么？

**Comment by ddhhz** [comment]
@yujintao529 你更新之前是 ip 吗？可能是缓存问题。请试试删除 runtime 再重启试试。

**Comment by yujintao529** [comment]
ok了，缓存删了就好了

**Comment by lizheming** [comment]
@shaoyun 好的，收到~
