### ISSUE TITLE
目前是否基于ThinkJS3的版本？

### ISSUE THREAD

**Issue by JackChius** [firekylin/firekylin#482]
如题，-->issue太多，可能前面有人问了没看到，见谅

**Comment by lizheming** [comment]
目前还是 2，可能过年的时候会抽空升级成3。

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/tree/1.x 该分支已经是 ThinkJS 3 了，先放分支上测试一下，年后再发新版更上去。

**Comment by lizheming** [comment]
@JackChius 基于 ThinkJS 3 的 1.0 版本已发布，欢迎使用。
