### ISSUE TITLE
输入emoji（如 🍎 字符）无法保存

### ISSUE THREAD

**Issue by brightgems** [firekylin/firekylin#483]
输入emoji（如 🍎 字符）无法保存

错误：  Unexpected Token

**Comment by xuexb** [comment]
这个应该是需要数据库和字段类型支持才可以，参考：[问题解答#如何添加emoji表情支持](https://github.com/firekylin/firekylin/wiki/%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94#%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0emoji%E8%A1%A8%E6%83%85%E6%94%AF%E6%8C%81) 。

**Comment by ddhhz** [comment]
同上。https://blog.whe.me/post/firekylin-add-emoji-support.html

**Comment by ddhhz** [comment]
Close due to inactivity.
