### ISSUE TITLE
firekylin的文章是如何保存的？

### ISSUE THREAD

**Issue by AlexYzhov** [firekylin/firekylin#484]
原来的firekylin出了点问题，管理员界面只剩下了“概述”和“文章管理”两个大项。第一次更新时选择解压覆盖原firekylin的内容，依然有异常。之后选择删除源文件夹，重新解压安装，结果文章都丢失了。更新前备份了firekylin文件夹，请问如何恢复文章？

**Comment by ddhhz** [comment]
所有的文章都在数据库里，不在文件系统里。请前往之前的数据库表中找回。

**Comment by AlexYzhov** [comment]
谢谢！发现了这个问题，正在找回ing。是我记错了数据库名，重搭的时候firekylin自动新建了一个table。麻烦关闭一下这个issue！

**Comment by ddhhz** [comment]
没问题😊
