### ISSUE TITLE
无法发布文章，报错REFERRER_ERROR

### ISSUE THREAD

**Issue by xiangfan211** [firekylin/firekylin#485]
刚装上，发布文章的时候报错。编辑文章也不行，烦请看看：
![qq 20180208201634](https://user-images.githubusercontent.com/13128860/35972558-523f987c-0d0d-11e8-8f23-8f91be358c8c.jpg)

**Comment by ddhhz** [comment]
系统设置 > 基本设置 > 网站设置 里的域名 需要和地址栏中的域名相同。

#481

**Comment by xiangfan211** [comment]
大大您好，还是不行噢。修改域名后都无法保存，还是报错呢。
![qq 20180208220005](https://user-images.githubusercontent.com/13128860/35976685-ded6c41e-0d1b-11e8-91c2-2e5517f61dde.jpg)

**Comment by ddhhz** [comment]
请按照 #481 在数据库中更改 之后删除runtime文件夹清空缓存重启pm2

**Comment by xiangfan211** [comment]
已解决，谢谢。
