### ISSUE TITLE
导入wordpress的XML文件，一直无响应了，已经30分钟了

### ISSUE THREAD

**Issue by xiangfan211** [firekylin/firekylin#486]
后台导入WP的XML文件，一直处于上传中状态，不知何故，烦请看看[
![tim 20180209112217](https://user-images.githubusercontent.com/13128860/36010273-8ce88d98-0d8b-11e8-84bf-5fab45b935a6.png)
](url)

**Comment by ddhhz** [comment]
文件太大 413 Request Entity Too Large
@lizheming 是不是 `max_file_size` 这个东西得设一下？
https://thinkjs.org/zh-cn/doc/2.2/config.html#post

**Comment by lizheming** [comment]
@xiangfan211 能不能说一下你的 xml 多大？
@ddhhz 上传文件大小需要同时设置 nginx 和 firekylin 好像。

**Comment by ddhhz** [comment]
他在另外一个issue里说是 1.9MB

**Comment by xiangfan211** [comment]
感谢老大，已经解决。

**Comment by lizheming** [comment]
@xiangfan211 请问如何解决的？
@ddhhz 文档写了默认大小都是 1G 的，应该是够用的，可能是他那边 nginx `client_max_body_size` 设置的比较小的原因。

**Comment by xiangfan211** [comment]
@lizheming 卸载了nginx重新整了一遍，然后重新导入就正常了。也有可能是京东云有关系。因为我本地正常，就是服务器上才出现莫名其妙的问题。

**Comment by lizheming** [comment]
@xiangfan211 OK，那我先 close 了，之后有问题再说。
