### ISSUE TITLE
文件上传，配置了阿里云后报错

### ISSUE THREAD

**Issue by xiangfan211** [firekylin/firekylin#488]
文件上传，配置了阿里云后报错；七牛云是正常的；

**Comment by ddhhz** [comment]
文件导入问题在另外一个issue里讨论。
上传图片到阿里云报错信息有吗？

**Comment by twang281314** [comment]
@xiangfan211 可以把错误截图发出来看下

**Comment by xiangfan211** [comment]
@twang281314 @ddhhz 配置阿里云后，正常，文章中插入时报错提示如下：
![1](https://user-images.githubusercontent.com/13128860/36068388-556ec884-0f0f-11e8-9d82-3d60f4bebf2b.jpg)
![qq 20180211093621](https://user-images.githubusercontent.com/13128860/36068390-5910a354-0f0f-11e8-8d0c-6805d7fb2cc5.jpg)

**Comment by twang281314** [comment]
服务区域 应该写 oss-cn-shenzhen 这里有说明 https://github.com/ali-sdk/ali-oss

**Comment by xiangfan211** [comment]
@twang281314 已调试解决，正常了。感谢。
