### ISSUE TITLE
系统设置bug

### ISSUE THREAD

**Issue by hiraetho** [firekylin/firekylin#489]
系统设置-》网站地址；不小心删掉了一位端口号；点了保存后，导致各个接口都返回  
 errmsg:"REFERRER_ERROR"
errno:1000
现在不知道怎么处理？？！？！？？！？！？！？！？！？！

**Comment by ddhhz** [comment]
请按照 #485 #482 的步骤 在数据库里更新一下再清除缓存重启即可

**Comment by ddhhz** [comment]
请按照 #485 #481 的步骤 在数据库里更新一下再清除缓存重启即可

**Comment by hiraetho** [comment]
可以了，3q
