### ISSUE TITLE
一个弱弱的建议：编辑器能否支持对视频文件/URL的解析？

### ISSUE THREAD

**Issue by xiangfan211** [firekylin/firekylin#490]
文章编辑中，用到视频的场景的非常多，目前还不支持，有两点建议，不知是否可行？
1、通过上传附件形成，插入到编辑器中，文章发布后就能播放；
2、插入URL，自动解析对应的title等，如下图所示：
![qq 20180227102409](https://user-images.githubusercontent.com/13128860/36707250-6d7ba78a-1ba8-11e8-8d7c-9fbcda4ac68f.jpg)
![qq 20180227102416](https://user-images.githubusercontent.com/13128860/36707251-6da8a4ce-1ba8-11e8-8d51-ce24b5cabbc9.jpg)
我本地上用discourse的oneboxch插件测试，可以实现，但是总有些问题。

**Comment by ddhhz** [comment]
你是说外部的视频？直接用 iframe 引用就可以呀。

![image](https://user-images.githubusercontent.com/5880908/36707100-dfdf961a-1b3a-11e8-877c-eadec7c94971.png)

![image](https://user-images.githubusercontent.com/5880908/36707115-eea8092a-1b3a-11e8-9624-98686fc97945.png)

**Comment by xiangfan211** [comment]
@ddhhz iframe 不行的。
![image](https://user-images.githubusercontent.com/13128860/36707633-15f39a98-1baa-11e8-8b0c-fcdde535ffa0.png)

**Comment by ddhhz** [comment]
请发布或点击![image](https://user-images.githubusercontent.com/5880908/36707724-8e576e32-1b3d-11e8-9509-2a8e88394d8d.png) 眼睛预览。

**Comment by lizheming** [comment]
@xuangfan211 markdown 预览的时候不行，发布之后是可以的。

**Comment by wei** [comment]
Closed due to inactivity.
