### ISSUE TITLE
启用新模板，资源还是引用的默认模板的资源

### ISSUE THREAD

**Issue by MiderWong** [firekylin/firekylin#492]
我把默认模板复制了一份，起名`firekylin_self`，修改完资源，但是怎么刷新都不生效，后来发现是资源引用地址写死了，不是根据模板地址动态生成的，把这layout.html中有下面两句话：
```
<link rel="stylesheet" href="/theme/firekylin/res/css/all.css" type="text/css" data-ls="css_firekylin">
```
和
```
<script src="/theme/firekylin/res/js/firekylin.js" data-ls="js_firekylin"></script>
```
把上面两句话中的`firekylin`改为`firekylin_self`就可以引用新模板的资源了

另外我注意到在layout.html中引用了自定义模板中的配置：`themeConfig.customCSS`，是不是把修改后的css内容放到这里面，同样可以实现资源更新？

**Comment by lizheming** [comment]
是的，你说的对~

**Comment by MiderWong** [comment]
恩，有没有可能直接在前端页面拿到当前使用的主题？如果能拿到主题名字，改动一下layout.html中资源的引用地址，就会方便很多，而且模板定制难度会降低许多。

**Comment by lizheming** [comment]
嗯，暂时还没有这个方法，你先自己在主题里写名字吧。后面考虑下怎么弄。

**Comment by MiderWong** [comment]
恩。好的。辛苦大神~~

**Comment by MiderWong** [comment]
找到临时性方案：
#### 1、关于字体的解决方案：
由绝对地址改为相对地址，具体修改如下：
修改默认主题`/theme/firekylin/res/css/icon.css`文件中对字体的引用：
```
@font-face {
  font-family: iconfont;
  src: url(../font/iconfont.eot);
  src: url(../font/iconfont.eot?#iefix) format("embedded-opentype"),url(../font/iconfont.ttf) format("truetype"),url(../font/iconfont.svg#iconfont) format("svg");
}
```
#### 2、关于新主题资源地址不更新的解决方案：
由写死的主题名称改为当前所选主题的名称，具体修改如下：
修改默认主题`/theme/firekylin/layout.html`文件中对资源的引用：
###### ①、修改css文件的引用，文件第15行：
```
<link rel="stylesheet" href="/theme/{{options.theme}}/res/css/all.css" type="text/css" data-ls="css_firekylin">
```
###### ②、修改js文件的引用，文件第113行：
```
<script src="/theme/{{options.theme}}/res/js/firekylin.js" data-ls="js_firekylin"></script>
```
不知这样修改是否可行？

**Comment by MiderWong** [comment]
@lizheming  ok，diy暂时到这里，有时间再研究一下在页面加入“返回顶部”操作入口，

**Comment by MiderWong** [comment]
@lizheming  

> 找到临时性方案：
>
> 1、关于字体的解决方案：
> 由绝对地址改为相对地址，具体修改如下：
> 修改默认主题/theme/firekylin/res/css/icon.css文件中对字体的引用：
> ```
> @font-face {
>   font-family: iconfont;
>   src: url(../font/iconfont.eot);
>   src: url(../font/iconfont.eot?#iefix) format("embedded-opentype"),url(../font/iconfont.ttf) format("truetype"),url(../font/iconfont.svg#iconfont) format("svg");
> }
> ```
> 2、关于新主题资源地址不更新的解决方案：
> 由写死的主题名称改为当前所选主题的名称，具体修改如下：
> 修改默认主题/theme/firekylin/layout.html文件中对资源的引用：
> ①、修改css文件的引用，文件第15行：
> ```
> <link rel="stylesheet" href="/theme/{{options.theme}}/res/css/all.css" type="text/css" data-ls="css_firekylin">
> ```
> ②、修改js文件的引用，文件第113行：
> ```
> <script src="/theme/{{options.theme}}/res/js/firekylin.js" data-ls="js_firekylin"></script>
> ```

上面提到的几处修改，是否可以直接在默认主题中修改，并在下一个版本中发布？如果可以，你帮忙修改一下吧，我就不提交了，只是简单的模板文件修改，没有功能的修改。

**Comment by lizheming** [comment]
好的
