### ISSUE TITLE
两步验证关闭问题

### ISSUE THREAD

**Issue by bpplpp** [firekylin/firekylin#493]
上回我也遇到这个情况，删除过这个注册表('two_factor_auth', 'LJTWGJCCGF2FxxxxxxxxxxxxxBI', '是否开启二步验证');，然后没解决。
现在隔了一段时间了，手机上的验证码居然无法使用，中间刷过机，恢复备份。
上次解决方式是导出相关数据然后重新安装才解决的，删除数据库那个两步验证无效啊。咋办？

**Comment by lizheming** [comment]
手动修改完数据库需要重启一下服务才行

**Comment by bpplpp** [comment]
删除了，机器也重启了，还是不行：`请填写二步验证码`

**Comment by lizheming** [comment]
还要删一下项目根目录下的 runtime 文件夹才行
