### ISSUE TITLE
FILE_UPLOAD_MOVE_ERROR

### ISSUE THREAD

**Issue by zxysilent** [firekylin/firekylin#495]
![image](https://user-images.githubusercontent.com/19162822/37250885-1ac67342-2541-11e8-9323-6254704df354.png)

**Comment by lizheming** [comment]
什么平台？如何操作的，上传的图片名称是什么？

**Comment by zxysilent** [comment]
![hpdjd 1p8fynplbafmy 8x](https://user-images.githubusercontent.com/19162822/37251090-f5a9539c-2543-11e8-9be3-8ce20be756f5.png)

windows
选择文件上传，尝试了几次试了不同格式的图片 .
上传到本地的

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/blob/master/src/admin/service/upload/local.js#L26
你可以在这一行前加一下 `console.log(e)` 看一下具体的报错内容么？

**Comment by zxysilent** [comment]
![image](https://user-images.githubusercontent.com/19162822/37871156-be01342e-3019-11e8-935f-d20670e659fa.png)

**Comment by lizheming** [comment]
果然是跨分区存储的问题，算是 Windows 系统保存文件碰到的经典案例了。这个是因为我把临时目录设置为系统的临时目录了，Linux 还好说，Windows 估计就会造成这个问题，我来改一下临时目录位置吧。

**Comment by zxysilent** [comment]
thank you
