### ISSUE TITLE
0.x升级1.0.0后 admin/dashboard无法加载 `Cannot read property 'call' of undefined`

### ISSUE THREAD

**Issue by Git2Frank** [firekylin/firekylin#499]
![image](https://user-images.githubusercontent.com/21982381/37630966-6bea61a6-2c22-11e8-8de7-40d0ff46b995.png)

**Comment by lizheming** [comment]
清一下浏览器缓存

**Comment by Git2Frank** [comment]
@lizheming 没问题了，尴尬..
