### ISSUE TITLE
Favicon上传失败

### ISSUE THREAD

**Issue by wangdehu** [firekylin/firekylin#502]
Version：
>系统概况
服务器系统：linux
Node.js版本：9.8.0
V8引擎版本：6.2.414.46-node.21
MySQL版本：5.7.21-0ubuntu0.16.04.1
ThinkJS版本：3.2.7
FireKylin版本：1.0.0

Deccription:

上传ico文件始终显示上传中，Console报错信息为
![image](https://user-images.githubusercontent.com/24820236/37966750-f7257df8-31fb-11e8-98ec-033e5a809eef.png)

确认ico文件正常，使用url形式正常 ,
用url下的icon下载下来上传也不行。
 [百度的icon](https://www.baidu.com/favicon.ico)

**Comment by lizheming** [comment]
因为安全问题显示了文件上传的类型，漏掉 .ico 文件啦，已补上~感谢反馈
