### ISSUE TITLE
v1.0的后台保存主题出红框

### ISSUE THREAD

**Issue by 85865528** [firekylin/firekylin#503]
保存主题时有红框，却又可以保存成功，另外就是，官网没有开放主题上传吗，我上传不了主题，不能为大家提供方便
![2018-03-29 4 06 44](https://user-images.githubusercontent.com/22594498/38077384-63f705bc-336b-11e8-8767-06626edfedd6.png)

**Comment by lizheming** [comment]
保存的问题我稍后看一下。主题市场是有的，但是目前有点问题，之后有时间我修复一下。

**Comment by lizheming** [comment]
问题查到了，是之前大版本升级遗留下来的一些写法的问题，已修改，下个版本会带上的。感谢反馈~
