### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by swust-xiaoj** [firekylin/firekylin#504]
文章从后台点击preview，跳转的页面代码高亮正常，但是直接访问站点文章，代码高亮不正常，
站点：[dearxiaojie.top](http://dearxiaojie.top)

**Comment by lizheming** [comment]
这些文章是不是都是导入进来的？看了下代码感觉不像是我们的高亮代码。

**Comment by swust-xiaoj** [comment]
对，通过hexo插件生成的json文件导入的

**Comment by lizheming** [comment]
嗯，看着比较像。你发一篇 markdown 的原文给我，我看一下，之前帮朋友导过 hexo，代码格式这块应该是要做一下修改的，导入过来的不能直接用。

**Comment by swust-xiaoj** [comment]
[https://github.com/swust-xiaoj/paradise/blob/master/source/_posts/diy-highcharts.md](https://github.com/swust-xiaoj/paradise/blob/master/source/_posts/diy-highcharts.md)这样发您ok吗

**Comment by lizheming** [comment]
你给代码块指定下语言试试？例如
```
    ```js
    console.log(123);
    ```
```

**Comment by swust-xiaoj** [comment]
[http://dearxiaojie.top/post/use-javascript-to-handle-9-patch.html](http://dearxiaojie.top/post/use-javascript-to-handle-9-patch.html),我在后台编辑增加JavaScript标识后，显示正常了

**Comment by swust-xiaoj** [comment]
不过我发现，我在后台不对md文件做操作，直接在编辑的位置重新发布文章也会好使

**Comment by lizheming** [comment]
好的，可能是导入的时候高亮处理的问题，我之后查一下在本 issue 回复一下你。暂时先把这个 issue 关闭了。
