### ISSUE TITLE
能否增加对外链播放器的支持

### ISSUE THREAD

**Issue by wangdehu** [firekylin/firekylin#507]
我尝试在修改主题，增加外链播放器。如插入以下代码
```html
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=100% height=110 src="//music.163.com/outchain/player?type=0&id=2173212928&auto=1&height=90"></iframe>
```
得到的效果如图，
![xc nico88ip iusest u8](https://user-images.githubusercontent.com/24820236/38383107-2f60cf8a-393e-11e8-92b0-93b9767927b2.png)

当然还有些问题，比如（设置为自动播放的时候，打开多个个页面会有同时播放）

是否考虑增加对外链播放器的支持。

**Comment by ddhhz** [comment]
设置自动播放的时候多个页面会播放的问题 可以你自己写 JS 解决 sessionStorage 或 cookie 或 referrer 之类。

**Comment by lizheming** [comment]
白色色块是你自己为了马赛克加上去的？我试了下样式并没有什么特别的问题。自动播放的话需要自己制作主题去操作。楼上说的 JS 操作或者直接用 `<iframe>` 修改整站的结构应该都 OK，可以参考下网易云音乐。

**Comment by wangdehu** [comment]
@lizheming  的确是自己加的马赛克，我自己倒是可以调整，就是提出建议，是否可以加入一个为外链播放器的特殊页面，可以自动实现播放的各种问题。

**Comment by lizheming** [comment]
这个需求比较个性化，我们官方暂时没精力做这些。建议你可以做一个支持这样的主题出来可以分享给大家~ 我就先暂时把这个 issue 关闭了。
