### ISSUE TITLE
ctx.get('pathname')为空

### ISSUE THREAD

**Issue by kongxun** [firekylin/firekylin#508]
https://github.com/firekylin/firekylin/blob/master/www/theme/firekylin/inc/comment.html
```
data-thread-key="{{think.md5(ctx.get('pathname'))}}"
```
此处ctx.get('pathname') 为空，导致所有post下评论都一样。

**Comment by lizheming** [comment]
的确有问题，下次发布前你可以按照 commit 手动修改下主题改成 `ctx.param('pathname')`
