### ISSUE TITLE
主题压缩问题

### ISSUE THREAD

**Issue by lycly** [firekylin/firekylin#510]
使用官方给的主题压缩方法，在firekylin_1.0.1版本压缩html失败，显示LocalstoragePlugin: can't open '/theme/{{options.theme}}/res/css/all.css' file; in file `www/theme/firekylin/layout.html` on line: 15, column: 3

**Comment by lyuly** [comment]
把layout.html里的{{options.theme}}改为firekylin，可以生成压缩文件，但是主页打开显示index失败

**Comment by lizheming** [comment]
`stc.view.config.js` 不建议用户使用，因为有些功能需要环境，之后会删除这个文件。
