### ISSUE TITLE
1.x版本admin页面没有favicon

### ISSUE THREAD

**Issue by fz568573448** [firekylin/firekylin#511]
:)

**Comment by ddhhz** [comment]
https://github.com/firekylin/firekylin/blob/0cfee47424459fa58c33942414cc2330343991f2/view/admin/index_index.html#L3-L10

head 里需要添加
https://github.com/firekylin/firekylin/blob/7ac4af118a8b8b0055b6dca2dc5f12b9118e6adb/www/theme/firekylin/layout.html#L7

欢迎 PR

**Comment by lizheming** [comment]
@ddhhz 😆没事，是我让他提的 issue，我改一下得了。
