### ISSUE TITLE
封面图片不显示

### ISSUE THREAD

**Issue by bailangsyc** [firekylin/firekylin#516]
发布文章的时候添加了封面图片的url，为什么首页不显示呢？

**Comment by lizheming** [comment]
这个字段是为了自定义主题的用户准备的，默认主题没有封面图显示的功能，你可以自己修改下主题。

**Comment by bailangsyc** [comment]
麻烦你了，这个怎么修改，我之前用的是hexo next主题，因为加载太慢了，感觉咱这个博客系统速度挺快的。

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/blob/master/www/theme/firekylin/index.html#L21 之后增加
```nunjucks
<img src="{{post. featuredImage}}" />
``` 
具体样式你自己调吧

**Comment by bailangsyc** [comment]
好的 ，谢谢。我自己研究研究！
