### ISSUE TITLE
发表文章的时候警告 referer error

### ISSUE THREAD

**Issue by chcifung** [firekylin/firekylin#519]
0|firekyli |     at Protocol.handshake (/root/firekylin/node_modules/mysql/lib/protocol/Protocol.js:52:41)
0|firekyli |     at Connection.connect (/root/firekylin/node_modules/mysql/lib/Connection.js:136:18)
0|firekyli |     at /root/firekylin/node_modules/thinkjs/lib/adapter/socket/mysql.js:117:25
0|firekyli |     at _class.run (/root/firekylin/node_modules/thinkjs/lib/util/await.js:52:40)
0|firekyli |     at Object.think.await (/root/firekylin/node_modules/thinkjs/lib/core/think.js:1032:25)
0|firekyli |     at _class.getConnection (/root/firekylin/node_modules/thinkjs/lib/adapter/socket/mysql.js:114:23)
0|firekyli |     at _class._callee2$ (/root/firekylin/node_modules/thinkjs/lib/adapter/socket/mysql.js:168:27)
0|firekyli |     at tryCatch (/root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:88:40)
0|firekyli |     at GeneratorFunctionPrototype.invoke [as _invoke] (/root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:341:22)
0|firekyli |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:121:21)
0|firekyli |     at step (/root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
0|firekyli |     at /root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
0|firekyli |     at Promise._execute (/root/firekylin/node_modules/bluebird/js/release/debuggability.js:272:9)
0|firekyli |     at Promise._resolveFromExecutor (/root/firekylin/node_modules/bluebird/js/release/promise.js:473:18)
0|firekyli |     at new Promise (/root/firekylin/node_modules/bluebird/js/release/promise.js:77:14)

**Comment by chcifung** [comment]
这是pm2 logs报错记录  看不出来做哪些处理能解决？

**Comment by ddhhz** [comment]
referrer error 请搜索 issues 解决。

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/issues/485
https://github.com/firekylin/firekylin/issues/481
https://github.com/firekylin/firekylin/issues/473

**Comment by chcifung** [comment]
谢谢
