### ISSUE TITLE
1.0.3的release里面多了个文件src/admin/service/upload/._local.js

### ISSUE THREAD

**Issue by fz568573448** [firekylin/firekylin#522]
RT。会导致运行不起来。在Mac上打包的时候不小心弄进去的吧。

**Comment by yachen4ever** [comment]
毕竟我雪啊

**Comment by lizheming** [comment]
嗯，找到原因了。昨天我以为是隐藏文件，看了下文件夹没有就没管了。今天再瞅了一眼发现原来 Mac 还有个东西叫扩展属性，真是坑大爹了... 1.0.3 的包已经重新上传了，应该 OK 了。

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/commit/3725e04cd6c0d3bd556c21599fdb636542fa759b 已增加 `-x` 避免以后再继续出现此类问题。
