### ISSUE TITLE
我也凑凑热闹~~

### ISSUE THREAD

**Issue by sanguineJohn** [firekylin/firekylin#524]
www.laijianlou.top

**Comment by ddhhz** [comment]
看到你去#34凑热闹了😁

**Comment by sanguineJohn** [comment]
发错地方了，还这么巧让你给看到了......   这响应速度，可以～

**Comment by lizheming** [comment]
哈哈哈，楼上这相应速度也很是很快了~

**Comment by sanguineJohn** [comment]
大家的反应速度确实不慢～～， 我今天发表文章的时候，总是发现存储失败，没有找到原因，于是....， 我又换了一个博客系统...., 还在捣鼓中.....

**Comment by lizheming** [comment]
是不是报 REFERRER_ERROR 的错误？

**Comment by sanguineJohn** [comment]
嗯嗯是的，就是这个错误～～～

**Comment by ddhhz** [comment]
REFERRER_ERROR 坑了一堆人呀😂

**Comment by sanguineJohn** [comment]
而且每次发布文章，总是需要选择时间才行，感觉还是有点麻烦～

**Comment by lizheming** [comment]
这个错误是因为你当前访问的域名和后台网站设置配置的域名不一致的原因。你使用后台配置的那个域名访问后台就可以了。发布文章的时候不强制你选择时间，默认是当前的时间的。

@ddhhz REFERRER_ERROR 这个我也没办法... 安全问题非让我加... 下回改个更友好的提示吧…

**Comment by sanguineJohn** [comment]
好像还不是这个ERROR，是另外一个，忘了名字了，应该是存库失败报的错

**Comment by sanguineJohn** [comment]
要不我再试试？如果有问题了，就再请教一下您～～，我还是比较喜欢这个博客系统的～

**Comment by bpplpp** [comment]
你快回来 haha

**Comment by lizheming** [comment]
可以呀，有问题提 issue 就好了，我们的响应速度还是可以的~

**Comment by sanguineJohn** [comment]
响快赞。（这响应速度这么快，赞一个～）
