### ISSUE TITLE
1.0版本pm2启动服务报错。

### ISSUE THREAD

**Issue by HarlanZhang** [firekylin/firekylin#525]
1.0版本npm启动报错。

pm2日志：
[Error] package `on-finished` is not installed. please run `npm install` command before start server.

nodejs -v 8.11.1
npm -v 6.0.0

**Comment by ddhhz** [comment]
please run `npm install` command before start server.

**Comment by HarlanZhang** [comment]
@ddhhz npm install 执行过以后才启动服务的。

**Comment by ddhhz** [comment]
麻烦您看一下您目录下的 package.json 文件和 https://github.com/firekylin/firekylin/blob/1.0.3/package.json 是否一致。
然后目录下运行 `npm ls on-finished` 看看有否输出已安装的package版本。
如果还有问题试一下 `rm -rf node_modules/` 再重新 `npm install`。
如果还有问题可以试一下删除

**Comment by HarlanZhang** [comment]
好的，谢谢你！ 迁移的过程中出了些问题，已经解决了。
