### ISSUE TITLE
Firekylin图标用的什么图标库？

### ISSUE THREAD

**Issue by jellydong** [firekylin/firekylin#527]
在配置左侧链接的时候我希望有些自己的图标，比如上传，QQ，微博等icon，问一下Firekylin使用的什么图标库呢？

**Comment by wei** [comment]
#526 已经回答你了哈

**Comment by lizheming** [comment]
#526 说的是后台的图标库，前台的图标库用的是 iconfont ，你可以自己找下 css 文件，有个 icon.css 在 www/static/css 里。

**Comment by hiblacker** [comment]
目前都支持哪些图标呢？ 我想加个菜单，找不到对应的图标，建议增加一个 [iconfont](https://www.iconfont.cn) 图标库  方便自定义图标

**Comment by hiblacker** [comment]
现在我的方法是对照 `icon.css` 中的类名，重新在 iconfont 中组建图标库。。。
