### ISSUE TITLE
管理员问题

### ISSUE THREAD

**Issue by liuzhaoxu1996** [firekylin/firekylin#533]
登录管理员之后，管理员不能删除文章，添加文章等等，显示error，怎么办呢？

![image](https://user-images.githubusercontent.com/29271740/40267131-1fef2146-5b8a-11e8-99fe-cc42262378ca.png)

**Comment by lizheming** [comment]
#485
#481
#473

**Comment by lizheming** [comment]
@liuzhaoxu1996 你这个后台地址没有设置对，应该就直接是你的博客地址，不需要带上后面的路径。
