### ISSUE TITLE
1.0.4版本，点击标签选项后，无法跳转到选中标签下的页面，停留 在原页面

### ISSUE THREAD

**Issue by TimeLetter** [firekylin/firekylin#537]
测试连接：http://xin.tletters.com/tag/android  （已自行修复）

**Comment by opsarno** [comment]
+1 相同的现象。
https://fandenggui.com/tag/dns

**Comment by wei** [comment]
https://github.com/firekylin/firekylin/blob/07cf51d03993756f6c0b1eb5600c9cadebd4d571/src/home/controller/post.js#L70-L87

@lizheming 这里可以直接删掉替换成 `return this.displayView('index'); ` 吧？成功：https://blog.whe.me/tag/ubuntu

如果要主题定制 tag.html / cate.html 的话可能换个路径或者让 <site_url>/tags 使用 tags.html 避免冲突？

**Comment by lizheming** [comment]
我抽空再看一下吧，这块的逻辑正常来说没什么问题，当且仅当 `tag.html` 存在的时候才会使用 `tag.html` 模板渲染，否则还是用 `index.html`。

**Comment by wei** [comment]
@liuguanyu tag.html 存在呀 目前仅用于渲染 /tags 所以如果 /tag/:tagName 也用的话就冲突了

**Comment by lizheming** [comment]
@wei 哦，那就改成 `tagList.html` 和 `cateList.html` 吧。

**Comment by wei** [comment]
这个是 breaking change 呀 自定义主题的人要手动改文件名 可以的话我PR进来

**Comment by lizheming** [comment]
没关系，现在用这个的人比较少，加进来吧。把 `tag.html` 改成 `tags.html` 也比较 breaking....
