### ISSUE TITLE
建议——文章删除的时候能否只做逻辑删除？

### ISSUE THREAD

**Issue by Aucitron** [firekylin/firekylin#539]
发现现在是直接删除数据库数据。
right ,手抖删错就再回不来了。
后台顺势还可以做个文章回收站之类的

**Comment by wei** [comment]
感谢建议-
 - 需要临时隐藏的话可以改成非公开
 - 需要恢复误删文章的话应该去每日备份里取一下
确实应该配置成软删除，不过更应该有每日备份，这样别的数据丢失的情况都可以恢复

**Comment by lizheming** [comment]
感谢建议，我觉得这个建议挺好的。这个会列到后期的需求池里，不过目前这个的优先级不是很高，暂时不会做，所以还请按照 @wei 说的时常备份下数据比较靠谱一点。

**Comment by yaimeet** [comment]
还是直接二次开发大法好啊，顺便还能学学react，thinkjs。
