### ISSUE TITLE
关于文章推送的两个小bug

### ISSUE THREAD

**Issue by TimeLetter** [firekylin/firekylin#540]
1.A博客推送文章到B博客后，当A博客内容重新修改后，再次推送时B博客未做任何修改，原因可能是推送只做了插入操作，而无更新操作
2.A博客文章有封面图时，推送后B博客的文章无仍旧无封面图

**Comment by lizheming** [comment]
感谢反馈，已在 1.x 版本中修复，更新是因为有报错所以没更新上，封面图是后期增加的推送这块没同步上也已更新，请等待下次发版。
