### ISSUE TITLE
重装系统后下载最新的firekylin变得异常慢

### ISSUE THREAD

**Issue by rxy8023** [firekylin/firekylin#544]
博客地址：kaicloud.net

**Comment by rxy8023** [comment]
firekylin版本：FireKylin 1.0.4
node版本 9.1.1
mysql版本 5.6.40
直接拉的安装包安装

首屏居然20多s

**Comment by lizheming** [comment]
ttfb 时间特别长，重启下 node 试试，不行的话把 https://github.com/firekylin/firekylin/blob/master/src/common/config/middleware.js#L10-L11 这两行的 `isDev` 改成 `true` 看看页面的真实请求时间。
![image](https://user-images.githubusercontent.com/424491/41815434-6b3a809e-779d-11e8-882c-43d507a3cc69.png)

**Comment by rxy8023** [comment]
感谢回复，按照您说的修改了配置并重启还是相应很慢。昨天目测刚搭起来是正常的，但添加了一些文章后就开始变慢

**Comment by lizheming** [comment]
目测是 MySQL 查询太慢了导致的，我看了下你的输出，真实处理的时间就是这么慢。所以你把 https://github.com/firekylin/firekylin/blob/master/src/common/config/adapter/model.js#L24-L25 这两行的 `isDev` 也改成 `true`，访问一下页面，然后进入 `logs` 目录查看一下今天的日志看看 SQL 的查询时间是多久吧。

**Comment by rxy8023** [comment]
查看日志确实是mysql查询慢引起的，刚重新编译了mysql，问题还未解决0.0

**Comment by rxy8023** [comment]
mysql查的并不慢，语句之间的间隔时间比较长，执行完全部sql的大概6s左右

**Comment by rxy8023** [comment]
[2018-06-24T21:06:16.804] [INFO] default - SQL: SELECT * FROM `fk_post` LEFT JOIN `fk_post_cate` AS `cate` ON `fk_post`.`id` = `cate`.`post_id` WHERE ( cate.cate_id = 4 ) AND ( `is_public` = 1 ) AND ( `type` = 0 ) AND ( `status` = 3 ) AND ( `create_time` <= '2018-06-24 21:06:15' ) ORDER BY create_time DESC LIMIT 0,10, Time: 1117ms
才发现这一句

**Comment by lizheming** [comment]
你把这句话粘贴到 MySQL 中直接执行看一下时间是多少？这句话本身并没有什么问题，我在本地测了一下也挺快的 9ms 280条记录查出来了。

**Comment by wei** [comment]
closed for inactivity
