### ISSUE TITLE
后台页面打不开,提示 Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by chaohui2** [firekylin/firekylin#546]
![image](https://user-images.githubusercontent.com/17821872/41927065-abb51dca-79a3-11e8-9040-37a7e422465a.png)
![image](https://user-images.githubusercontent.com/17821872/41927123-dc25dd00-79a3-11e8-9601-f58c7ab576c9.png)

cnpm@6.0.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.1.0 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@10.5.0 (/usr/lib/nodejs/bin/node)
npminstall@3.6.2 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/lib/nodejs
linux x64 4.4.0-43-Microsoft
registry=https://registry.npm.taobao.org

安装包地址:https://github.com/firekylin/firekylin/archive/1.1.0.zip
启动方式:  sudo node production.js

**Comment by ChaoHui123** [comment]
主页可以访问,我安装的时候使用的是cnpm,其中有个依赖是sqlite的,一直403,我就把依赖移除了,
/src/common/config/adapter/model.js, 这个文件引用到了sqlite ,所以我修改了这个文件,不知道有没有影响

**Comment by haima2** [comment]
应该是修改文件的锅吧，等等官方出修复版本吧

**Comment by lizheming** [comment]
出现这个问题一般是用仓库版自行 webpack 编译有点问题导致的，建议直接使用编译好的安装版解决这个问题 https://firekylin.org/release/v1/latest.tar.gz

**Comment by Easy-Martin** [comment]
编译好的也有问题

**Comment by He--He** [comment]
可能是这个原因：react-bootstrap在v0.29.0版本中做出的一个breaking change：

> Rewrite form and form control API (`<FormControl>`, &c.), and deprecate the old API (`<Input>`, &c.) 

而依赖于此的react-bootstrap-validation似乎已经停止维护，没有做出相应修改： [Uncaught TypeError: Super expression must either be null or a function, not undefined #70](https://github.com/heilhead/react-bootstrap-validation/issues/70)

所以可以尝试修改package.json中的`"react-bootstrap": "^0.28.3"`至`"react-bootstrap": "~0.28.3"`，再用最新版本的npm安装避免此问题。

但因为react-bootstrap-validation中的依赖被写为`"react-bootstrap": ">=0.23.0"`，所以如果用yarn进行安装，需再添加`"resolutions": { "react-bootstrap-validation/react-bootstrap": "~0.28.4" }`，用cnpm的话手动修改下目录链接吧。

**Comment by wei** [comment]
closed for inactivity
