### ISSUE TITLE
ununtu16 部署遇到问题,mysql是5.7

### ISSUE THREAD

**Issue by qiubiteme** [firekylin/firekylin#548]
按照配置,设置后,在这孩子账号页面,报下面错误
Firekylin - 系统安装
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by wei** [comment]
直接命令行mysql连得上吗

**Comment by qiubiteme** [comment]
命令行可以,

**Comment by wei** [comment]
目测是这个问题：https://github.com/mysqljs/mysql/issues/1574

可以用root账号登录 mysql，然后运行
```
use mysql;
select User, plugin from user where User = '<用户名>'
```
查看，如果 plugin 是旧版的就得按照网上教程更新。

**Comment by wei** [comment]
closed for inactivity
