### ISSUE TITLE
markdown导入bug

### ISSUE THREAD

**Issue by Jarvis-Q** [firekylin/firekylin#549]
markdown导入bug. markdown service模块并没有被正常输出

bug代码地址: 
[`/src/admin/service/import/markdown.js`](https://github.com/firekylin/firekylin/blob/26cb9003dea720ca451ee35a8d99c9849a518bfa/src/admin/service/import/markdown.js#L7)
```js
module.epxorts = class extends Base {
  constructor(think) {
    super(think);
    this._think = think;
  }
  ...
}
```

`exports`被错误的书写为`epxorts`. 

额外补充: 

上传时因为是通过动态的调用service, 词法分析阶段有可能无法被发现。应用运行时虽然做了try/catch，但无法捕捉到准确错误，没有相关日志，暂时没有排查其他服务(service)是否存在同样情况？

```js
// service == 'markdown'
think.service(`import/${service}`, 'admin', this)
```
> note:  `v1.1.1 安装版`中发现该bug, 相关issue中未发现该问题。

**Comment by lizheming** [comment]
感谢指出，笔误已修改。不把 try...catch 的错误报出来当时考虑的是部分导入成功的情况下如果报错可能会影响后续流程（其实就是没有事务的锅），所以当时只是在控制台输出了方便排查问题。
