### ISSUE TITLE
CentOS 安装版部署出错  MySQL8.0

### ISSUE THREAD

**Issue by LittleCoder1991** [firekylin/firekylin#553]
请问安装界面报数据库出错怎么回事?确定账号密码没有问题，本地mysqlbench可以连接上

**Comment by wei** [comment]
有输出吗 确认不是 #548 的问题吗

**Comment by wei** [comment]
还有就是本地连接有啥用  要运行firekylin的服务器上测试连接

**Comment by LittleCoder1991** [comment]
mysql8.0 版本问题  使用你们默认的mysql5.6就好了

**Comment by lizheming** [comment]
MySQL 8 使用了新的认证加密方式，目前底层的 `node-mysql` 驱动器模块还不支持，解决办法是切换 MySQL 8 的认证加密方式即可，详见： https://stackoverflow.com/questions/50373427/node-js-cant-authenticate-to-mysql-8-0
