### ISSUE TITLE
FireKylin 1.1.1 如何配置404页面？

### ISSUE THREAD

**Issue by supervergil** [firekylin/firekylin#554]
MySQL版本：5.6.41
ThinkJS版本：3.2.8
FireKylin版本：1.1.1

请问FireKylin 1.1.1版本如何配置404页面？

**Comment by lizheming** [comment]
新版的话现在应该还不行，我周末加一下。

**Comment by lizheming** [comment]
加好了，在主题下新建 `error/404.html` 文件即可，例如 ``www/theme/firekylin/error/404.html`，敬请期待下一次发版。
