### ISSUE TITLE
后台进不去啥原因呢

### ISSUE THREAD

**Issue by yuexiaoliang** [firekylin/firekylin#558]
安装完了，网站是可以进去了 ，  但是进后台的时候会跳转到`/admin/dashboard`这个链接，页面上什么都没有，一片灰色，是我哪里搞错了么。
[http://www.mobai.pro/admin](http://www.mobai.pro/admin)
哪位大佬帮忙看看，上边是后台地址

**Comment by yuexiaoliang** [comment]
研究出来了，哈哈。把服务器重装了一下...   然后就好了，也不知道问题出在哪 @wei

**Comment by wei** [comment]
好
