### ISSUE TITLE
求教文章的封面图片怎么用

### ISSUE THREAD

**Issue by yuexiaoliang** [firekylin/firekylin#559]
嘎嘎嘎， 我又来了，捣鼓了一晚上...    现在遇到了新问题，文章里边的封面图片能单独调用么？ 我想在前台调用个缩略图

**Comment by yuexiaoliang** [comment]
可调用的属性名在哪里能找到???  大佬们，

**Comment by wei** [comment]
主题里 post.html 可使用 post.featuredImage 输出。如需js调用，可输出一个 script 标签，里面定义一个变量=post.featuredImage
