### ISSUE TITLE
cpp highlight doesn't work

### ISSUE THREAD

**Issue by Sothan** [firekylin/firekylin#560]
It's pretty strange to find cpp highlight doesn't work when my code contains:
`
Complex wn(cos(-op * 2 * PI / h), sin(-op * 2 * PI / h));
`
However, it works when I use the following implementation:
`
double real = cos(-op * 2 * PI / h), imag = sin(-op * 2 * PI / h);
Complex wn(real, imag);
`
As you see, 
![image](https://user-images.githubusercontent.com/38458025/44306730-423e5200-a3c7-11e8-9e4f-7224de63800b.png)

**Comment by lizheming** [comment]
We use highlight.js to higlight code. It seems older code's language feature not obvious rather than newer, then higilight.js detect language failed. There has no better way to resolve it, maybe you can write more feature code to fix it. Thank you for your issue.
