### ISSUE TITLE
请教下怎么单独调取某个分类下文章

### ISSUE THREAD

**Issue by yuexiaoliang** [firekylin/firekylin#562]
大佬们，我在后台建了几个分类，然后建了一个页面，想单独调取其中一个分类的文章可以吗？

**Comment by lizheming** [comment]
那不就是 [http://blogs.360.cn/cate/漏洞分析](http://blogs.360.cn/cate/%E6%BC%8F%E6%B4%9E%E5%88%86%E6%9E%90) 分类详情页么？

**Comment by xiaojinzi123** [comment]
> 大佬们，我在后台建了几个分类，然后建了一个页面，想单独调取其中一个分类的文章可以吗？

你新建一个页面(注意不是文章),然后在右侧选择模板为 cates_list,点击发布,然后在菜单管理中把这个页面配置到导航的左侧,分类页面就做出来了

**Comment by wei** [comment]
closed for inactivity
