### ISSUE TITLE
这里的console里有个error：https://firekylin.org/themes

### ISSUE THREAD

**Issue by medmin** [firekylin/firekylin#563]
请修复一下

另外，请问哪里可以看到其他主题？谢谢

**Comment by lizheming** [comment]
官方主题市场年久失修，之后会进行重构，先忽略吧。目前主题还比较少，我暂时先用 WiKi 罗列一下吧
https://github.com/firekylin/firekylin/wiki/%E4%B8%BB%E9%A2%98%E5%88%97%E8%A1%A8
