### ISSUE TITLE
请问ACCOUNT_ERROR是怎么回事

### ISSUE THREAD

**Issue by yuexiaoliang** [firekylin/firekylin#565]
昨天用的时候，清了一下浏览器缓存，然后重新登录的时候就提示ACCOUNT_ERROR，后来我重新安装了一下，装完以后登录的时候也总是提示  ACCOUNT_ERROR ，我怕是我装的时候密码输错了，又装了大概有3-4次不管怎么装都会提示这个。

**Comment by lizheming** [comment]
有可能用户名输错了，另外用户名不是邮箱。

**Comment by yuexiaoliang** [comment]
@lizheming    用户名我没改  admin     密码我已经设置成了12345678   一个字一个字输入的

**Comment by lizheming** [comment]
有地址么，我也试试。账号密码验证还没有人报过这种问题，我这边也不好排查。

**Comment by yuexiaoliang** [comment]
@lizheming   我刚刚装了  1.1.1   版本 ， 成功了。  然后在线升级了下 1.1.2 ， 然后退出登录，重新登录的时候，后台刷不出来了。不知道是我电脑的原因还是怎么还是，http://39.105.49.179:8360/admin

**Comment by lizheming** [comment]
先用 1.1.1 吧，最新这个版有点问题，下午再修一下

**Comment by yuexiaoliang** [comment]
@lizheming   好的，谢谢
