### ISSUE TITLE
在线升级以后的后台空白

### ISSUE THREAD

**Issue by bpplpp** [firekylin/firekylin#566]
本来1.1.0升级1.1.1就是空白，后来干脆不敢升级了。看到1.1.2还是一样，已尝试删除runtime，前台正常。

![image](https://user-images.githubusercontent.com/15948273/44634889-e6c92100-a9d1-11e8-9fbc-f42d0d1299c5.png)

**Comment by lizheming** [comment]
浏览器版本多少，给个在线地址我去看看

**Comment by bpplpp** [comment]
Chrome 68.0.3440.106 已经回1.1.0

**Comment by lizheming** [comment]
给个在线地址我去看看吧，我这边同版本没办法复现这个问题

**Comment by bpplpp** [comment]
https://bpplpp.com/

**Comment by bpplpp** [comment]
你在线的，那我可以花点时间复现下问题

**Comment by lizheming** [comment]
嗯，你给的地址是 1.0.4 版本的，给一个有问题的版本的吧，thx~

**Comment by bpplpp** [comment]
我就这个了，我先去后台在线升级

**Comment by bpplpp** [comment]
![image](https://user-images.githubusercontent.com/15948273/44661720-1e6db280-aa3e-11e8-8d3a-71a8d04ad411.png)

可以了，后台白屏

**Comment by lizheming** [comment]
清下缓存，我这边是 OK 的

**Comment by bpplpp** [comment]
runtime？

**Comment by lizheming** [comment]
浏览器缓存

**Comment by bpplpp** [comment]
ok 原来Ctrl+F5就行了

**Comment by lizheming** [comment]
OK
