### ISSUE TITLE
Gitalk 配置后不生效

### ISSUE THREAD

**Issue by ringcrl** [firekylin/firekylin#567]
按照如图所示填入了配置项 json，但是填入的内容直接在页面上显示出来了，https://chenng.cc

<img width="771" alt="wx20180828-230542 2x" src="https://user-images.githubusercontent.com/16740021/44733109-7200fe80-ab19-11e8-9fd6-7e2f3ca0dc09.png">

**Comment by lizheming** [comment]
你是手动覆盖文件升级的么？发现你有部分文件不是最新的，和对应的版本匹配不上。

![image](https://user-images.githubusercontent.com/424491/44767849-09a23380-ab92-11e8-9b42-93f01db45ed8.png)
缺少下面的这部分内容：https://github.com/firekylin/firekylin/blob/0.15.18/www/theme/firekylin/res/js/firekylin.js#L88-L90

请尝试更新相关文件或者直接升级到最新版 1.x 来解决，0.x 升级到 1.x 的文档见 https://github.com/firekylin/firekylin/wiki/0.x%E5%8D%87%E7%BA%A7%E8%87%B31.x

**Comment by lizheming** [comment]
数据库配置出问题了，检查下自己的 db 配置吧

**Comment by ringcrl** [comment]
![image](https://user-images.githubusercontent.com/16740021/44849252-1c009800-ac8c-11e8-829b-27aecbc056af.png)

额，不好意思，数据库连上了，可是报了一些其他错误。。

**Comment by wei** [comment]
JSON格式不对  你validate一下

**Comment by ringcrl** [comment]
修复了，博客复活了，谢谢各位
