### ISSUE TITLE
通过admin修改的密码，登录不成功

### ISSUE THREAD

**Issue by suikelei** [firekylin/firekylin#568]
1、通过admin修改某个用户密码
2、这个用户用密码登录不成功
3、这个用户，找回密码，重新设置，登录成功

**Comment by lizheming** [comment]
本地测试未能复现你的问题，查看了代码也没发现你说的问题，请确认自己的操作没有问题吧。

**Comment by suikelei** [comment]
重新安装发现问题了。
通过 https://firekylin.org/release/v1/latest.tar.gz 安装， 密码没问题
通过 https://github.com/firekylin/firekylin/releases/download/1.1.2/firekylin_1.1.2.tar.gz 安装，密码有问题

**Comment by zsakvo** [comment]
同  我也是有这个问题，通过https://github.com/firekylin/firekylin/releases/download/1.1.2/firekylin_1.1.2.tar.gz安装，登入后台的时候会出错（ account error ），但是通过https://firekylin.org/release/v1/latest.tar.gz 安装则没有问题。
node版本8.12.0，mysql版本为8.0.12

**Comment by lizheming** [comment]
感谢反馈，我试了下的确 Github Release 的版本 md5 是不一样的。当时应该是发布完 1.1.2 之后发现了一个问题，重新打包更新了 1.1.2 的版本，firekylin.org 下载源的更新了结果 Github Release 忘记同步上来了，抱歉抱歉。已经重新上传了一份，给你们带来麻烦了真是不好意思，最后感谢你们的反馈。
