### ISSUE TITLE
安装后生成的文章里面，有个基本设置的按钮点了之后跳不过去

### ISSUE THREAD

**Issue by CrazyLifeCrazyFun** [firekylin/firekylin#569]
安装后生成的文章里面，有个基本设置的按钮点了之后跳不过去，提示是：
{"errno":404,"errmsg":"url `/post/admin/options/general` not found."}

**Comment by CrazyLifeCrazyFun** [comment]
用的是安装版，版本是1.1.1

**Comment by lizheming** [comment]
是 `/admin/options/general` 你是不是地址写错了

**Comment by CrazyLifeCrazyFun** [comment]
这个地址不是我写的，我点文章里面的按钮，跳过去就这样了

**Comment by lizheming** [comment]
具体是什么按钮

**Comment by CrazyLifeCrazyFun** [comment]
”基本设置“  这个按钮

**Comment by CrazyLifeCrazyFun** [comment]
![qq 20180830175150](https://user-images.githubusercontent.com/13356873/44844453-9118a100-ac7d-11e8-9d9c-b11106584289.png)

**Comment by lizheming** [comment]
算了你还是给个截图吧。。。。你这么描述根本不清楚在哪里。。。

**Comment by lizheming** [comment]
原来是这里啊。。。这篇文章是用户帮忙写的之前没具体检查内容。已经修复了，谢谢反馈。

**Comment by CrazyLifeCrazyFun** [comment]
嗯，修复就好，萌新只能提提问题了

**Comment by lizheming** [comment]
好的，有问题继续反馈，谢谢~
