### ISSUE TITLE
希望增加登录cookies保持时间的选项

### ISSUE THREAD

**Issue by fz568573448** [firekylin/firekylin#571]
如果要经常写东西的话，默认一天是不是有点短了？最好能有个永不过期的选项，这样比较方便。反正选择权在用户手里，也不存在安全的问题。

**Comment by lizheming** [comment]
OwQ 好的，其实讲道理有 Chrome 的记住密码我都没有纠结过这个问题...

**Comment by fz568573448** [comment]
这不是不想多点那一下嘛

**Comment by lizheming** [comment]
后台登录已增加了一个自动登录的选项，可以延时成1年 https://github.com/firekylin/firekylin/commit/7bd605e74f87ed319364189cb9cae00a760acd52
