### ISSUE TITLE
怎么提高渲染速度

### ISSUE THREAD

**Issue by zxysilent** [firekylin/firekylin#575]
![image](https://user-images.githubusercontent.com/19162822/46739498-44d86c00-ccd3-11e8-8373-39f2de809fec.png)

![image](https://user-images.githubusercontent.com/19162822/46739549-5d488680-ccd3-11e8-85d9-14be103aee7a.png)

**Comment by wei** [comment]
推荐配置 nginx 缓存。

**Comment by lizheming** [comment]
TTFB 时间长表示的是服务端相应处理返回的时间较长，你可以把代码里这块 https://github.com/firekylin/firekylin/blob/master/src/common/config/adapter/model.js#L24 修改成 `logger: true` 然后查看下 `logs` 文件夹下的日志看一下请求对应的每条 SQL 的执行时间是多少。

**Comment by wei** [comment]
closed for inactivity
