### ISSUE TITLE
Submit the result REFERRER_ERROR

### ISSUE THREAD

**Issue by SCsunyuan** [firekylin/firekylin#578]
Unable to save any behavior, site_url is consistent with the background setting UR L. System environment centOS 7.3, NodeJS version 8.12.0
![image](https://user-images.githubusercontent.com/16719884/46903551-4c815600-cf09-11e8-9f4b-db842ca24cc0.png)

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/issues/485
