### ISSUE TITLE
自定义js后管理界面登录不上

### ISSUE THREAD

**Issue by hz1995** [firekylin/firekylin#580]
在写入自定义js后管理界面就登录上去了，想将这js删除
web显示：
\"}","title":"腹黑的猪","twitter_url":"","two_factor_auth":false,"upload":{"type":"smms"}}, };

**Comment by lizheming** [comment]
应该是 nunjucks 转义没转好，目前只能去数据库里删除了。

**Comment by lizheming** [comment]
最新版已修复这个问题，请及时更新，感谢反馈。
