### ISSUE TITLE
有没有简单的办法能将发布到github上的notebook嵌入在blog里

### ISSUE THREAD

**Issue by brightgems** [firekylin/firekylin#581]
如题：有没有简单的办法能将发布到github上的notebook嵌入在blog里?

**Comment by wei** [comment]
Gist吗？embed code粘贴到正文里就行

**Comment by brightgems** [comment]
比如说下面的网页能嵌入吗，iframe?

http://nbviewer.jupyter.org/github/Azure/Azure-Data-Service-Notebook/blob/master/adlmagics/01_usql_samples.ipynb

**Comment by wei** [comment]
markdown支持所有html代码 iframe也可行
