### ISSUE TITLE
后台无法进入，显示空白

### ISSUE THREAD

**Issue by Lopins** [firekylin/firekylin#583]
![image](https://user-images.githubusercontent.com/44494732/47556484-fd8fe380-d940-11e8-8ac6-528f02f6b365.png)
![image](https://user-images.githubusercontent.com/44494732/47556619-64ad9800-d941-11e8-9660-caed67fd9169.png)

安装过后，前台正常，后台空白，请问是否配置有问题还是其他问题
运行环境：centosv7.3  alisql   nodev8.12.0 mysqlv2.16.0 npmv6.4.1 pm2v3.2.2

**Comment by Lopins** [comment]
请问是否能出一份宝塔面板下的配置教程

**Comment by lizheming** [comment]
Chrome 打开控制台看一下静态资源是否有加载上

**Comment by qianfeiqianlan** [comment]
检查一下www/static/js/admin.js  有没有这个js  我是下载1.2.2 release的包，解开以后发现没有这个.

**Comment by guandaxia** [comment]
![image](https://user-images.githubusercontent.com/9638813/48329908-ac445b80-e685-11e8-9285-7809c75b1a5b.png)
我是在线升级的1.2.2版本之后，存在这个问题

js文件加载都没有问题

![image](https://user-images.githubusercontent.com/9638813/48329936-c8e09380-e685-11e8-9b28-43fd6a88d433.png)

**Comment by lizheming** [comment]
@guandaxia 你这个是 nunjucks 转义有问题，和他们的不太一样，发一下地址我们看看。

**Comment by guandaxia** [comment]
@lizheming  地址：http://guansixu.cn/admin， 登录没有问题

**Comment by lizheming** [comment]
@guandaxia 应该是访问统计的代码的转义有问题了，你要急的话就自己上数据库把数据清一下，然后删除项目根目录下的 runtime 文件夹重启服务就行。不急的话我们之后修一下你更新到新版就行。

```sql
UPDATE `fk_options` SET `value` = '' WHERE `key` = 'analyze_code' ;
```

**Comment by guandaxia** [comment]
@lizheming 好的，我试试

**Comment by Xonlystar** [comment]
我后台也空白，打开控制台发现报错
![image](https://user-images.githubusercontent.com/19361551/48657576-db840f80-ea6d-11e8-9dfc-a1566c4ebc28.png)

**Comment by lizheming** [comment]
@Xonlystar 您这个试着清下浏览器缓存试试？

**Comment by lizheming** [comment]
@guandaxia 最新版已修复这个问题，感谢反馈。
