### ISSUE TITLE
管理页面要加8360端口问题

### ISSUE THREAD

**Issue by zjpwang** [firekylin/firekylin#590]
前台地址不加8360显示不正常
![image](https://user-images.githubusercontent.com/43128887/48041151-e8c01500-e1b6-11e8-9a40-bf9dc857b97d.png)
后台地址不加8360无法显示

版本：FireKylin 0.15.18

**Comment by wei** [comment]
是 nginx 反代配置问题。

**Comment by lizheming** [comment]
贴一下你的 nginx 配置，注意一下 `root` 是要指定到 `www` 目录的 https://github.com/firekylin/firekylin/blob/master/nginx.conf#L4

**Comment by wei** [comment]
closed for inactivity
