### ISSUE TITLE
添加Gitalk评论帮助文档

### ISSUE THREAD

**Issue by opsarno** [firekylin/firekylin#594]
# 配置前准备
- Github 账号
- 创建 Repositorie 仓库用于评论系统
  - 评论内容会自动在仓库的Issue中生成
- 创建 OAuth Apps [点击创建](https://github.com/settings/applications/new)，
简要说明创建OAuth需要填写的内容：
  - Application name：应用的名字随便起，我定义的是`blog`
  - Homepage URL：填写你的博客域名
  - Application description：可选描述，可留空。
  - Authorization callback URL：填写你的博客域名

创建完OAuth Apps，就得到了 Client ID & Client Secret
 

# FireKylin 后台配置
登录博客后台--->系统设置--->评论设置，评论类型选择`Gitalk`，评论代码写入配置模板内容，相关的信息请酌情自行修改。

配置模板
```bash
{
    "clientID": "your_id",
    "clientSecret": "your_secret",
    "repo": "your_repositorie_name",
    "owner": "your_github_username",
    "admin": [
        "your_github_username"
    ],
    "distractionFreeMode": true,
    "githubUserName": "your_github_username",
    "githubPassWord": "your_github_password"
}
```

建议添加到WIKI中。
来源：https://fandenggui.com/post/firekylin_integration_gitalk_comment.html

**Comment by lizheming** [comment]
感谢补充，已更新到 WIKI https://github.com/firekylin/firekylin/wiki/%E6%B7%BB%E5%8A%A0%E8%AF%84%E8%AE%BA
