### ISSUE TITLE
导入md文件失败

### ISSUE THREAD

**Issue by Dangerxfh** [firekylin/firekylin#597]
我把所有md文件放到文件夹中，打包成tar.gz，上传抱import fail

**Comment by lizheming** [comment]
把 tar 包发一下吧，我们试试。

**Comment by Dangerxfh** [comment]
> 把 tar 包发一下吧，我们试试。

已经发到邮箱了

**Comment by Dangerxfh** [comment]
@lizheming

**Comment by lizheming** [comment]
打包不要带文件夹，直接都是 `.md` 即可。

**Comment by Dangerxfh** [comment]
@lizheming
您能直接将打包好的文件给我试下吗

**Comment by lizheming** [comment]
你就直接把 md 文件夹去掉就好了，打包逻辑大概是

```
tar cvf md.tar.gz ./*.md
```

**Comment by Dangerxfh** [comment]
还是不行，显示上传中，过了几秒，还是import fail
@lizheming

**Comment by lizheming** [comment]
看看终端有什么报错

**Comment by Dangerxfh** [comment]
怎么看

**Comment by Dangerxfh** [comment]
@lizheming

**Comment by Dangerxfh** [comment]
日志在哪

**Comment by Dangerxfh** [comment]
报的错：
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
@lizheming
