### ISSUE TITLE
配置https一直失败，提示403

### ISSUE THREAD

**Issue by MOOOWOOO** [firekylin/firekylin#601]
运行环境：vultr 主机 Ubuntu 18.04 x64，root 用户， DNS 配置到了 namecheap 的 FreeDNS
执行 https.sh（包括网上其他教程中的脚本），每次到最后都显示如下报错：

`检测 openssl 成功
检测 python 成功
Parsing account key...
Parsing CSR...
Found domains: www.pycode.cc, pycode.cc
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying pycode.cc...
Traceback (most recent call last):
  File "acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme_tiny.py", line 144, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to ./challenges/rGZC17sNS7ZDkVmhmED14id8-EHnxYVOy37sv3vrv1E, but couldn't download http://pycode.cc/.well-known/acme-challenge/rGZC17sNS7ZDkVmhmED14id8-EHnxYVOy37sv3vrv1E: Error:
Url: http://pycode.cc/.well-known/acme-challenge/rGZC17sNS7ZDkVmhmED14id8-EHnxYVOy37sv3vrv1E
Data: None
Response Code: 403
Response: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>`

Nginx.conf 文件内容如下：

`server {
    listen 80;
    server_name pycode.cc www.pycode.cc;
    root /root/firekylin/www/;
    set $node_port 8360;

    index index.js index.html index.htm;

    location ^~ /.well-known/acme-challenge/ {
      alias /root/firekylin/ssl/challenges/;
      try_files $uri = 404;
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

    location = /development.js {
        deny all;
    }
    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
    }

    location ~ /static/ {
        etag         on;
        expires      max;
    }
}

#https nginx conf

server{
    listen 443;
    server_name pycode.cc www.pycode.cc;
    root /root/firekylin/www;
    set $node_port 8360;

    ssl on;
    ssl_certificate  /root/firekylin/ssl/chained.pem;
    ssl_certificate_key /root/firekylin/ssl/domain.key;

    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DAES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SH
    ssl_session_cache shared:SSL:50m;
    ssl_dhparam /root/firekylin/ssl/dhparams.pem;
    ssl_prefer_server_ciphers on;

    index index.js index.html index.htm;

    location ^~ /.well-known/acme-challenge/ {
      alias /root/firekylin/ssl/challenges/;
      try_files $uri = 404;
    }

   location / {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

    location = /development.js {
        deny all;
    }

    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
   }

   location ~ /static/ {
      etag         on;
      expires      max;
   }
}
server {
    listen 80;
    server_name pycode.cc www.pycode.cc;
    rewrite ^(.*) https://pycode.cc$1 permanent;
}`

**Comment by lizheming** [comment]
403 错误的话一般是权限问题，你把 nginx 的运行用户改成 root 试一下。

**Comment by MOOOWOOO** [comment]
> 
> 
> 403 错误的话一般是权限问题，你把 nginx 的运行用户改成 root 试一下。

我本身就是root用户配置的，应该不是这个问题

**Comment by lizheming** [comment]
nginx 默认启动是 `www-data` 用户，自己打开 `/etc/nginx/nginx.conf` （或者是 `/usr/local/nginx/nginx.conf`）看一下。

**Comment by MOOOWOOO** [comment]
> 
> 
> nginx 默认启动是 `www-data` 用户，自己打开 `/etc/nginx/nginx.conf` （或者是 `/usr/local/nginx/nginx.conf`）看一下。

用 root 用户的话，重启 nginx 会失败，错误信息提示：
`Dec 05 02:57:39 vultr.guest systemd[1]: Starting A high performance web server and a reverse proxy server...
Dec 05 02:57:39 vultr.guest nginx[12674]: nginx: [emerg] SSL_CTX_use_PrivateKey_file("/root/firekylin/ssl/domain.key") failed (SSL: error:0B080074:x50
Dec 05 02:57:39 vultr.guest nginx[12674]: nginx: configuration file /etc/nginx/nginx.conf test failed
`

**Comment by MOOOWOOO** [comment]
已解决，方法如下：

1.  将 /etc/nginx/site-enabled 中自己的 conf 文件中，https 部分全部注释

2. 修改 /etc/nginx/nginx.conf 中 user www-data; 为 user root;

3. systemctl restart nginx

4. 运行 sh https.sh domain.xx www.domain.xx 自动配置 https

5. 第4步成功后，解除第一步中注释的内容

6. systemctl restart nginx
