### ISSUE TITLE
.md 文件正常打包成 tar.gz，上传提示失败

### ISSUE THREAD

**Issue by MOOOWOOO** [firekylin/firekylin#602]
如题，ubuntu 下使用 `tar cvf md.tar.gz *.md` 将所有 markdown 文件打包，上传提示失败，logs 文件夹内 app.* 文件内容无变化

**Comment by Dangerxfh** [comment]
我的是报这个错，@lizheming
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by Dangerxfh** [comment]
好使了
直接用这个命令
tar -zcvf md.tar.gz *.md 
@MOOOWOOO

**Comment by lizheming** [comment]
是的，需要加 `-z` 参数表示 gzip 压缩，目前是只解析 `tar.gz` 格式的包了。
