### ISSUE TITLE
1.2.2版nginx.conf配置文件错误

### ISSUE THREAD

**Issue by locbytes** [firekylin/firekylin#603]
资源文件目录static没动过，nginx版本1.14.1。
以下是nginx.conf里的资源文件路径的默认配置
```
location ~ /static/ {
    etag          on;
    expires      max;
}
```
使用该默认配置会造成静态资源文件全部404无法访问，注释之后即可正常访问。

**Comment by wei** [comment]
目测这一行没有改成你服务器上对应的目录

https://github.com/firekylin/firekylin/blob/5a0ba4164b2059e6d376e59b6185e0c26a023c6b/nginx.conf#L4

**Comment by locbytes** [comment]
> 目测这一行没有改成你服务器上对应的目录
> 
> [firekylin/nginx.conf](https://github.com/firekylin/firekylin/blob/5a0ba4164b2059e6d376e59b6185e0c26a023c6b/nginx.conf#L4)
> 
> Line 4 in [5a0ba41](/firekylin/firekylin/commit/5a0ba4164b2059e6d376e59b6185e0c26a023c6b)
> 
>  root /Users/welefen/Develop/git/firekylin/www;

修改了的，我是严格按照配置教程一步一步来的。

**Comment by wei** [comment]
请确认那一行为 `/www` 结尾。

**Comment by locbytes** [comment]
好的我明白了...
我的firekylin安装路径：/data/wwwroot/www/
加www之后正确的路径：/data/wwwroot/www/www/
谢谢解答。

**Comment by wei** [comment]
没问题！
