### ISSUE TITLE
升级后，版本号没有变，依旧是V1.1.2

### ISSUE THREAD

**Issue by SAHX** [firekylin/firekylin#606]
如题目：升级后，版本号没有变，依旧是V1.1.2

**Comment by lizheming** [comment]
在线更新有可能没重启成功，可以尝试再重启下或者再重试更新一下。

**Comment by SAHX** [comment]
@lizheming 谢谢，确实是在线更新的，重启后版本号就变了。如果不用重启也能同步，岂不更好，:smile:

**Comment by lizheming** [comment]
有做重启的操作，可能重启失败了。
