### ISSUE TITLE
怎样上传文件到腾讯COS？

### ISSUE THREAD

**Issue by ilouiss** [firekylin/firekylin#608]
我看更新日志中上个版本就已经支持了，但是后台管理中的“上传设置”中并没有 COS 的选项，那么这个上传到 COS 该怎么设置

**Comment by lizheming** [comment]
1.2.0 的版本里有个前端重构，可能在重构的时候前端这块漏掉了。@colordove 你参考下这个 PR https://github.com/firekylin/firekylin/pull/584/files 补一下吧。

**Comment by lizheming** [comment]
#610 已添加，谢谢反馈，请等待下一次发版。
