### ISSUE TITLE
1.2.3 上传文件到腾讯 COS 失败

### ISSUE THREAD

**Issue by ilouiss** [firekylin/firekylin#611]
如题，已经更新到新版
nodejs 版本为 v11.6.0

上传时出现以下错误
![image](https://user-images.githubusercontent.com/37164399/50936777-09089a80-14ac-11e9-903e-5eabbb272770.png)

以下是 COS 配置
![image](https://user-images.githubusercontent.com/37164399/50936874-6bfa3180-14ac-11e9-9884-0cd7964b70ed.png)

请求解答。

**Comment by lizheming** [comment]
我们有空试一下，你先暂时手工上传下吧，下个版本修。

**Comment by lizheming** [comment]
怎么把 issue 关了，是问题解决了么？

**Comment by ilouiss** [comment]
@lizheming 没有，既然下个版本修复那这个问题也算是暂时解决了。

**Comment by lizheming** [comment]
好的，暂时先开着吧，关了我到时候就记不住了 😄

**Comment by ilouiss** [comment]
@lizheming 浏览器返回的错误如图
![ew7q wwye639ep 0ez5 ln1](https://user-images.githubusercontent.com/37164399/51091799-6f522d80-17ca-11e9-96be-1a46f1f49e61.png)

Firekylin的logs中就一个 
[2019-01-14T06:58:26.176] [INFO] default - NORMAL VERIFY TYPE

Nginx 中也没有error，下面是 access 中的日志
120.xxx.78.xx - - [14/Jan/2019:07:01:16 +0800] "POST /admin/api/file HTTP/2.0" 200 69 "https://blog.ilouis.cn/admin/post/create" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

**Comment by ilouiss** [comment]
我用的安装包版本安装的

**Comment by lizheming** [comment]
有用 PM2 的话 `pm2 logs` 看一下？应该有一个 `console.log` 的输出的

**Comment by lizheming** [comment]
感谢，原来是依赖库升级导致的不兼容，已修复。
