### ISSUE TITLE
1.x 版本 admin 登录页获取不到 favicon_url，只能显示默认 icon

### ISSUE THREAD

**Issue by MuyePeikon** [firekylin/firekylin#618]
仅登录页，登录成功后能正常获取。
开隐身模式看到最开始是能获取到正确的 icon 的，但一瞬间就被默认的 icon 替换了。。
摸索了半天，没看懂整个项目流程，心酸。。直接提 Issue 了。

**Comment by lizheming** [comment]
地址发一下，icon 前台是这句话控制的 https://github.com/firekylin/firekylin/blob/master/www/theme/firekylin/layout.html#L7

**Comment by MuyePeikon** [comment]
http://peikon.cf/admin/login （一篇文章都没有。。其实不好意思发出来的

**Comment by wei** [comment]
![image](https://user-images.githubusercontent.com/5880908/51462921-d5413680-1d2f-11e9-8346-25115ec9a9dd.png)

https://github.com/firekylin/firekylin/blob/9cbc6f0e78eae09929817ba64ad5f6f4090bec38/src/admin/controller/base.js#L39-L47

这里加一个 `favicon_icon: options.favicon_icon`

不然 

https://github.com/firekylin/firekylin/blob/9cbc6f0e78eae09929817ba64ad5f6f4090bec38/view/admin/index_index.html#L8

抓不到值。
