### ISSUE TITLE
我在heroku部署安装成功后过一段时间打开网站又让重新安装，这是咋回事呢？

### ISSUE THREAD

**Issue by huoguangxuan** [firekylin/firekylin#622]
heroku部署的，安装也成功了。过一段再打开网页又让安装，这是咋回事呢 @lizheming

**Comment by wei** [comment]
heroku没有永久存储  目前一些信息是存在文件系统里的  比如 .install 文件和数据库连接等。heroku重启就自动抹去了

https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted
