### ISSUE TITLE
如果是管理员，请到后台添加地址为 links 的页面，点击这里添加。

### ISSUE THREAD

**Issue by hdq924** [firekylin/firekylin#623]
如果是管理员，请到后台添加地址为 links 的页面，点击这里添加。
请问about和links页面如何生成呢？

**Comment by wei** [comment]
新建页面 取名 links 即可

**Comment by hdq924** [comment]
请问页面文件放到firekylin/www目录下吗？页面需要在后台菜单关于，链接，位置要修改路径不？

**Comment by wei** [comment]
没那么麻烦  在后台登陆进去就可以点击 【页面管理】然后【添加页面】
