### ISSUE TITLE
firekylin1.2.3 后台错误

### ISSUE THREAD

**Issue by YWDMB** [firekylin/firekylin#624]
1. https://github.com/firekylin/firekylin/archive/1.2.3.zip
2. yarn install
3. 浏览器可以访问前端
![93d64f1c2f9acc1e8c4e1d2dbe7364f](https://user-images.githubusercontent.com/25597590/54172461-201e3580-44b9-11e9-98f7-ddac0d119bf9.png)
4. 访问后台控制台错误
![6f13a36d7260cbed23df7e18cd97f6e](https://user-images.githubusercontent.com/25597590/54172548-6c697580-44b9-11e9-8be5-74ebd25a1e26.png)

**Comment by YWDMB** [comment]
![c72eb6d42bbfb6af7c3908e560a34d8](https://user-images.githubusercontent.com/25597590/54172849-76d83f00-44ba-11e9-98be-913b30798302.png)

**Comment by lizheming** [comment]
清一下浏览器缓存

**Comment by YWDMB** [comment]
![81b712966724450734918123dc6e7ee](https://user-images.githubusercontent.com/25597590/54176528-2e288200-44ca-11e9-8fe8-aff2c3558e13.png)
![001eb934dce985eabe8af3838609dcd](https://user-images.githubusercontent.com/25597590/54176530-31bc0900-44ca-11e9-95a8-c353ba2e3208.png)

**Comment by YWDMB** [comment]
与缓存无关吧

**Comment by lizheming** [comment]
使用 yarn 安装复现了你这个问题，应该是版本依赖导致的。建议先用我们编译好的文件 https://github.com/firekylin/firekylin/releases/download/1.2.3/firekylin_1.2.3.tar.gz 安装，或者使用 npm 安装。

**Comment by YWDMB** [comment]
问题解决了，要使用 npm 安装 。
