### ISSUE TITLE
百度统计代码，显示代码未生效

### ISSUE THREAD

**Issue by Dangerxfh** [firekylin/firekylin#630]
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?1b562844bdffdf5ba38f3e57b9bc717b";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

**Comment by lizheming** [comment]
有在线地址没，提供一下我们看看。

**Comment by Dangerxfh** [comment]
> 有在线地址没，提供一下我们看看。

已发送到您的邮箱

**Comment by Dangerxfh** [comment]
> 有在线地址没，提供一下我们看看。

现在正确了。。。。感谢

**Comment by lizheming** [comment]
好的
