### ISSUE TITLE
系统安装过程中显示数据库信息有误，但是在本地利用mysql命令可以成功登陆，数据库编码是utf8

### ISSUE THREAD

**Issue by itpwuwei** [firekylin/firekylin#634]
![image](https://user-images.githubusercontent.com/41659547/57497218-46e4c680-72c6-11e9-8c1b-29b8d6d5a19a.png)

**Comment by wei** [comment]
此公网 ip 提示 3306 端口未开。请贴上本地成功连接的命令

**Comment by itpwuwei** [comment]
好的，多谢！！！
