### ISSUE TITLE
新增分类，网站首页就500错误了

### ISSUE THREAD

**Issue by jameswatt2008** [firekylin/firekylin#641]
本地部署上去，在后台新增分类，然后主页就进500错误了
后端新增标签进去不。

这都是从零部署的时候出现的

**Comment by lizheming** [comment]
看看控制台具体报什么错误？

**Comment by lizheming** [comment]
我本地按照你说的重新安装了下复现了，是因为之前做分类文章统计的时候有一个字段未做空判断导致 SQL 执行出错了，目前已经fix了，你可以等待下次发版修复，感谢你的反馈。
