### ISSUE TITLE
请问摘要的标签是什么？默认模板没有，.summary？调用不出来

### ISSUE THREAD

**Issue by lopins** [firekylin/firekylin#644]
请问摘要的标签是什么？默认模板没有，.summary？调用不出来,文章中已添加
```
如果您对 Firekylin 不是很熟悉，可以先阅读以下常用操作了解一下。<!--more-->

这是程序自动发布的文章。如果您看到这篇文章，表示您的 Blog 已经安装成功
```

**Comment by Lopins** [comment]
![TIM截图20190818182158](https://user-images.githubusercontent.com/44494732/63223243-360cf080-c1e5-11e9-81e6-66ffca5c4b0e.png)
![TIM截图20190818182232](https://user-images.githubusercontent.com/44494732/63223246-3a390e00-c1e5-11e9-97cf-49439c91a12c.png)

**Comment by lizheming** [comment]
`<!--more-->` 需要单独一行才行呢

**Comment by Lopins** [comment]
预览正常，发布不解析

![文章withTOC](https://user-images.githubusercontent.com/44494732/63225604-2d77e280-c204-11e9-8aea-198b2200b0f4.png)

![预览](https://user-images.githubusercontent.com/44494732/63225615-4d0f0b00-c204-11e9-91e2-07321285988b.png)

**Comment by Lopins** [comment]
> `<!--more-->` 需要单独一行才行呢

有没有TOC都是一样的

**Comment by lizheming** [comment]
没看懂您的意思，`<!--more-->` 仅用于在列表页获取摘要部分，在详情页解析成 HTML 注释是正常现象。

**Comment by Lopins** [comment]
在详情页单独调用 `{{post.summary | safe}}` 在预览页中正常，在正式页中获取不到这个标签值

**Comment by Lopins** [comment]
列表页(`\archives`)中 `{{item.summary | safe}}` 也是空白

**Comment by lizheming** [comment]
那证明数据库数据是正常的，两种情况需要去 check 一下，要么是你使用错变量读取了，要么就是这个数据在当前的模板中并没有被注入。如果是 `archives` 页面的话后者的可能性会更高点。

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/blob/master/src/home/model/post.js#L193-L209v 确认了下，是这样的，在归档页面并没有注入正文的详情，只有标题和路由以及时间。

**Comment by Lopins** [comment]
好的，请问一下这个变量作用在什么地方，还要列表页的摘要标签是什么？我用` .summary `输出不了,文章页只有预览里面才能看到摘要，正常发表摘要获取不到。
![TIM截图20190819095909](https://user-images.githubusercontent.com/44494732/63234577-69449380-c268-11e9-8934-ec32bc8bfa5a.png)

**Comment by lizheming** [comment]
就是文章列表页呀，你切回默认主题自己看一眼就明白了。

**Comment by Lopins** [comment]
后台有很多地方出现白屏：`/admin/appearance/theme`，`/admin/tag/list`，我看github上最新版本包已经修复了，但是这个问题依然存在

**Comment by Lopins** [comment]
这个问题是注释掉`package.json`文件中这几行出现的
![image](https://user-images.githubusercontent.com/44494732/63234891-e7ee0080-c269-11e9-9371-d471a75bd7a1.png)

**Comment by lizheming** [comment]
清一下浏览器的缓存

**Comment by Lopins** [comment]
切换会默认主题后，摘要没有问题，但是后台标签列表还是白屏的

**Comment by lizheming** [comment]
清一下浏览器的缓存
