### ISSUE TITLE
console 里疯狂提示Uncaught ReferenceError: h is not defined

### ISSUE THREAD

**Issue by matinjugou** [firekylin/firekylin#645]
console里一直在输出Uncaught ReferenceError: h is not defined，而且我还是打不开tag/list这个页面，1.2.8的版本

**Comment by matinjugou** [comment]
发现用仓库版build完成后覆盖掉www/static目录就没有问题了，但是这build出来的应该是dev版本的吧。prod版本可能有问题

**Comment by lizheming** [comment]
好像是 uglify 有冲突了，先暂时把 uglify 去了解决了。
