### ISSUE TITLE
新安装后初始密码是什么？

### ISSUE THREAD

**Issue by llawo** [firekylin/firekylin#725]
我设置完数据库信息后下一步，admin账号密码都还没来得及设置就重定向到登录页面了，这是一个bug吧！

**Comment by lizheming** [comment]
数据库中是否已经有 firekylin 的表了，已经有的话会直接使用旧的数据表，没有的话会让设置账户的。

**Comment by llawo** [comment]
我使用firekylin.sql生成空表后执行的安装，但是在填完数据库连接信息后，点下一步是有一个设置密码的页面，但是这个页面只出现几秒就重定向到登录页了，根本来不及填密码；后面我删除项目重新安装一次也是同样的结果；在网上查找了一些资料，但是看到的设置密码是在设置数据库连接信息的下面，是在同一页的，可能版本不一样吧，我下载的最新版的；想问下密码加密是怎么加密的，现在我想直接表里插入一个账户密码

**Comment by lizheming** [comment]
已经生成表的话就需要自己手动插入用户了，比较推荐先本地数据库生成一个然后导到线上去，要不然自己整还挺麻烦的，用的 passwordhash 的库。

**Comment by llawo** [comment]
好的，谢谢你！还有个问题想问下，初次安装在填写数据库信息前需要手动创建好数据库和数据表吗？还是在初次安装时填写好数据库信息，点下一步程序会自动创建好数据库和数据表

**Comment by lizheming** [comment]
对，不需要手动导数据，程序会自动导入并初始化。当然前提是你的数据库账号有写入权限了。

**Comment by llawo** [comment]
谢谢了！我重新弄了下弄好了，在安装之前没有先手动创建数据库和表，那个设置密码的页面就不会被重定向到登录页了
