### ISSUE TITLE
使用markdown倒入文章现实上传失败

### ISSUE THREAD

**Issue by hesunfly** [firekylin/firekylin#726]
使用markdown倒入文章现实上传失败
![image](https://user-images.githubusercontent.com/33787409/66801274-1a0a9e80-ef4b-11e9-9420-3e8b0b3052ed.png)

**Comment by lizheming** [comment]
压缩包一级目录木能有文件夹，如果还不行邮件把 tar 包发我我试试

**Comment by hesunfly** [comment]
@lizheming  多谢，看了一下确实有文件夹。现已成功上传
