### ISSUE TITLE
8360端口没有打开

### ISSUE THREAD

**Issue by LadySky** [firekylin/firekylin#728]
我在阿里云上准备代建一个博客，现在域名备案还没批下来，我使用的ip访问，这是我的Nginx配置：
```
server{
    listen 443;
    server_name  www.***.com;
    root /Users/welefen/Develop/git/firekylin/www;
    set $node_port 8360;

    ssl on;
    ssl_certificate  %path/ssl/3165588_www.***.com.pem;
    ssl_certificate_key %path/ssl/3165588_www.***.com.key;

    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA;
    ssl_session_cache shared:SSL:50m;
    #ssl_dhparam %path/ssl/dhparams.pem;
    ssl_prefer_server_ciphers on;


    index index.js index.html index.htm;

    location ^~ /.well-known/acme-challenge/ {
      alias %path/ssl/challenges/;
      try_files $uri = 404;
    }

   location / {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

    location = /development.js {
        deny all;
    }

    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
   }


   location ~ /static/ {
      etag         on;
      expires      max;
   }
}
```
现在是访问不了我的博客，netstat -nptl没见8360端口开放，哪位大佬能帮忙看看是哪里出问题了？

**Comment by wei** [comment]
npm start / pm2 运行了吗?

**Comment by lizheming** [comment]
阿里云有安全组，最好看下 80, 8360, 443 等端口有没有在安全组开放出来。

**Comment by wei** [comment]
@lizheming 他在本地netstat -nptl没显示应该就是 node部分没运行吧

**Comment by lizheming** [comment]
@wei 哦哦，那可能是，等他确认下吧。

**Comment by LadySky** [comment]
我是通过:
pm2 startOrReload pm2.json
service nginx restart
还需要运行：npm start这个命令吗？我一运行报很多错误
我阿里的安全组都打开了；@wei

**Comment by LadySky** [comment]
[root@iZ2zec4xgjixyxamb9l720Z ~]# npm start
npm ERR! Linux 3.10.0-1062.1.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v13.2.0
npm ERR! npm  v3.10.10
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
@wei

**Comment by lizheming** [comment]
进到项目根目录下再执行 `npm start`，你现在都不在项目目录。

**Comment by LadySky** [comment]
> 
> 
> 进到项目根目录下再执行 `npm start`，你现在都不在项目目录。

好了 端口开启了 谢谢！

**Comment by LadySky** [comment]
好了 端口开启了 谢谢！@lizheming
