### ISSUE TITLE
基本配置中域名地址是否加端口号呢？？

### ISSUE THREAD

**Issue by li395092734** [firekylin/firekylin#729]
我的加上端口号才能添加文章和其它的操作，前端访问也是没有问题的。但是，想使用评论功能的话，就默认把我的端口号去除了。然后，我再加上。导致评论也不能用，自己的添加文章的功能，也不能使用了。这个是什么原因呢？

**Comment by li395092734** [comment]
![dddd](https://user-images.githubusercontent.com/50952020/70290323-7636c400-1812-11ea-9a86-deed495835a2.png)

**Comment by li395092734** [comment]
`www.lydms.com`这个网址，我的左面的个人头像显示不出来，但是在加上端口号以后`www.lydms.com:8360`，就能显示出来，这个是为什么呢？？
![fff](https://user-images.githubusercontent.com/50952020/70290448-da598800-1812-11ea-88bc-986c40c2b346.png)

**Comment by lizheming** [comment]
nginx 配置中的 root 需要指定到项目的 `www` 目录下。

**Comment by li395092734** [comment]
更改了以后还

> nginx 配置中的 root 需要指定到项目的 `www` 目录下。

更改了以后还是不行，还是过去的那俩问题。没有解决；
![到达目录](https://user-images.githubusercontent.com/50952020/70306266-62568680-1841-11ea-94a8-edaa029290cb.png)
![Nginx配置文件](https://user-images.githubusercontent.com/50952020/70306277-697d9480-1841-11ea-9d59-b2955436fd38.png)

**Comment by lizheming** [comment]
更改后需要重启 nginx 服务

**Comment by li395092734** [comment]
> 更改后需要重启 nginx 服务
已经重启了，还是这样的效果；还是没有显示图标，下面的自动更新为不带端口号的。
![重启](https://user-images.githubusercontent.com/50952020/70307291-cf6b1b80-1843-11ea-81a2-ad7b90c3471d.png)
![网站地址](https://user-images.githubusercontent.com/50952020/70307305-d42fcf80-1843-11ea-9307-d7d602689b4d.png)
![头像](https://user-images.githubusercontent.com/50952020/70307359-f0cc0780-1843-11ea-8e67-785d5bc65412.png)

**Comment by lizheming** [comment]
http://www.lydms.com/static/upload/20191204/logo.jpg 
目前看是静态资源 nginx 返回 403，https://github.com/firekylin/firekylin/issues/117 https://github.com/firekylin/firekylin/issues/144 参考下这两个 issue 看看吧，一般都是文件夹权限的问题。

**Comment by li395092734** [comment]
问题已经结果：
问题一：基本配置中域名地址是否加端口号呢？？
不加端口号；配置网址为:http://www.lydms.com
问题二：个人头像不显示（访问静态页面403错误）？
打开自己的`/etc/nginx/nginx.conf`目录；
用户改为root用户，重启nginx即可
```
user root;
```
问题三：后台上传文档更新失败？
后端的访问的地址应为`http://www.lydms.com/admin`，不加端口号；

**Comment by lizheming** [comment]
好的，给你点赞！
