### ISSUE TITLE
[政策问题] 需要增加备案号 去掉博客字样

### ISSUE THREAD

**Issue by songguangyu** [firekylin/firekylin#731]
Hi. 刚刚接收到ZF通知，网站需要去掉 `博客` 字样 建议换成`空间`， 并且需要在底部添加备案号，只给了一周的时间来处理问题，请问能否支持此功能？感谢！

**Comment by wei** [comment]
你说的设置里都可以改哇。

**Comment by lizheming** [comment]
是的，进入后台 <kbd>系统设置</kbd> - <kbd>基础设置</kbd> 中，站点名称、工信部备案、公安备案都是可以配置的。

**Comment by songguangyu** [comment]
Thanks!
