### ISSUE TITLE
Wiki中Docker安装部分麻烦新建页面

### ISSUE THREAD

**Issue by xlanger** [firekylin/firekylin#732]
我的blog后面可能不续期了，Docker安装部分还请建一个Wiki页面吧，文档在：https://github.com/xlanger/docker-install-firekylin-wiki

**Comment by lizheming** [comment]
好的，感谢你的提醒~

**Comment by xlanger** [comment]
不客气（后面补充了docker-compose.yml参考）

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/wiki/Docker-安装 已添加页面，谢谢你的文章。
