### ISSUE TITLE
如何，更改备案的绑定的网址呢？

### ISSUE THREAD

**Issue by li395092734** [firekylin/firekylin#736]
工信部备案绑定的过去的网址失效了，但是没有新的绑定的网址的路径设置；
旧版路径：http://www.miitbeian.gov.cn/
新更新的路径：http://beian.miit.gov.cn

**Comment by lizheming** [comment]
https://github.com/firekylin/firekylin/blob/master/www/theme/firekylin/layout.html#L111

默认主题很早就已经修改了这个啦，如果使用的是默认主题的话直接更新下 Firekylin 版本就可以了，如果不是默认主题的话需要自己找到对应的位置修改下。
