### ISSUE TITLE
插入图片cos图片 自动带上了当前域名 导致打不开

### ISSUE THREAD

**Issue by wanglong167** [firekylin/firekylin#737]
![image](https://user-images.githubusercontent.com/456516/72269017-d153a600-365d-11ea-8dd1-13c33877bf8c.png)
 
![image](https://user-images.githubusercontent.com/456516/72267826-af592400-365b-11ea-9670-817bd9bf35b5.png)

配置
![image](https://user-images.githubusercontent.com/456516/72266734-eb8b8500-3659-11ea-90e7-5d2fdaee3506.png)

FireKylin版本：1.3.0

**Comment by lizheming** [comment]
修复叻，感谢反馈啦~
