### ISSUE TITLE
一个bug，文件位置问题

### ISSUE THREAD

**Issue by yangshuaidu** [firekylin/firekylin#739]
我安装后，后台白屏，我看到也有人问了，但我的找到原因了
我看了nginx的错误日志，发现他使用的位置是
`"/usr/local/www/fkblog/static/js/vendor.js"`
类似这种错误，要static这个目录
然后我进入网站目录，并没有看到这个static目录，然后，，我在另一个文件夹里再次解压，在解压过程中，我看到了static，在网站根目录的www文件夹里，目前，我是做了一个指向他的链接，，现在是可以正常访问后台了
![Screenshot_2020_0309_025717](https://user-images.githubusercontent.com/61946790/76169300-c3c82180-61b1-11ea-9c25-d077ebf60341.png)
这是nginx错误日志截图

这是我的目录截图

**Comment by yangshuaidu** [comment]
嗯？？，目录那张图，好像不见了，，

**Comment by lizheming** [comment]
唔，nginx 的配置应该要把 root 设置到 `www` 那个目录的说，感觉你应该配置到项目根目录了？

**Comment by yangshuaidu** [comment]
我知道了，，感谢，，建议在安装说明中说明一下，一些人可能会忽略掉后面www，配置在根目录，因为这样还是可以访问，只是后台无法访问。

**Comment by lizheming** [comment]
好的，感谢反馈 https://github.com/firekylin/firekylin/wiki/%E5%AE%89%E8%A3%85 已经在该页面进行补充了。

**Comment by yangshuaidu** [comment]
@lizheming 还有一个问题，我将域名由blog更改为www，之后文章里面域名也自动改了，但，在后台，进行发布文章，上传图片这类操作一直报错，然后我在系统设置中看到域名还是原来的，修改后，无法保存，也是报错，，通过修改数据库里内容解决了，，，

**Comment by lizheming** [comment]
@yangshuaidu 是这样子的，接口为了避免 CSRF 问题做了 referer 校验，是根据基础设置中的域名来判断的。一般改域名是建议在改之前先把基础设置换掉然后再改比较好。
