### ISSUE TITLE
base controller硬编码了模板文件后缀

### ISSUE THREAD

**Issue by aztack** [firekylin/firekylin#74]
[src/home/controller/base.jsde displayView](https://github.com/75team/firekylin/blob/master/src/home/controller/base.js#L49)中硬编码文件后缀为'.html'。
建议从config/view.js中设置的file_ext读取。
这样有助于后期增加新的theme。theme提供者可能使用其他模板引擎。比如jade

**Comment by welefen** [comment]
这块后续会抽取出来

**Comment by lizheming** [comment]
考虑到之后会增加动态渲染等特有功能，暂时先不考虑多模板的适配，先关闭此问题。
