### ISSUE TITLE
代码块问题，最后一行不显示

### ISSUE THREAD

**Issue by yangshuaidu** [firekylin/firekylin#740]
这是编辑界面
![捕获](https://user-images.githubusercontent.com/61946790/76495729-6b737700-6472-11ea-9354-264c9b220cbb.PNG)
这是发布后界面
![捕获1](https://user-images.githubusercontent.com/61946790/76495797-95c53480-6472-11ea-9964-39b35133b0e3.PNG)
右边预览小窗可以显示，但预览页面和发布后页面，不显示最后一行，不管有几行只有最后一行不显示，如果不停的刷新，会有一瞬间显示，之后没有，通过浏览器源代码界面能看到最后一行内容

**Comment by lizheming** [comment]
应该是之前的 PR 加行号显示加的逻辑，已经修复了下个版本会发布，感谢反馈。
