### ISSUE TITLE
新版本1.3.1在线升级后，后台白屏，后台提示的下载链接的包也好像有问题

### ISSUE THREAD

**Issue by yangshuaidu** [firekylin/firekylin#741]
在线升级后白屏，控制台错误信息
![捕获](https://user-images.githubusercontent.com/61946790/76685251-340cf200-664d-11ea-8608-7359ab2d932c.GIF)

后台提示的下载链接，下载升级后502，然后还发现了这个
![批注 2020-03-14 234312](https://user-images.githubusercontent.com/61946790/76685310-a2ea4b00-664d-11ea-84b1-b30a43da0d7b.png)

上面的是升级后的，下面的是还原原先的，是不是放错了

**Comment by lizheming** [comment]
唔，0.x 版本升级到 1.x 版本的话需要参考下文档升级 https://github.com/firekylin/firekylin/wiki/0.x%E5%8D%87%E7%BA%A7%E8%87%B31.x

**Comment by yangshuaidu** [comment]
@lizheming 不是啊，，后台提醒更新，点在线更新，升级后白屏，点下载更新，下载下来的包版本是0.x的

**Comment by lizheming** [comment]
在线更新如果白屏的话清一下浏览器的缓存试试，刚刚用自己的博客试了下1.3.0在线更新1.3.1，没有问题。另外下载更新那个地址的确是个问题，这块一直没改，我改一下吧。

**Comment by yangshuaidu** [comment]
嗯，我在试下

**Comment by yangshuaidu** [comment]
能提供一下后台，对手机的适配么，或者手机编辑方法，，手机进后台，编辑器的工具栏就会变成两行，挡住一部分，

**Comment by lizheming** [comment]
恩，现有后台对移动端是没有很好的适配。之前是打算做一个小程序来作为移动端适配的方法的，之后看谁有空帮忙弄下吧~

**Comment by lxjcxj** [comment]
@yangshuaidu 修改/view/admin/index_index.html最后一行插入<script src="/static/js/vendor.js?v=25fd8">

修改后为</script> <div id=app></div><script src="/static/js/admin.js?v=8e2d6"></script><script src="/static/js/vendor.js?v=25fd8"></script>><script src="/static/js/vendor.js?v=25fd8"></script></body></html>

**Comment by yangshuaidu** [comment]
@lxjcxj
