### ISSUE TITLE
sitemap 问题

### ISSUE THREAD

**Issue by yangshuaidu** [firekylin/firekylin#743]
访问sitemap 页面502
，
我刚刚想使用sitemap,但设置里没找到，搜索了下，看到有，便访问了下看看，
然后，显示502
之后所有网页全都无法访问，所有页面全部显示
`Internal Server Error`，重启软件不行，重启服务器后，才会恢复
然后，我又访问了下，还是502，但这次只有部分页面变成`Internal Server Error`其他还能访问

**Comment by lizheming** [comment]
https://75.team/sitemap.xml 我看了下是可以的，你的地址提供下我去看一下？

**Comment by yangshuaidu** [comment]
https://www.moebsd.cn/sitemap.xml

**Comment by yangshuaidu** [comment]
可能看不了，刚刚发现全部又变成`Internal Server Error`了只要有人一点这个链接，就出现

**Comment by lizheming** [comment]
@yangshuaidu 看起来像是访问 sitemap.xml 的时候服务出错了导致整体服务宕了所以都出 502 了。你能直接使用 `node production.js` 在后台启动一下，然后访问下 sitemap.xml 看看有什么错误信息出现吗？

**Comment by yangshuaidu** [comment]
这个么，看起来不像
![Screenshot_2020_0328_173151](https://user-images.githubusercontent.com/61946790/77820025-3590ec80-711a-11ea-8d2b-16566f782954.png)
这个是之后出错后，在访问时的内容
![-244975f2553a9e37](https://user-images.githubusercontent.com/61946790/77820429-4b53e100-711d-11ea-9643-ff8c20877bdc.png)

**Comment by lizheming** [comment]
这个错误信息确实看不太出来什么… 不介意的话是否可以让我去你机器上看一下？下面是我的公钥，或者提供下账号密码发我邮箱也可以，我的邮箱个人主页上有。

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQClUZXHYZpyLyDSDSlykD71OUFrEkCarFtD6DBz+phrb1xqVjxV/cGZanA12Go2R234hmkH6U5bltimoU9M2/rsc0LGyfbB31pbFS3kPQDeXzZ6lA4FMRYa80S5iMNYdNTuy+YBJ1HWZpjA8DMjYcaFZQVcVEMwEFkefttu6fPVN6ykBsVrgiJxK+hMfESEmixIHM4hStp6ZiLyRSQ+XGK11BjxH5FAvKroFo+93VqbkO7Z7vVtMqE9VbgyUjVjqBjjumZUnJZ6idp2K7BTSI/7gNG3C6XimY3TfySsljzBu/UtwrW45wxq0WNYMbT9/VPgoQUlQKfZm2Hc/xyxByyvS55Io5M0LWGO2IHkXe+IP+iypQBJnoslJETpBCdngNlPs/UCARZlaBm+x+rRFbFM9PMzIx+ByK3E+CgKJCc292wu0p4xEDja7TigbqMVTN5IRjf7aVk/++VN+vuvlkTNtE24mRLCPTgJODevSQ3lMP48k3NMFKXFkKrxU6IavW8HvUucREzKA9VbqqdRa8u82CbHT7yPJV5hWlR2xTnND6Ile6HPDldoTeuBHcmJ7nFKjiqJP+ViCq4WX/V9CO606X8zrZg+yX1dBuj4DyY3Prb0L2YUyoqgBt80RE9ikzvpnyFJW4GLUGJugWU0Th8RYZZF1KWYjw9+yjJYXy6Qbw==
```

**Comment by yangshuaidu** [comment]
公钥加上了

**Comment by lizheming** [comment]
应该可以了 https://www.moebsd.cn/sitemap.xml 你试一下。

查了一下主要原因是因为后台有一个每页显示多少篇文章的配置 `postsListSize`，不知道为什么你的数据库里这个字段是空，然后 `sitemap.xml` 这块会取这个字段的数来计算分页数，为空的话运算之后就是 `NaN` 了，导致后续模板循环遍历的时候异常了最终导致 node 进程崩溃。然后不知道为什么这种情况下会连带 mysql 进程也同时崩溃。所以你重启 node 进程无效，只能重启机器（实际上重启机器就是守护进程开启 mysql 的过程）才能生效。

然后我把你的数据修正了下之后已经可以了。其实这个字段用到的地方应该比较多，其它地方这块应该都已经有兼容会有一个默认值的，所以你会发现首页都是正常的，但是 `sitemap.xml` 这个应该是用到的场景比较少所以我这边也给忘记了导致这块有遗漏，我之后修复一下吧。

ps. 你记得把我的公钥删了哦

**Comment by yangshuaidu** [comment]
感谢，。
