### ISSUE TITLE
Gitalk评论集成认证更新方式

### ISSUE THREAD

**Issue by opsarno** [firekylin/firekylin#747]
[GitHub] Deprecation Notice https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

目前Gitalk配置
```
{
    "clientID": "",
    "clientSecret": "xxxxxxxxx",
    "repo": "x'x'xxxxxxx",
    "owner": "xxxx",
    "admin": [
        "xxxxx"
    ],
    "distractionFreeMode": true,
    "githubUserName": "xxx",
    "githubPassWord": "xxxxxxxx"
}
```

是不是改成新的认证方式集成呀。

**Comment by opsarno** [comment]
```
{
    "clientID": "",
    "clientSecret": "xxxxxxxxx",
    "repo": "x'x'xxxxxxx",
    "owner": "xxxx",
    "admin": [
        "xxxxx"
    ],
    "distractionFreeMode": true
}
```

去掉最后2行账密，也可以使用。 这样估计就不会再收到GitHub邮件了吧。

**Comment by lizheming** [comment]
是否更新认证这个取决于 Gitalk 那边，Firkeylin 这只是负责帮忙快速接入 Gitalk 而已，实际上配置目前都是直接 JSON 传给 Gitalk 的实例的，目前 Gitalk 引入的版本也是最新的版本。如果 Gitalk 有问题的话可以去 https://github.com/gitalk/gitalk/issues gitalk issues 里提一下。
