### ISSUE TITLE
代码块不能按指定的格式高亮

### ISSUE THREAD

**Issue by MaxxMoney** [firekylin/firekylin#748]
加上yaml没有高亮

![image](https://user-images.githubusercontent.com/59759939/87274219-cf37aa80-c50d-11ea-90e9-d5c494b40802.png)

不加的话又识别成别的

![image](https://user-images.githubusercontent.com/59759939/87274290-fb532b80-c50d-11ea-9329-c2df07705fa7.png)

服务器系统：linux
Node.js版本：8.17.0
V8引擎版本：6.2.414.78
MySQL版本：5.5.65-MariaDB
ThinkJS版本：3.2.11
FireKylin版本：1.3.1

**Comment by lizheming** [comment]
正则有点小问题，已经修复了，等下次发版的时候带上，感谢反馈。
