### ISSUE TITLE
请问一下这个项目可以部署到GitHub Pages上吗

### ISSUE THREAD

**Issue by Lopins** [firekylin/firekylin#752]
请问一下这个项目可以部署到GitHub Pages上吗
怎么隐藏数据库配置文件（好像GitHub Pages项目库必须公开才行）

**Comment by wei** [comment]
感谢提交 issue。

不可以哈 GitHub Pages 是静态托管。本项目需要 node 环境也需要数据库连接，这些 GitHub Pages 是不提供的哈。: D

**Comment by lizheming** [comment]
是的，Github Pages 只支持静态博客托管，后续我会考虑适配 [Vercel](https://vercel.com)。

**Comment by Lopins** [comment]
你好，我的意思是说像小程序一样，通过API在GITHUB静态页上调用

**Comment by lizheming** [comment]
@Lopins 不是非常理解，是想说静态页调接口渲染数据？

**Comment by Lopins** [comment]
> @Lopins 不是非常理解，是想说静态页调接口渲染数据？

是的

**Comment by lizheming** [comment]
@Lopins 那和数据库文件没啥关系吧，你的 Firekylin 没有部署在 Github Pages 上，只是你 Github Pages 上的一个静态页调用了 Firekylin 提供的接口而已。Firekylin 是提供接口访问的，在访问的 URL 后增加 `.json` （如果后面有 `.html` 的话就替换），就可以得到纯数据的 JSON 接口了。

**Comment by Lopins** [comment]
> @Lopins 那和数据库文件没啥关系吧，你的 Firekylin 没有部署在 Github Pages 上，只是你 Github Pages 上的一个静态页调用了 Firekylin 提供的接口而已。Firekylin 是提供接口访问的，在访问的 URL 后增加 `.json` （如果后面有 `.html` 的话就替换），就可以得到纯数据的 JSON 接口了。

好的，了解了，就是这个意思。
