### ISSUE TITLE
如何在公安部备案号前加上备案图标

### ISSUE THREAD

**Issue by Genliese** [firekylin/firekylin#753]
![image](https://user-images.githubusercontent.com/28807542/98803223-61fe3c80-244f-11eb-88b8-b19df70c8d4d.png)
就这个图标

**Comment by wei** [comment]
可以编辑主题 https://github.com/firekylin/firekylin/blob/ab1e85fa6c3be87e8f74a1f2363038858c46b0d0/www/theme/firekylin/layout.html#L113-L116

**Comment by lizheming** [comment]
后台 <kbd>外观设置</kbd> > <kbd>主题管理</kbd> > <kbd>自定义CSS</kbd> 中把下面的内容贴进去：

```
.beian ~ .beian {
    padding-left: 17px;
    background: url(https://web-resource.mucang.cn/maiche.web/mucang.official/official/resources/images/new-version/beian.png) no-repeat 0 0;
    background-size: 17px 17px;
}
```

**Comment by Genliese** [comment]
> 后台 外观设置 > 主题管理 > 自定义CSS 中把下面的内容贴进去：
> 
> ```
> .beian ~ .beian {
>     padding-left: 17px;
>     background: url(https://web-resource.mucang.cn/maiche.web/mucang.official/official/resources/images/new-version/beian.png) no-repeat 0 0;
>     background-size: 17px 17px;
> }
> ```

非常感谢(*^▽^*)

**Comment by Genliese** [comment]
> 可以编辑主题
> 
> https://github.com/firekylin/firekylin/blob/ab1e85fa6c3be87e8f74a1f2363038858c46b0d0/www/theme/firekylin/layout.html#L113-L116

非常感谢(*^▽^*)
