### ISSUE TITLE
如何获取网站的所有文章的地址呢？

### ISSUE THREAD

**Issue by li395092734** [firekylin/firekylin#757]
主要是为了满足百度搜索爬虫的搜索的，需要自己提交当前网站的地址进行操作的。下面是网址：[https://ziyuan.baidu.com/linksubmit/index](url)

**Comment by lizheming** [comment]
`<博客地址>/sitemap.xml` Firekylin 会有一个 sitemap 的页面，可以提交这个地址，例如 https://75.team/sitemap.xml

**Comment by li395092734** [comment]
已经解决了，谢谢、
