### ISSUE TITLE
请问哪里有更多的主题列表，或者有什么投稿渠道吗

### ISSUE THREAD

**Issue by matinjugou** [firekylin/firekylin#758]
主题列表两年没更新了

**Comment by lizheming** [comment]
目前还没有一个主题列表的地方，主要是使用者中有自定义主题的用户的确少之又少。https://75.team/ 目前奇舞团的官网是用 Firekylin 自定义主题做出来的。如果你那边有好的主题的话，可以 issue 推荐一下，我在首页上加一下。

**Comment by matinjugou** [comment]
那我再优化优化然后放issue吧。

**Comment by lizheming** [comment]
好的，没问题。ps. 其实本人也转静态博客了（逃…

**Comment by matinjugou** [comment]
> 好的，没问题。ps. 其实本人也转静态博客了（逃…

好家伙，我直接好家伙。静态博客有啥优势吗

**Comment by lizheming** [comment]
哈哈，我主要是有点疲于维护主机了，而现在有很多免费部署静态博客的服务，具体的心历路程可以参考我之前写的文章 https://imnerd.org/blog-migrate-to-hugo.html。

当然本博客程序 Firekylin 我还是会继续维护下去的，如果有什么痛点的话可以随时 issue 讨论。
