### ISSUE TITLE
分享一个自己写的主题

### ISSUE THREAD

**Issue by matinjugou** [firekylin/firekylin#759]
每年微调一次。。。。
https://github.com/matinjugou/firekylin-theme

**Comment by lizheming** [comment]
赞一个，已经将主题仓库和博客地址都添加到了 README 当中~ 
ps. Gitalk 有比较严重的安全问题，不建议使用。推荐使用我开发的另外一款评论系统 [waline](https://waline.js.org) 呀！

**Comment by matinjugou** [comment]
谢谢~Waline想试来着，就是很奇怪是一定要用LeanCloud吗

**Comment by lizheming** [comment]
可以用其它的，目前支持 LeanCloud, CloudBase, MongoDB, MySQL, SQLite, PostgreSQL。如果是用火麒麟的话可以试试 Docker + MySQL 这样在一块维护可能方便点。
