### ISSUE TITLE
RSS订阅路径错误导致404

### ISSUE THREAD

**Issue by WD0XCC** [firekylin/firekylin#763]
主页RSS订阅后，通过订阅打开文章，会在域名后面多一个斜杠，导致404，这个问题要怎么解决啊

**Comment by lizheming** [comment]
提供一下博客地址我看看吧

**Comment by WD0XCC** [comment]
好的
这是博客地址：http://blog.secknow.cn/
这是RSS: http://blog.secknow.cn/rss.html
这是随机一篇文章的订阅地址
http://blog.secknow.cn//post/Ubuntu20.04%20pei-zhi-MySql-yuan-cheng-deng-lu.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Austin ***@***.***&gt;; 
发送时间: 2021年3月26日(星期五) 上午10:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [firekylin/firekylin] RSS订阅路径错误导致404 (#763)





 
提供一下博客地址我看看吧

**Comment by lizheming** [comment]
后台系统设置-基础设置里有一个网站地址，你那里最后的一个 `/` 去掉应该就可以了，你试试吧。

**Comment by WD0XCC** [comment]
好了，谢谢
