### ISSUE TITLE
主题管理，颜色设置，透明度调节条无法移动

### ISSUE THREAD

**Issue by yangshuaidu** [firekylin/firekylin#782]
主题管理，颜色设置，透明度调节条无法移动，一直在最右边，不管鼠标点击还是拖动都没用，
![Screenshot_20211004_222948](https://user-images.githubusercontent.com/61946790/135870582-be189224-c0f2-473f-bab5-b38066a86362.jpg)
，（图是在手机上截的，发现问题时，是电脑操作）
还有就是中间颜色条，和上面大方框，那个点感觉不跟手，，移动那个点，会很生硬的跳过去，而不是跟着鼠标移动，，，感觉很长时间了，到现在还没有啥好看的主题

**Comment by lizheming** [comment]
感谢反馈 1.3.3 版本已修复该问题~ 主题的话确实，可能用的人大部分都是比较喜欢默认主题的吧~
